### ISSUE TITLE
Errors while filtering values

### ISSUE THREAD

**Issue by omri374** [comet-ml/issue-tracking#100]
Hi,
I'm trying to filter out rows in which a certain metric is empty (i.e. equals ""). The UI gives an error message saying "Enter a value before saving". Not sure how to overcome this. See attached screenshot.

![image](https://user-images.githubusercontent.com/3776619/44681896-904bf900-aa4a-11e8-83cb-b82254424bba.png)

Selecting "is not null" doesn't filter these out neither.

Thanks! Comet.ml is great!

**Comment by Nimrod007** [comment]
fixed
