### ISSUE TITLE
Parallel coordinates graph - selecting new metric keeps old metric

### ISSUE THREAD

**Issue by omri374** [comet-ml/issue-tracking#101]
Hi,
The Parallel coordinates feature is awesome! However when I replace the target variable, the old target variable is kept in the Y-axis list. 
Before:
![image](https://user-images.githubusercontent.com/3776619/44682604-85926380-aa4c-11e8-89a3-11de1070ef1f.png)

After replacing the metric:
![after](https://user-images.githubusercontent.com/3776619/44682850-34cf3a80-aa4d-11e8-8f0b-94d8d320ad44.png)

**Comment by ceceshao1** [comment]
Hi @omri374 - I've changed this issue from a `bug` to an `enhancement` upon further review. We do leave **f1** selected as a design choice, but you can simply unselect it if you'd like to exclude it from your chart.

In the future, we may update this UI so replacing a target variable will unselect the previously selected one!

**Comment by Nimrod007** [comment]
fixed
