### ISSUE TITLE
Bar chart assumes experiment id as x axis

### ISSUE THREAD

**Issue by omri374** [comet-ml/issue-tracking#102]
Hi,
The new visualization tools are awesome. When creating a bar chart, the UI asks for an X axis. After selecting a metric as an x axis, it shows a graph with hex values on the x axis (assuming this is the experiment id) and the metric as y axis.
There's a mix between the x and y axes, and the ability to set my own x axis or get a histogram of the metric value across experiments (count per range or value of metric) would be a better representation IMHO.

Thanks!

**Comment by omri374** [comment]
This is both a feature request and a bug. X and Y axes should be switched (If I understand correctly)

**Comment by Nimrod007** [comment]
we added comet panels, you can now code the bar chart how ever you would like.
