### ISSUE TITLE
Hiding experiments on comparison charts

### ISSUE THREAD

**Issue by neighthan** [comet-ml/issue-tracking#103]
The new model comparison charts have a legend on the side showing the experiment key for each of the lines plotted (in the line chart). Clicking on the experiment key toggles the visibility of the associated line. However, it seems that if there's an update to the chart, all of the experiments' lines are toggled back on. I'm not sure if this is a bug or intentional? I think the better behavior would be to keep the same experiments visible as before new data was uploaded since anything invisible the user explicitly didn't want there right now. If you have a running experiment, this essentially makes the toggling visibility useless (by the time I've toggled off the handful of experiments I don't want to see, something has updated, and they're visible again).

**Comment by gidim** [comment]
Thanks for the feedback @neighthan.
This is a bug! We're on it

**Comment by ceceshao1** [comment]
Closing this issue as it has been resolved.
