### ISSUE TITLE
Edit hyperparameters

### ISSUE THREAD

**Issue by neighthan** [comet-ml/issue-tracking#105]
#86 requests being able to edit metric/hyperparameter names. Expanding upon that, I think it would also be nice to be able to edit the values of hyperparameters. For metrics, this probably doesn't make sense, because there's a lot of data there. For hyperparameters, we shouldn't really need to either, but I sometimes do something a bit hacky, especially during quick prototyping, and log a hyperparameter without the logged value actually changing a setting in my model (e.g. because changing the setting is a bit complex, I actually edit the code itself to change it). Thus if I actually changing the setting, but I forget to update the logged hyperparameter to reflect this, then the wrong value is recorded. I've noticed this a few times, but there's not anything I can do about it now.

I could imagine this being implemented either as an edit icon on each row of the hyperparameter table or by double-clicking on an entry turning it into a text field that you can edit.

If other people are more principled than me and don't need a way to fix hackishly set hyperparameters, you can close this =)

---

I'd also like to be able to delete a hyperparameter from a specific experiment entirely, though this isn't as important to be. Mainly for when I have things like {"run_arg_0": "-d"} because I haven't initialized the experiment correctly to not add my command line arguments (which I tend to add myself, properly formatted and such). Not sure if this should be a separate issue? I put it here because I imagine the framework to make hyperparameters editable and to make them deletable would be quite similar. I could also imagine the UI being similar (a delete button on each row?). If the buttons are too cluttering, maybe in the header of the table you could click "Edit" or such to show them (hidden by default).

**Comment by ceceshao1** [comment]
Similar issue to https://github.com/comet-ml/issue-tracking/issues/86

**Comment by Nimrod007** [comment]
you can now add hyper parameter directly from the UI, this will solve this issue.
