### ISSUE TITLE
Add hyperparameter with default value

### ISSUE THREAD

**Issue by neighthan** [comet-ml/issue-tracking#106]
I often find that I have some settings for my models that are initially constant, so I don't log them as hyperparameters. Later, though, I may decide to experiment with more things and then start recording the values I set. However, the previously logged experiments are now missing this hyperparameter in their logs even though they did have it. Simple example for illustration: assume I'm training an MLP and initially I always use just one hidden layer. Later, I decide to try using multiple, so I log something like {"n_layers": 2}. For all of the previous experiments, I implicitly had {"n_layers": 1}, but this wasn't logged. Now I want to compare performance based on "n_layers", but it's harder to filter/group my experiments properly.

The feature I would like is a way (on the website) to add a new hyperparameter to either a set of selected experiments or all experiments in a project (I've only found myself in need of the latter) which is set to a given value, unless that hyperparameter already exists. E.g. suppose I've just run the first few experiments with {"n_layers": 2} and {"n_layers": 3}, now I want to see if adding layers helps. I click something that will add {"n_layers": 1} to all experiments except those that already have a hyperparameter called "n_layers". Now (especially once model comparison charts support grouping by a hyperparamter ;) ), I can easily compare performance.

If you choose to add this, I'm not sure where a great place to put it would be. The hyperparameters table has a lot of space (at least for me; I don't have terribly long names for things), but it seems a bit odd to put something there that affects not just that specific experiment but all experiments in the project (or all those selected).

**Comment by Nimrod007** [comment]
you can now add hyper parameters. metrics and log_other via the rest api, see:  https://www.comet.ml/docs/rest-api/endpoints/#writeparameter
