### ISSUE TITLE
Undo delete experiment

### ISSUE THREAD

**Issue by neighthan** [comet-ml/issue-tracking#107]
When I add something new to one of my experiments, sometimes I have several of them that fail with small bugs before I get things working. This leads to several logs in my experiments table, usually each having a duration of just a few seconds. Once I get things working, I sort by duration and go through these one by one, checking the standard output to confirm I know what went wrong, then deleting them. When you're repeatedly selecting the top box and then deleting, it seems possible that you could accidentally click the select all box instead and out of sheer repetition, delete all of your experiments before you realize you've selected more than one. I haven't done this, but I almost clicked the select all box instead of the box for the top experiment, and I thought of how frustrated I would be if I'd accidentally deleted a bunch of records I still wanted. When you delete an experiment, a box pops up to notify that "Your runs were deleted." I think it would be nice if this box had an "Undo" button that would restore your experiments. I'm not talking about any long-term storage of deleted experiments here, just the ability to undo the most recent deletion within a few seconds of when it happened - enough time that if I accidentally select all instead of one, I can undo that (similar to the Undo for deleting an email in Google's Inbox app, if you're familiar with that).

This is related to #54; if all deleted experiments were archived for some period of time, there wouldn't necessarily be any need for this feature. However, if you don't decide to do archiving, I think this would be nice.

**Comment by Nimrod007** [comment]
Hi @neighthan - great point. we actually do archive experiments. its just not exposed in the UI yet. will update once implemented.

**Comment by pierthodo** [comment]
Any update on the archive experiments feature ?
