### ISSUE TITLE
Metric column sorts incorrectly 

### ISSUE THREAD

**Issue by ceceshao1** [comet-ml/issue-tracking#109]
> First reported by Denny via slack channel: https://cometml.slack.com/archives/C9JPDBXEU/p1535765170000100

"On the experiments list page, when you sort the table, it's sorted lexicographically, so if the column is numeric, the sort order is off e.g. “1100” would come before “150"

User confirmed that the column is a metric type.

Comet.ml team is currently investigating and trying to reproduce

**Comment by Nimrod007** [comment]
fixed.
