### ISSUE TITLE
Error with Docker surfacing notebook warning

### ISSUE THREAD

**Issue by ceceshao1** [comet-ml/issue-tracking#110]
> First reported by Manuel on the slack channel: https://cometml.slack.com/archives/C9JPDBXEU/p1535944764000100

**From the user:**
"I have a problem with jupyter that is more Docker related. My dockerfile calls the following commands:
RUN conda install -y python=${python_version} && \
   pip install --upgrade pip && \
   pip install \
     sklearn_pandas \
     bleach==1.5.0 \
     html5lib==0.9999999 \
     tensorflow-gpu==${TENSORFLOW_VERSION} \
     zarr \
     comet_ml \
     torchsummary && \
   jupyter comet_ml enable
CMD jupyter comet_ml enable && jupyter notebook --port=8888 --ip=0.0.0.0

Yet I still get the error: COMET WARNING: We detected that you are running inside a Ipython/Jupyter notebook environment but we cannot save your notebook source code. Please be sure to have installed comet_ml as a notebook server extension by running:
jupyter comet_ml enable.

According to all the other examples I've seen about Docker this should work, I put the command twice for good measure, but still nothing. I tried issuing the command from bash inside docker but it doesn't affect the jupyter server already running, and I need to have the server running from container creation, any ideas?"

**Comment by Nimrod007** [comment]
fixed
