### ISSUE TITLE
Email notification

### ISSUE THREAD

**Issue by leej35** [comet-ml/issue-tracking#116]
Sending an email notification when a training is finished successfully or failed during the training (with the error message)

**Comment by ceceshao1** [comment]
Thanks for the feature request @leej35 - I've added it to our queue. You can keep track of updates via this github issue!

**Comment by fanweiya** [comment]
I think telegram bot is great idea!

**Comment by dsblank** [comment]
This has now been implemented, and you can in fact use it for your own notification schemes.

See: https://www.comet.ml/docs/python-sdk/Experiment/#experimentsend_notification

Thanks for reporting!
