### ISSUE TITLE
Wrong link for docs

### ISSUE THREAD

**Issue by dsblank** [comet-ml/issue-tracking#117]
On the page `https://www.comet.ml/parameter-optimization` there is the link:

```html
<a href="//docs/"> Check out the Documentation.</a>
```

but should probably be:

```html
<a href="/docs/"> Check out the Documentation.</a>
```

**Comment by dsblank** [comment]
A related error: on an experiment page (such as https://www.comet.ml/dsblank/mnist-006/5a9a2f88cdd54a6eb59ea66699789409) if there are no plotable data points, the help text is:

```html
<p>Use your <a href="undefined/docs/python-sdk/Experiment/">Experiment object</a> to report metrics using <code>log_metric()</code> or <code>log_multiple_metrics()</code>. Please check out the <a href="undefined/docs/python-sdk/Experiment/#experimentlog_metric">documentation</a> for more information.</p>
```

The "undefined" in the links should be removed.

**Comment by dsblank** [comment]
Another help link error: https://www.comet.ml/docs/rest-api/getting-started/ missing video:

![screenshot from 2018-10-02 10-46-44](https://user-images.githubusercontent.com/168568/46356354-95472e00-c630-11e8-9266-aa615f435dc8.png)

**Comment by ceceshao1** [comment]
@dsblank - Doug, thank you so much for reporting these (a triple whammy)!

I've adjusted all three of these items in the webpage + documentation and the changes will be live soon.

**Comment by dsblank** [comment]
Here is another one:  on the HTML page of an experiment, there is this text:
```
No custom html was found by Comet.ml. 
Please refer to the custom params/html guide
```
but guide links to "//docs/python-sdk/getting-started/"  rather than "/docs/python-sdk/getting-started/"

**Comment by Nimrod007** [comment]
fixed

**Comment by dsblank** [comment]
Thanks!
