### ISSUE TITLE
Inconsistent use of "?" on Comet.mt FAQ

### ISSUE THREAD

**Issue by mikaelsouza** [comet-ml/issue-tracking#12]
Not sure if I should report this problem here, but on Comet.ml FAQ webpage there's an inconsistent use of "?".

For example, there are questions like "Would Comet slow down my model’s training?" and "Is this only for deep learning?" where there's no space between the word and the question mark.

However, there are other questions like "Does work with library X ?" and "Do you provide an on-premise installation of comet.ml ?" where it does.

Image example:

<img width="987" alt="cometml" src="https://user-images.githubusercontent.com/9092284/38384368-f821f50a-38dc-11e8-9c8a-dfa6091c7e0c.png">

This is just a silly problem, but it calls my attention.

If this was intentional, you can ignore this issue. Thanks!

**Comment by gidim** [comment]
Thanks @mikaelsouza! That wasn't intentional. We'll fix it ASAP!

**Comment by rememberlenny** [comment]
Thanks @mikaelsouza for flagging this! Just to update you, we have merge the updates here. The production release will go out tomorrow morning.

**Comment by rememberlenny** [comment]
@mikaelsouza This was released last week. Thank you!
