### ISSUE TITLE
Filter/sort graphics by step

### ISSUE THREAD

**Issue by tom-roddick** [comet-ml/issue-tracking#123]
For me one of the most useful features of Comet has been the ability to visualize model inputs and predictions during training, however I'm finding it a bit difficult to use as even after a relatively small number of steps the graphics tab very quickly becomes very cluttered, slow to load and requires a lot of scrolling to see the latest results. It would be great to have the ability to filter the generated images by step or timestamp to cut down on some of the clutter. 

Tensorboard handles this well by having a slider which allows the user to view different versions of the same image. Alternatively minimal solutions could be the overwriting option suggested in #61 or simply sorting the images by timestamp descending so that the most recent images are displayed.

**Comment by EdwardHuCS** [comment]
plus one. I'm doing GAN training and was bummed out to see this feature wasn't there.  Unfortunately image visualization is one of the most important parts of monitoring the GAN training. This is the only thing blocking me from doing a full migration from TB to Comet!

**Comment by Nimrod007** [comment]
added in the new Graphics tab
![home-credit_fa6ecafbcb52433f9acd0bd2c3ad8e69](https://user-images.githubusercontent.com/3535799/49606055-41becc80-f960-11e8-8ae5-b9783304df6d.png)
