### ISSUE TITLE
Control running experiments (e.g. shut down, debug)

### ISSUE THREAD

**Issue by rmst** [comet-ml/issue-tracking#124]
It would be great if we could trigger callbacks in the experiment class from the web interface. Even greater would be if we'd be able to be able to drop into a remote shell using pdb and modify stuff in a running experiment (of course only if security can be ensured).

**Comment by dsblank** [comment]
We have implemented "Stop Experiment" from the web UI.

Being able to connect onto a running experiment is an interesting idea... adding it to our long term list to explore.

Thanks for reporting!
