### ISSUE TITLE
Logging more than one file

### ISSUE THREAD

**Issue by cicobalico** [comet-ml/issue-tracking#125]
Hi everybody,
is it possible to log additional files to an experiment?
It would be useful for dependencies or config files (I know you could log them as params but I find it limiting since some of my configurations are functions, and they're not easy to log)

Thank you in advance

**Comment by ceceshao1** [comment]
@cicobalico - let us know if @dsblank's response helped you with logging multiple files.

**Comment by gidim** [comment]
Hi @cicobalico 
We're building an Asset Storage feature so you can easily store any kind of configuration, code or even your model weights on Comet. Should be ready by January.

**Comment by Nimrod007** [comment]
please see: https://www.comet.ml/docs/python-sdk/Experiment/#experimentlog_asset
