### ISSUE TITLE
Pycharm console output not getting logged in output tab

### ISSUE THREAD

**Issue by vermaMachineLearning** [comet-ml/issue-tracking#126]
Seems like running an experiment inside the pycharm console does not yield any logs in the output tab (screenshots attached). Note that here the file is actually been run inside the python console (as oppose to running from terminal command line). 

Would be great if there are any solutions or trick to resolve this issue for now.

![image](https://user-images.githubusercontent.com/19637167/47545041-1051dc00-d89f-11e8-9713-0bb7fadba241.png)

![image](https://user-images.githubusercontent.com/19637167/47545127-63c42a00-d89f-11e8-893b-7471760fafeb.png)

**Comment by Nimrod007** [comment]
Hi @vermaMachineLearning , thanks for reporting this. currently we dont support IPython source code logging. and no tricks to solve this issue at the moment. sorry about that

**Comment by ceceshao1** [comment]
Marking this as a feature request @vermaMachineLearning

**Comment by dsblank** [comment]
Update: we now support IPython and Jupyter source code logging, and are working on standard output logging as well. Stay tuned!

**Comment by dsblank** [comment]
This should appear in the next Python SDK release.
