### ISSUE TITLE
Incorrect sorting of multi-digit values

### ISSUE THREAD

**Issue by brennanNichyporuk** [comet-ml/issue-tracking#127]
<img width="93" alt="screen shot 2018-10-26 at 9 34 35 pm" src="https://user-images.githubusercontent.com/10503797/47598252-6f7b2380-d967-11e8-90e5-a81275453318.png">

**Comment by brennanNichyporuk** [comment]
<img width="90" alt="screen shot 2018-10-26 at 10 51 38 pm" src="https://user-images.githubusercontent.com/10503797/47598939-cb4aaa00-d971-11e8-9c91-fd9084738a0a.png">

**Comment by Nimrod007** [comment]
Hi @brennanNichyporuk - can you share a snippet of how this was reported ? and is this a metric / param / log other ?

**Comment by Nimrod007** [comment]
deployed. thanks for reporting
