### ISSUE TITLE
PyTorch end to end example doesn't work

### ISSUE THREAD

**Issue by LeeJZh** [comet-ml/issue-tracking#129]
https://www.comet.ml/docs/python-sdk/pytorch/

this example doesn't work.

**Comment by ceceshao1** [comment]
Hi @LeeJZh - thanks for reporting this. We'll investigate today and update the example need be.

**Comment by ceceshao1** [comment]
@LeeJZh - can you provide the error message you receive when you try to run this example?

**Comment by LeeJZh** [comment]
@ceceshao1 
`import torch
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms
from torch.autograd import Variable
from comet_ml import Experiment`
> SyntaxError: Please import comet before importing any torch modules

**Comment by ceceshao1** [comment]
Thanks @LeeJZh - I was able to reproduce the same error (just wanted to make sure we were solving for the same error). 

We'll be pushing out a fix today
