### ISSUE TITLE
Http proxy support

### ISSUE THREAD

**Issue by 7kbird** [comet-ml/issue-tracking#132]
I'm working behind a http proxy and got `COMET ERROR: Run will not be logged` after creating an `Experiment` instance. It's a local networking issue according to your [doc](https://www.comet.ml/docs/python-sdk/warnings-errors/).

But environment variable 'HTTP_PROXY' and 'HTTPS_PROXY' are already set and `requests` module works fine. So I dig into this and find out that network failed at `Experiment._initialize_streamer()` when call `self.ws_connection.wait_for_connection()`.

This is because the WebSocketApp do not use the proxy in env. Change `WebSocketConnection._loop` at `comet_ml/connection.py` into 
```python
    def _loop(self):
        # Pass the default ping_timeout to avoid issues with websocket-client
        # >= 0.50.0
        self.ws.run_forever(ping_timeout=10,
                            http_proxy_host='you_proxy_ip',
                            http_proxy_port='your_port')
        LOGGER.debug("Run forever has ended")
```
fix the problem. This is a dirty hack, I hope there will be a way to support proxy from  env-variable or config option.

- python: 3.6.6
- comet_ml: 1.0.37
- pytorch: 0.4.1
- OS: Win10 Pro x64

**Comment by nlynn12** [comment]
+1 This is still an issue @gidim, what's the status on this?

**Comment by dsblank** [comment]
Would an environment/config variable, something like: `export COMET_PROXY=your_proxy_ip:your_port` solve the issue?

**Comment by nlynn12** [comment]
Why add another environment variable? Why not just use the HTTP_PROXY, HTTPS_PROXY, etc.?

Venlig hilsen

Nicolai Anton Lynnerup

ErhvervsPhD Stipendiat
Mærsk Mc-Kinney Møller Instituttet, SDU
Konsulent, Teknologisk Institut
T 72 20 27 13
nicolai_lynnerup@hotmail.com
________________________________

**Comment by dsblank** [comment]
There is already a HTTP_PROXY environment variable? Is that just a well-known environment variable name?

**Comment by nlynn12** [comment]
Yes. It is commonly used for setting the proxy system wide. So they “just” need to read in those variables.

Venlig hilsen

Nicolai Anton Lynnerup

ErhvervsPhD Stipendiat
Mærsk Mc-Kinney Møller Instituttet, SDU
Konsulent, Teknologisk Institut
T 72 20 27 13
nicolai_lynnerup@hotmail.com
________________________________

**Comment by dsblank** [comment]
So the logic would be: check for HTTPS_PROXY; if defined use it. Check for HTTP_PROXY; if defined, use it. Otherwise don't use a proxy. Does that sound correct to you all?

**Comment by dsblank** [comment]
Or just use HTTP-PROXY? 

Is there ever a time when you would need to use HTTP-PROXY for one thing and something else for web sockets?

**Comment by dsblank** [comment]
Good news: comet_ml now supports proxies! It will use any HTTPS proxy setting that you have on your OS: https://www.comet.ml/docs/python-sdk/advanced/#http-proxy

Let us know how that works for you!
