### ISSUE TITLE
Experiment class throws git error - Submodules?

### ISSUE THREAD

**Issue by bw4sz** [comet-ml/issue-tracking#134]
I have a git repo that has a submodule that I created following  https://blog.github.com/2016-02-01-working-with-submodules/. The idea was to partition the code and the data in my ML project to make the code repo more lightweight.

When I open an Experiment class it throws

```
Using TensorFlow backend.
/Users/ben/miniconda3/envs/retinanet/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
COMET ERROR: Failed to log git metadata
```

and points at the submodule dir

https://cl.ly/577159c8f83a

test on comet version 1.0.30 and 1.0.37

**Comment by kdmcdrm** [comment]
I'm seeing the same issue but without a submodule.

**Comment by dsblank** [comment]
Can you upgrade comet_ml and try again?

**Comment by kdmcdrm** [comment]
I'm still seeing it on 1.0.49. I haven't dug in to see what part of the git patch process is failing.

**Comment by Lothiraldan** [comment]
@kdmcdrm Could you paste the output of `pip list`? Could you try to update the version of `comet-git-pure` with `pip install -U comet-git-pure`?

If that's still happens, the output of `git status` and the redacted outputs of `git diff` and `git diff --cached` would be very valuable to understand what is happening

**Comment by bw4sz** [comment]
I believe my original issue has been resolved.

For example this experiment has code attached, even though the repo has a submodule in the directory.

https://www.comet.ml/bw4sz/deeplidar/1bb919a651824e7bb967eaa43c3c6ced/code

I'm going to close, but others should reopen/separate issue if there are ongoing challenges.
