### ISSUE TITLE
Allow event purging when using ExistingExperiment

### ISSUE THREAD

**Issue by gidim** [comet-ml/issue-tracking#137]
Reported via Michael Petrochuk 

Hi There! Looking to switch to Comet.ml from Tensorboard. Unfortunately, Comet.ml does not support “Event Purging”. In long deep learning experiments (2 weeks), it’s common for the experiment to crash / restart from a checkpoint in the past.

Given that the checkpoint is behind the current step of the experiment, events after the checkpoint need to be purged.

Delete all the events from a time t forward, if I start an ExistingExperiment at the lower time t. 
Overriding wouldn’t work well because sometimes I skip steps!

Any timeline for this feature? Or am I missing something

**Comment by Nimrod007** [comment]
we have added a parameter to ExistingExperiment `step_copy=123` 
this will copy all the data for the ExistingExperiment until the given step and create a new experiment.

**Comment by PetrochukM** [comment]
Hi! I think this parameter is missing from the documentation by the way!

**Comment by dsblank** [comment]
Thanks, @PetrochukM ... noted, and will revise docs.
