### ISSUE TITLE
Support multiple files code tab.

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#139]
Hi There!

Love the idea of the code tab. It's not really useful for me at the moment though. Based on my crude understanding, the code tab does not support visualizing the differences between multiple files in a code base. 

This is important for me because my deep learning repository has many files and many critical ones. For example, my model is 5 - 6 files by its self.

**Comment by Nimrod007** [comment]
do you have any suggestion how to detect the files you expect to view ? (and not just show the entire repo)

**Comment by PetrochukM** [comment]
When comparing between two experiments, it's important for me the view the code differences between both experiments. 

When looking at a single experiment, I'd probably want to inspect the commit that ran that experiment. This can be done through Github, I suppose.

**Comment by Nimrod007** [comment]
we added a "Compare on github" button in the diff view:

![comet_ml___supercharging_machine_learning](https://user-images.githubusercontent.com/3535799/50496830-d61ccc00-0a00-11e9-9d21-d91aa6919bea.png)

**Comment by Vozf** [comment]
I

> we added a "Compare on github" button in the diff view:
> 
> ![comet_ml___supercharging_machine_learning](https://user-images.githubusercontent.com/3535799/50496830-d61ccc00-0a00-11e9-9d21-d91aa6919bea.png)

Can this be used for other git providers like gitlab or bitbucket? Or is it only for github?

**Comment by Nimrod007** [comment]
@Vozf  -  compare button currently works on GitHub only, Ill add bitbucket and GitLab to our roadmap
