### ISSUE TITLE
Earlier the stdout / stderr logging

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#140]
Hi There!

Small nitpick, it'd be nice if Comet.ml started capturing stdout / stderr before I instantiate an experiment and after I import the package. This would be nice so I don't have to figure out how to place the Experiment instantiation all the way at the beginning of my code before I've loaded my checkpoint, arguments, environment, etc that all have logging associated.

Thanks!

**Comment by dsblank** [comment]
I don't believe that logging information would be feasible before creating an experiment. Where would it go? In a live experiment, it is streamed to the cloud. In an offline experiment, it is sent to a file. We can't know until you create an experiment.

You could send the early log information to a file, and log the file as an asset at the end of the experiment. That should work in all situations. Might be worth a try.

**Comment by PetrochukM** [comment]
@dsblank Can you please reopen this issue? This is still a valid feature request.

I asked for logging to be captured as soon as `comet` is imported. This can be logged to a temporary file until an experiment object is created.

I have already implemented a workaround. I'd prefer not to have a work-around to save crucial logs from the experiment initialization.

**Comment by dsblank** [comment]
@PetrochukM Don't worry... your request is on our product feature request list. We're just closing the ones in this issue-tracker because it isn't as well integrated into our development process. I'll update this though when we have a fix. Thanks!
