### ISSUE TITLE
[Bug] Chart Lag and Chart tooltip

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#144]
Hey!

When using the UI, it's super laggy as you can see. Also, the number tooltip only shows me the value of one line. (I expect to see all the numbers or the value of the line I'm hovering over)

![screen recording 2018-11-20 at 1 47 51 pm mov](https://user-images.githubusercontent.com/7424737/48805062-36ff0900-eccb-11e8-82d7-2fff87aae10a.gif)

Thanks!

**Comment by Nimrod007** [comment]
fixed
