### ISSUE TITLE
Chart naming

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#145]
Hi There!

Looks like unlike the graphics tab the context is appended to the chart name. This is not a blocker but it does, for me, mess up my naming schema. 

**Current**
`dev_epoch/attention_norm`, `dev_infered/attention_norm`

**Expectation**
Context is added as a separate field similar to the graphics tab.
![image](https://user-images.githubusercontent.com/7424737/48805342-fa7fdd00-eccb-11e8-8740-c6a5bbec2175.png)

**Alternative Expectation**
More control of the context + metric naming.
`dev/epoch/attention_norm`, `dev/inferred/attention_norm`

Thanks!

**Comment by Nimrod007** [comment]
Hey @PetrochukM - would allowing you to change the chart name solve this issue ? or you prefer the automatic chart name generation without the context as prefix on metric name ?

**Comment by PetrochukM** [comment]
Hi There!

Allowing me to change the chart name through the Python API would work or automatic. I'd like to avoid manually correcting all my experiment chart names and correct future experiments as well. 

Thanks!
