### ISSUE TITLE
HTML Tab Overwrite

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#148]
Hi There!

Love the HTML tab because it gives me a lot of control for specific UI components I need. Unfortunately, the HTML tab always appends HTML. It'd be nice to overwrite the HTML. 

Overwriting the HTML would allow me to do super creative things. For example, your current graphics tab does not have sorting or sampling features. I could implement those myself through your HTML tab and be content.

An efficient implementation of an HTML overwrite would be only to record differences between the old HTML and the new HTML.

Thanks!

**Comment by Nimrod007** [comment]
since version `comet-ml 1.0.39` you can now 
```
    def log_html(self, html, clear=False):
```
