### ISSUE TITLE
[UI] The color scheme for this graph is inaccessible

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#150]
Hey There!

It's difficult for me to tell apart these faded colors:
![image](https://user-images.githubusercontent.com/7424737/48806384-fbfed480-ecce-11e8-8b3c-e6ced7ccedf1.png)

It's possible to tell them apart but not the easiest in the world. The green and blue in the center is very difficult.

There are maximum contrast color palettes to ensure it's easy to tell apart colors. Programatically, you can use the CIELAB color space to generate contrasting colors.

Thanks!

**Comment by dsblank** [comment]
We have rewritten many parts of the colorization of graphs.

Please reopen and describe if you have any questions or issues. Thanks for reporting!
