### ISSUE TITLE
Legend does not show everything

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#151]
Hi There!

Looks like the legend for my lines is not fully displaying:
![image](https://user-images.githubusercontent.com/7424737/48806625-bdb5e500-eccf-11e8-91f2-2e30a1c4a34d.png)

There are 4 lines, yet I only see 2 items in the legend.

NOTE: 4 items fix in the expanded view of the charts, I'm using that meanwhile.

Thanks!

**Comment by Nimrod007** [comment]
fixed
