### ISSUE TITLE
GPU Utilization Screen

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#152]
Hi There!

The GPU utilization graph is not useful. It'd be nice to smooth it out a bit. It's not clear if the graph is denser around 60%, 80% or 100%.
![image](https://user-images.githubusercontent.com/7424737/48806670-f3f36480-eccf-11e8-85f3-0d0dbe6cbbde.png)

Thanks!

**Comment by dsblank** [comment]
I believe that this is fixed. Please re-open if you have any issues. Thanks for reporting!
