### ISSUE TITLE
System Metrics Line Toggle

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#153]
Hi There!

After turning off a line in the system metrics, it comes back. Here is a gif --
![screen recording 2018-11-20 at 2 26 09 pm mov](https://user-images.githubusercontent.com/7424737/48806850-8c89e480-ecd0-11e8-857e-63b943216237.gif)

Other things:
- I don't press the key board at all expect to start and stop the screen recording.
- This is for a running experiment.

Thanks!

**Comment by Nimrod007** [comment]
Hi @PetrochukM - we've made a change and wanted to make sure it solves your issue, can you check again when you run your next experiment ? 
thanks

**Comment by PetrochukM** [comment]
It's still a bit weird:
![screen recording 2018-12-27 at 8 06 26 pm mov](https://user-images.githubusercontent.com/7424737/50502372-a6c38a80-0a13-11e9-80ab-1ef67ce1ddfa.gif)

**Comment by dsblank** [comment]
I believe that all issue related to this problem have been addressed. Please reopen and describe if you have any questions or issues. Thanks for reporting!
