### ISSUE TITLE
Unable to move experiments to a different project

### ISSUE THREAD

**Issue by eksponente** [comet-ml/issue-tracking#158]
Hi,

First of all, just wanted to say that I am really enjoying using your platform! It's definitely been the most hassle-free, easy to set up experiment management framework I've come across, and the dashboard is amazing too! Great tool all around.

I've come across a minor bug though. When I try to move an experiment to a different project (using the Move button at the top of the experiment list), I get the following error message:

"An error occurred while moving your experiment(s) to the project."

Please let me know if you need more information from me regarding the bug.

Regards,
Rugile

**Comment by Nimrod007** [comment]
fixed.
