### ISSUE TITLE
Only able to log up to 100 images

### ISSUE THREAD

**Issue by eksponente** [comet-ml/issue-tracking#159]
I am only able to log up to a 100 images per experiment. The Python client does not raise any errors, just no more images appear after 100 images have been logged. 
If this is due to storage constraints, would it be possible to make an option to remove old images in favour of storing new ones?

**Comment by Nimrod007** [comment]
Hi @eksponente - we dont limit for only 100 images, we have many users uploading many more. 
are you using `log_figure` or `log_image` ?

**Comment by eksponente** [comment]
I am using `log_image`. The images may be uploading successfully, but only a 100 are displayed on the website (under the `Graphics` tab).

**Comment by Nimrod007** [comment]
we've created a new `Graphics` tab. should solve this issue.
