### ISSUE TITLE
[API] log_asset parameters and return value

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#160]
Hi There!

For `log_asset`, it'd be nice if you could pass an open file to the method. For me, files created during training are in memory, not on disk. It'd be nice to be able to pass an [in-memory file object](https://stackoverflow.com/questions/44672524/how-to-create-in-memory-file-object) to `log_asset` instead of a file_path.

Similarly, for compatibility with `log_html` it'd be nice if `log_asset` passed back a URL link to the asset. The workflow would be to `log_asset` then update the HTML with the asset.

Thanks!

**Comment by Nimrod007** [comment]
for file-like upload update sdk to `1.0.41`.
file links is still in progress (keeping this open until we update around the url for the uploaded file)

**Comment by Nimrod007** [comment]
when uploading and asset or image you get back the web url and rest api url.
check in version: `1.0.43`
