### ISSUE TITLE
[UI] Highlight differences between hyperparameters

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#162]
Scrolling through a 100 hyperparameters, it's hard to spot the differences:
![screen recording 2018-11-23 at 8 02 29 pm mov](https://user-images.githubusercontent.com/7424737/48964436-e94cff80-ef5b-11e8-82f9-05406e080d59.gif)

Ideas:
- Move the different hyperparameters to the top
- Use green / red to highlight added / removed hyperparameters similar to Github

**Comment by Nimrod007** [comment]
done
