### ISSUE TITLE
[Bug] Outliers loses data

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#163]
With outliers show:
![image](https://user-images.githubusercontent.com/7424737/48971472-066ee600-efcf-11e8-8df4-d01031c27023.png)

With outliers ignore:
![image](https://user-images.githubusercontent.com/7424737/48971476-15559880-efcf-11e8-9008-0fcdb379eada.png)

In outliers ignore, I'd expect to see a blue point between 400 to 500 above the green line and below 1.0 on the y-axis.

I think this relates to: https://github.com/comet-ml/issue-tracking/issues/141

**Comment by Nimrod007** [comment]
fixed
