### ISSUE TITLE
[Feature Request] Step column

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#164]
Hi There!

Looks like with customizing columns, I cannot pull up a step metric. This would a nice addition similar to duration.

NOTE: For right now, I use ``train_curr_epoch`` as a substitute.

Thanks,
Michael

**Comment by Nimrod007** [comment]
Hey @PetrochukM , you can use the sdk to report 
```
exp.log_metric("current_step", step)
```
after you do this it will be available on the customize column and in the query builder.

**Comment by Nimrod007** [comment]
please update to `1.0.41` and add `curr_step` in customize columns
