### ISSUE TITLE
[Feature Request] Deleting ExistingExperiment Run

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#165]
Hi There!

Deleting experiment is super useful for clearing up clutter, unfortunately, the same cannot be done with ExistingExperiment. Today, I'd accidentally loaded up a checkpoint with a bug that updated an existing experiment. It'd be nice to be able to delete that.

My graphs are super messed up now :(
![image](https://user-images.githubusercontent.com/7424737/48976771-e3c9e500-f041-11e8-937a-9827f3eabf4d.png)

In Tensorboard, event purging and deleting run files would handle this!

Thanks!

**Comment by skim2257** [comment]
bump, would love this feature as well.
