### ISSUE TITLE
Remove "File name" and "Experiment Key" column

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#166]
Hi There!

It'd be nice to be able to remove the "File name" and "Experiment Key" column from the list:
![image](https://user-images.githubusercontent.com/7424737/48977025-eaa72680-f046-11e8-98e9-7567b2e9dafe.png)

Those columns are not very useful when comparing or running experiments, for me. 

Thanks,
Michael

**Comment by Nimrod007** [comment]
File name can be removed. experiment key is currently the only link to the single view. we are keeping it for now.
