### ISSUE TITLE
[Feature Request] Customisable x-axis in Experiment page

### ISSUE THREAD

**Issue by system123** [comet-ml/issue-tracking#169]
I often use a LR finding algorithm to determine the best learning rate for my models but in order to do this I need to be able to plot learning rate vs loss on a Log scale.

Allowing the user to select another logged metric as the x-axis, and to set the scale of the x-axis to logarithmic would enable this. In order to easy implementation, it could be assumed that the two metrics need to be namespaced in the same namespace and should contain the same number of data points.

**Comment by KaleabTessera** [comment]
Any progress on this @gidim ?

**Comment by gidim** [comment]
Yep that's already in production actually. See attached screenshot

Closing this.
<img width="996" alt="Screen Shot 2019-04-05 at 2 30 04 PM" src="https://user-images.githubusercontent.com/5440856/55648839-606a8e00-57af-11e9-959b-a7669f819906.png">

**Comment by gidim** [comment]
Got it.. let me update the title and re-poen.
We're consolidating both chart builders so this should be finished soon.

**Comment by Damowerko** [comment]
> We're consolidating both chart builders so this should be finished soon.
Will we be able to set log scale in the experiment view?
