### ISSUE TITLE
problem with uploading graph on windows

### ISSUE THREAD

**Issue by kingarthurie** [comet-ml/issue-tracking#17]
Experiment is uploaded twice, but graphics not at all.

The exception I'm getting is:

> RuntimeError: 
>         An attempt has been made to start a new process before the
>         current process has finished its bootstrapping phase.
> 
>         This probably means that you are not using fork to start your
>         child processes and you have forgotten to use the proper idiom
>         in the main module:
> 
>             if __name__ == '__main__':
>                 freeze_support()
>                 ...
> 
>         The "freeze_support()" line can be omitted if the program
>         is not going to be frozen to produce an executable.

OS - windows 10
python 3.5
IDE - pyCharm, .py file, not jupyter NB

code:

> import matplotlib as mpl
> mpl.use('TkAgg')
> import matplotlib.pyplot as plt
> import numpy as np
> 
> t = np.arange(0.0, 2.0, 0.01)
> s = 1 + np.sin(2*np.pi*t)
> plt.plot(t, s)
> 
> plt.xlabel('time (s)')
> plt.ylabel('voltage (mV)')
> plt.title('About as simple as it gets, folks')
> plt.grid(True)
> 
> experiment.log_figure(figure=plt)

output:

> Experiment is live on comet.ml https://www.comet.ml/danilo/matplotlib/ea2bf8c69f4b40ada4158c8869961bc1
> 
> LINES [<matplotlib.lines.Line2D object at 0x0000016DB2361B00>]
> 
> 
> 
> Experiment is live on comet.ml https://www.comet.ml/danilo/matplotlib/fa4b15da2dcc48a7878cf165be1bdead
> 
> LINES [<matplotlib.lines.Line2D object at 0x000002087ED8E9E8>]
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 106, in spawn_main
>     exitcode = _main(fd)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 115, in _main
>     prepare(preparation_data)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 226, in prepare
>     _fixup_main_from_path(data['init_main_from_path'])
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
>     run_name="__mp_main__")
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Danilo\PycharmProjects\Kaggle\test.py", line 18, in <module>
>     experiment.log_figure(figure=plt)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\site-packages\comet_ml\__init__.py", line 530, in log_figure
>     url_params)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\site-packages\comet_ml\file_uploader.py", line 210, in upload_file_process
>     p.start()
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 105, in start
>     self._popen = self._Popen(self)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 212, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 313, in _Popen
>     return Popen(process_obj)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
>     prep_data = spawn.get_preparation_data(process_obj._name)
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
>     _check_not_importing_main()
>   File "C:\Users\Danilo\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
>     is not going to be frozen to produce an executable.''')
> RuntimeError: 
>         An attempt has been made to start a new process before the
>         current process has finished its bootstrapping phase.
> 
>         This probably means that you are not using fork to start your
>         child processes and you have forgotten to use the proper idiom
>         in the main module:
> 
>             if __name__ == '__main__':
>                 freeze_support()
>                 ...
> 
>         The "freeze_support()" line can be omitted if the program
>         is not going to be frozen to produce an executable.
> 
> Uploading stats to Comet before program termination (may take several seconds)
> 
> Experiment is live on comet.ml: https://www.comet.ml/danilo/matplotlib/fa4b15da2dcc48a7878cf165be1bdead
> close status: 26479
> 
> Uploading stats to Comet before program termination (may take several seconds)
> 
> Experiment is live on comet.ml: https://www.comet.ml/danilo/matplotlib/ea2bf8c69f4b40ada4158c8869961bc1
> close status: 26479
> 
> Process finished with exit code 0

**Comment by gidim** [comment]
This is due to the way the subprocess module is implemented in windows. There's a really easy fix on your end. Just add in your code `if __name__ == ''__main__"`. So your script should look like this:

import matplotlib as mpl
mpl.use('TkAgg')
import matplotlib.pyplot as plt
import numpy as np
from comet_ml import Experiment

```
if __name__ == '__main__':
    experiment = Experiment(api_key="your_key", project_name="matplotlib")

    t = np.arange(0.0, 2.0, 0.01)
    s = 1 + np.sin(2*np.pi*t)
    plt.plot(t, s)

    plt.xlabel('time (s)')
    plt.ylabel('voltage (mV)')
    plt.title('About as simple as it gets, folks')
    plt.grid(True)

    experiment.log_figure(figure=plt)
```
