### ISSUE TITLE
[Feature Request] Status Symbol on Program Hanging

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#170]
Hi There!

If a script hangs for a long time and does not send events to comet.ml, the status symbol does not change. It'd be nice to have some way of verifying if a script is still running or it's just hanging.

Thanks!

**Comment by Nimrod007** [comment]
Hi @PetrochukM , we can have a "last message received" indicator for experiment (timestamp) will that solve the issue ?

**Comment by PetrochukM** [comment]
Yup! That's what I got working so far!

**Comment by PetrochukM** [comment]
@Nimrod007 Can you add basic anomaly detection for this.

The idea is to track the average and standard deviation for the time between events. If the time is larger than the average + standard deviation * 3, then you'd change the status symbol to a warning.

Thanks!

**Comment by Nimrod007** [comment]
we added a `last_message_time` to the table. currently were not adding basic anomaly detection

![nimrod007_tf-bug__fsd](https://user-images.githubusercontent.com/3535799/50496934-a02c1780-0a01-11e9-9429-e32320dd8c46.png)

**Comment by PetrochukM** [comment]
Okay! Thank you!
