### ISSUE TITLE
[Feature Request] Support copy paste for notes

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#171]
Hi There!

Can you please support copy pasting images into the notes box? This is helpful for documenting experimental results.

Thanks!

**Comment by Nimrod007** [comment]
for a quick fix you can copy the url from the images in the image tab (top right corner) 

and paste it into your notes with markdown like this:
```
![](https://s3.amazonaws.com/comet.ml/PBfMrzvfrgh2fKvvPUujmKRxV.)
```
we can make this much easier for user.  will add it to our todo list

**Comment by Nimrod007** [comment]
we know support copy / paste into notes.
