### ISSUE TITLE
[feature request] add a debug/tuning mode to experiment 

### ISSUE THREAD

**Issue by LeeJZh** [comet-ml/issue-tracking#173]
by setting experiment as "debugging", information would be sent to the project of workspace; i believe it will helps better organizing experiments when there are some bugs in the code. thanks

**Comment by gidim** [comment]
Hi @LeeJZh 
You can add a tag called "debug" and then easily filter/find those on the UI.
See docs - https://www.comet.ml/docs/python-sdk/Experiment/#experimentadd_tag
