### ISSUE TITLE
log code

### ISSUE THREAD

**Issue by AntoinePrv** [comet-ml/issue-tracking#175]
Hello,

Comet_ml logs the code logs the code of the file run. If that file is a simple runner it doesn't contains much information. It would be convenient if we could rather run `Expermient.log_code` to select a file/module we wish to log.

**Comment by gidim** [comment]
Hi @AntoinePrv 
you can achieve this by calling `experiment.set_code("string with source code")`
See docs: https://www.comet.ml/docs/python-sdk/Experiment/#experimentset_code
