### ISSUE TITLE
[Feature Request] Highlighting different hyperparamaters in the "diff" mode

### ISSUE THREAD

**Issue by shagunsodhani** [comet-ml/issue-tracking#176]
When we take the diff of two experiments and look at the hyperparameter tab, it is difficult to know which hyperparameters are different. Can we add support for highlighting the different parameters eg change the background color of the cell to red or maybe just put them first in the ordering?

**Comment by ceceshao1** [comment]
Marking as a similar request to #162

**Comment by Nimrod007** [comment]
done.
