### ISSUE TITLE
[Feature Request] Tags fill up space

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#177]
Hi There!

When the column size expands, can it be that the tags fill up the extra space?
![image](https://user-images.githubusercontent.com/7424737/49903270-7d9fd900-fe1b-11e8-99e3-f9286eb2359b.png)

Attached a screenshot with the tags column and a bunch of white space on the right.

Thanks!

**Comment by gidim** [comment]
Yes! Good point.
In the works

**Comment by PetrochukM** [comment]
Thank you!

**Comment by Nimrod007** [comment]
deployed.
