### ISSUE TITLE
Support for conda installation?

### ISSUE THREAD

**Issue by sahilgandhi94** [comet-ml/issue-tracking#18]

**Comment by gidim** [comment]
Hi, Thanks for opening an issue.
Given that you can install pip packages in a conda environment this is probably low priority.

"While the packages won't be managed by the Conda package manager, they will still be managed by the Anaconda environment. It will download the correct version of the package for the active Python install and update it correctly using the pip package manager."

**Comment by Haydnspass** [comment]
@gidim That is true however the source you cited (https://www.anaconda.com/using-pip-in-a-conda-environment) states a couple of things which one needs to be aware of.

> Recreate the environment if changes are needed
> 
> once pip has been used conda will be unaware of the changes
> to install additional conda packages it is best to recreate the environment

I think conda packages can be created from existing pip things, so it would be nice if this would be available :)

**Comment by gidim** [comment]
Thanks for the additional info @Haydnspass 
We'll take a deeper look

**Comment by cao13jf** [comment]
Guys, could `conda skeleton` be useful for you? It can build a package for a module that is already avaliable from PyPi. Please check this [link](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html).

**Comment by dsblank** [comment]
Thanks for the link @cao13jf  ! That was quite useful. We haven't committed to this yet, but please try this test package to see if it works for you:

```
conda install -c dsblank comet_ml
```

**Comment by dsblank** [comment]
We are tentatively building comet_ml conda packages.

https://anaconda.org/comet_ml/comet_ml

Please let us know if you have any further issues or questions. Thanks for the hints and reporting!

**Comment by ttpro1995** [comment]
cannot install via conda 
```
$ conda install -c comet_ml comet_ml 
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:


  - comet_ml -> netifaces[version='>=0.10.7']

Current channels:

  - https://conda.anaconda.org/comet_ml/linux-64
  - https://conda.anaconda.org/comet_ml/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

**Comment by XXZhou25** [comment]
> @ttpro1995 You should add conda-forge to your channel list:
> 
> ```
> conda install -c comet_ml -c conda-forge comet_ml 
> ```

worked perfectly. Thanx!
