### ISSUE TITLE
[UI] Color the experiments rows same as the graph colors

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#180]
Hi There!

For project visualizations, could you add the graph colors to the experiment table? Either color the entire row or add a column with the experiment color or change the link color.

This would be helpful for quickly skimming through results.

Thanks!

**Comment by PetrochukM** [comment]
Double checking on this, it'd be useful to me!

There is some work required to figure out how a line in the graph maps to an experiment in the table.

**Comment by dsblank** [comment]
I think we have implemented exactly this (plus the ability to change the color for the experiment if you don't like it).

Please reopen and describe if you have any questions or issues. Thanks for reporting!
