### ISSUE TITLE
[UI] System usage with 4 GPUs

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#182]
Hi There!

With 4 GPUs + contexts, the gpu utilization graph gets unreadable:
![image](https://user-images.githubusercontent.com/7424737/50056388-59404700-0110-11e9-88d6-9d5e1bdfd4f9.png)

Thanks!

**Comment by Nimrod007** [comment]
thanks, were working on this. will update once deployed

**Comment by Nimrod007** [comment]
please update sdk to `1.0.41`
