### ISSUE TITLE
[UI] Update delete experiment warning

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#184]
![image](https://user-images.githubusercontent.com/7424737/50377306-d451a380-05cf-11e9-9d3d-e5e6f70cf473.png)

Would it be possible to have the number of experiments to be deleted included in the warning?

**Comment by Nimrod007** [comment]
done

**Comment by bnbarak** [comment]
@PetrochukM, 
We just deployed a new version. Please refresh your browser to see the feature. 
Happy New Year
