### ISSUE TITLE
[Bug] Remove throttling icon after experiment finishes

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#188]
![image](https://user-images.githubusercontent.com/7424737/50740820-6ef1db00-11a9-11e9-8502-b90d559e26c7.png)

The throttling icon is still around after the experiment finishes.

**Comment by PetrochukM** [comment]
Question, does the throttle warning go away if I stop sending more than 6000 requests a minute?

**Comment by Nimrod007** [comment]
I think its worth keeping since it indicates that this experiment might be missing data

the icon does not go away, if the experiment was throttled once the icon will show.

**Comment by PetrochukM** [comment]
@Nimrod007 Okay! That makes sense. For my use case, how do I know if I have fixed the problem (throttling)? Say, I change the parameters in a long-running experiment to log less, how do I know if I fixed my throttling issues?

**Comment by Nimrod007** [comment]
@PetrochukM , not sure i fully understand the question. if you start a new experiment with the changes and the throttling button isn't there the issue is fixed. 

having said that throttling isn't only a code issue. you can have the same code running in different parallelism levels and hit the limit. the amount is 6K per minute for a single user (which includes all messages sent from the training code to comet backend (metrics, params, log_other, stdout)

**Comment by PetrochukM** [comment]
So the use case I am considering is long-running experiments. During an experiment that has been running for 3 days, I notice that I am now getting throttled. Without restarting the experiment at step 1, I'd like to know how to resolve the issue and get confirmation that it has been resolved.

**Comment by Nimrod007** [comment]
sure, we can add an api call so you can check is experiment X currently throttled, will that solve the issue ?

**Comment by PetrochukM** [comment]
Yeah, having a field in the column list will help! Thank you!

I still believe the icons are still a tad bit confusing. It's odd to have a throttling icon if the experiment is no longer being throttled. A more appropriate icon is a "might be missing data" icon.

**Comment by Nimrod007** [comment]
sounds right. will add this to the pipeline

**Comment by dsblank** [comment]
I believe that all issue related to this problem have been addressed. Please reopen and describe if you have any questions or issues. Thanks for reporting!
