### ISSUE TITLE
Is there a limit of experiments that can be performed (for each workspace)?

### ISSUE THREAD

**Issue by nbro** [comet-ml/issue-tracking#189]
I created [this public workspace](https://www.comet.ml/nbro/comparing-optimizers), but, even though my script is still running, apparently the experiments are not being added to the web interface. So, is there a limit to how many experiments can be performed and saved in a workspace?

According to the web interface, I have created 19 experiments. However, according to some files created during my experiments, I should have already created 20 experiments, and, now, I am on the 21st. 

I have some error messages from Comet.ml on the terminal (for several experiments). The last one is:

```
COMET ERROR: Failed to report experiment status
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/nbro/comparing-optimizers/2c22e9e5871a40219d742a5f392b8ddd

COMET ERROR: Run will not be logged
```

But if I go to https://www.comet.ml/nbro/comparing-optimizers/2c22e9e5871a40219d742a5f392b8ddd, the experiment exists. So, what's going on?

I also have the error (before a previous experiment):

```
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/nbro/comparing-optimizers/963749385d2a40cdbc5313e17cab11e2

COMET ERROR: Failed to setup the std logger
COMET WARNING: Failed to log ip
COMET ERROR: File could not be uploaded
COMET ERROR: Failed to report experiment status
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/nbro/comparing-optimizers/2c22e9e5871a40219d742a5f392b8ddd
```

Note that, in this error message, the last link is the same as the previous one, i.e., comet.ml https://www.comet.ml/nbro/comparing-optimizers/2c22e9e5871a40219d742a5f392b8ddd. But there is also the link: https://www.comet.ml/nbro/comparing-optimizers/963749385d2a40cdbc5313e17cab11e2. What's going on?

Even before

```
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/nbro/comparing-optimizers/b4ac4a7ab03d4adca77affe02c68860b

COMET ERROR: Failed to setup the std logger
COMET ERROR: File could not be uploaded
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/nbro/comparing-optimizers/963749385d2a40cdbc5313e17cab11e2
```

Even before, I have

```
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/nbro/comparing-optimizers/a88441680f324121b603484fc6a24127

COMET ERROR: File could not be uploaded
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/nbro/comparing-optimizers/b4ac4a7ab03d4adca77affe02c68860b
```

Before this last error message, I also have many other error messages of the form `COMET ERROR: File could not be uploaded`.

What's going on?

I would like to note that during the execution of the script (which is still running), my Mac sometimes slept. I am not sure if that disconnects the the Mac from the Wi-Fi network, but that could have been the problem. How does Comet.ml deal with interruptions of the internet connection?

[Here](https://github.com/nbro/comparative-study-between-optimizers/blob/master/main.py) you have the script I am currently executing. Anyway, you can retrieve it from the web interface. 

As you can see from the script, I need to perform multiple experiments, which are very similar to each other, but only differ in certain hyper-parameters. I need to make sure that I will have kept track of all them. I can't wait other 10 hours to obtain the results. Also, I can't use computational resources like this.

**Comment by Nimrod007** [comment]
there is no limit for how many experiments can be in one workspace or project.
this error looks like a networking issue. 
```
COMET ERROR: Run will not be logged
```
indicates that the run will not show on comet website

if you are using an unstable network or want to work offline you can use the offline experiment option. (currently in beta)

**Comment by Nimrod007** [comment]
to get further information about this error you can turn on debug with:
```
import os
os.environ['COMET_LOGGING_FILE'] = '/tmp/comet.log'
os.environ['COMET_LOGGING_FILE_LEVEL'] = 'DEBUG'
from comet_ml import Experiment
```
