### ISSUE TITLE
comet.ml error: failed to report experiment status

### ISSUE THREAD

**Issue by paraschas** [comet-ml/issue-tracking#19]
While running my not too complex Keras model experiment, I get the following error:
```
comet.ml error: failed to report experiment status
```

After the exceptions:
```
socket.timeout: The read operation timed out

[...]

urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.comet.ml', port=443): Read timed out. (read timeout=10)

[...]

requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.comet.ml', port=443): Read timed out. (read timeout=10)
```

It subsequently uploads data to Comet.ml, and I can see the experiment in the Projects page. I'm not sure of what information, if any, is missing.

Is it a temporary service issue, a mis-configuration of my setup, or a bug in the comet_ml module?

**Comment by gidim** [comment]
Hi @paraschas - we're looking into this.
Is your network stable?

**Comment by paraschas** [comment]
Yes, I checked my Internet connection when I run the experiment and it seemed to be working without issues.

The experiment eventually managed to finish without error. I'll send more information if happens again, but my best guess is that the service was under load.

Thanks for the fast reply and what seems to be a great service.

(You can close this issue if it hadn't occurred to anyone else.)

**Comment by Nimrod007** [comment]
since im not detecting this on our monitoring closing for now.
please re-open if problem happens again.

**Comment by zc-alexfan** [comment]
Hello, I am having the same issue. Did you find the problem?

**Comment by dsblank** [comment]
@zc-alexfan This is probably a different issue, since so much has changed in the last 2 years. Please send details (log file, environment, experiment link, etc) to support@comet.ml and we can debug. Thanks!
