### ISSUE TITLE
Experiment logs intermediate model results

### ISSUE THREAD

**Issue by JudoWill** [comet-ml/issue-tracking#190]
I have a keras model that includes a model used for preprocessing data. This model is fixed and requires no training because I train it separately. The full model trains properly but when I run it without comet-ml but I get strange behavior when I add the experiment logging.

```
def build_preprocessing():
  inp = Input((1000,))
  # more stuff
  out = Dense(50)(inp)
  return Model(inp, out)

def build_model():
  inp = Input((1000,))
  pre_model = build_preprocessing()
  preprocessed = pre_model(inp)
  # more stuff
  out = Dense(1)(preprocessed)
  return Model(inp, out)

experiment = Experiment(api_key="...")
mdl = build_model()
mdl.fit(X,y)
experiment.end()
```

When I run this code my output is filled with:
`COMET WARNING: Cannot safely convert array([[[1.4244142, 1.4244142, 1.4244142, ..., 1.4244142, ....
`

It looks like these are the outputs of my preprocessing model that it is trying to log. Is there a way to specify which model the experiment logs results from?

I've also tried putting the model `in-line` like so:
```
def build_model_inline():

  pre_model = build_preprocessing()
  preprocessed = pre_model.output
  # more stuff
  out = Dense(1)(preprocessed)
  return Model(pre_model.input, out)
```
Thinking that perhaps the auto-detector wouldn't pick up the output of the preprocessing model. But that didn't work either.

I could just do a work-around to turn off the warning; but that seems like less-than-ideal solution.

Any ideas?

**Comment by dsblank** [comment]
I believe that if you create the Experiment *after* you build your model, you should be fine.

Please reopen and describe if you have any questions or issues. Thanks for reporting!
