### ISSUE TITLE
Download data

### ISSUE THREAD

**Issue by AntoinePrv** [comet-ml/issue-tracking#191]
How can I download data from comet.ml?
For instance, I would like to download the data from the charts section in raw (numerical) form. Something like the coordinates of all points on the curve.

The closest I can find is SVG export.
This is necessary when I need to post-process runs, make visual adaptations, etc.

Thank you

**Comment by AntoinePrv** [comment]
OK, I figure this is possible through the [REST API](https://www.comet.ml/docs/python-sdk/API/).

**Comment by ceceshao1** [comment]
Hi @AntoinePrv - apologies for the late response (see you've already closed the issue). Indeed you can use the REST API to export your data. [The example in our documentation](https://www.comet.ml/docs/python-sdk/Comet-REST-API/) if that's helpful.
