### ISSUE TITLE
[Bug] Column is not being sorted correctly

### ISSUE THREAD

**Issue by nbro** [comet-ml/issue-tracking#193]
In this project, https://www.comet.ml/nbro/optimizers-comparison, when I click on the column "Learning Rate", I expect to see the entries sorted according to the learning rate, but this is not happening correctly: I first see the entries with learning rate 0.0001 coming before the entries with learning rate 0.01, which come before the entries with learning 0.001. This is weird because other columns which contain float-point numbers (e.g. Test Accuracy) are apparently sorted correctly.

**Comment by nbro** [comment]
@Nimrod007 Why was this closed? Apparently, the problem still persists.

**Comment by Nimrod007** [comment]
thanks @nbro - will update once resolve

**Comment by Nimrod007** [comment]
fixed for log_other and paramater
