### ISSUE TITLE
Parallel coordinates not showing up lines

### ISSUE THREAD

**Issue by vermaMachineLearning** [comet-ml/issue-tracking#194]
Seems like parallel coordinates chart is not working properly. No lines are showing in the chart as shown 
below.

![image](https://user-images.githubusercontent.com/19637167/51125690-ccf47300-17e6-11e9-8713-8151c710c621.png)

**Comment by ceceshao1** [comment]
Thanks for reporting this @vermaMachineLearning. We're investigating now.

Can you share your project's link? Feel free to message directly in [Slack ](https://join.slack.com/t/cometml/shared_invite/enQtMzM0OTMwNTQ0Mjc5LTM4ZDViODkyYTlmMTVlNWY0NzFjNGQ5Y2Q1Y2EwMjQ5MzQ4YmI2YjhmZTY3YmYxYTYxYTNkYzM4NjgxZmJjMDI)

**Comment by vermaMachineLearning** [comment]
Awesome. Working fine now!
