### ISSUE TITLE
REST API throwing 504 Server Error: Gateway Time-out

### ISSUE THREAD

**Issue by vermaMachineLearning** [comet-ml/issue-tracking#195]
I am having trouble retrieving experiments from one of my project (contains around 2600 experiments). Code Snippet is shown. Although the same code is working for another project (contains 130 experiments). Let me know if you need any other piece of information.

Code Snippet:

import comet_ml
from config.utils_comet import API_KEY, REST_API_KEY
comet_api = comet_ml.API(api_key=API_KEY, rest_api_key=REST_API_KEY)
project = comet_api.get(project='MY_PROJECT', workspace="MY_WORKSPACE")

  File "/home/ubuntu/anaconda3/envs/env_py36/lib/python3.6/site-packages/comet_ml/api.py", line 665, in get_request
    response.raise_for_status()
  File "/home/ubuntu/anaconda3/envs/env_py36/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://www.comet.ml/api/rest/v1/experiments?projectId=31dbb270c0544b0487f93fb6df0b886f

**Comment by Nimrod007** [comment]
HI @vermaMachineLearning, working on a fix for this. thanks for reporting

**Comment by Nimrod007** [comment]
fixed.
