### ISSUE TITLE
What hyperparameter optimizer is used?

### ISSUE THREAD

**Issue by sotte** [comet-ml/issue-tracking#196]
I was wondering what kind of optimizer is used for optimizing the hyperparameters?

SMAC, Bayesian optimization, Bandits, whatnot?

The [docs](https://www.comet.ml/docs/python-sdk/Optimizer/) are a bit light on the details.

**Comment by gidim** [comment]
Hi @sotte 
The current public implementation is based on SMAC. We're actively working on adding more backends though.

**Comment by sotte** [comment]
Great, thanks!

I've had huge success with hyperband.
You're probably aware of it, but I've heard good things about BOHB:
- https://arxiv.org/abs/1807.01774
- https://github.com/automl/HpBandSter

**Comment by gidim** [comment]
Thanks @sotte we'll take a look!
