### ISSUE TITLE
DOCS: The example for an ordinal parameter is a categorical parameter

### ISSUE THREAD

**Issue by sotte** [comet-ml/issue-tracking#197]
In the docs, the example for an ordinal parameter is a categorical parameter:
```
batch_size categorical {16,32,64,128} [32]
```
Should be
```
batch_size ordinal [16,32,64,128] [32]
```

Here: https://www.comet.ml/docs/python-sdk/pcs-file/#ordinal-parameters

**Comment by dsblank** [comment]
Thanks! Reworking that part of the manual just now. If you see anything else, let us know.

**Comment by sotte** [comment]
Thanks!

Just a few comments real quick:
- `Suggestion.params` is not documented but it's quite handy if you normally pass your params as dict.
- That being said: the type of the parameters of the `params` dict is not the one you specified in the PCS file.

**Comment by dsblank** [comment]
Good! Thanks!

**Comment by dsblank** [comment]
Where do you see the `Args` keyword error?

**Comment by sotte** [comment]
I guess it's just a formatting thing:
https://www.comet.ml/docs/python-sdk/Optimizer/

`Args:` normally is on a sep. line like here:
https://www.comet.ml/docs/python-sdk/Experiment/#experimentdisplay

**Comment by dsblank** [comment]
Got it; thanks! Will be fixed in the next release of our new documentation.

**Comment by sotte** [comment]
Great, thanks! :1st_place_medal:

**Comment by dsblank** [comment]
I believe that all issue related to this problem have been addressed. Please reopen and describe if you have any questions or issues. Thanks for reporting!
