### ISSUE TITLE
[Feature Request] Show params when hovering over bar plot

### ISSUE THREAD

**Issue by sotte** [comet-ml/issue-tracking#199]
The bar plot normally shows some metric for each experiment. It would be great to show the the parameters when hovering the experiment.

**Comment by ceceshao1** [comment]
Hi @sotte - thanks for suggesting this. I'll add it to our queue of feature requests 👍 

Have you tried the parallel coordinates chart option? It has different parameters on each axis so you can see how those parameters impact a metric (see screenshot below)

This sample public project has a live example of the parallel coordinates chart that you can test: https://www.comet.ml/cometpublic/parameter-space-exploration

![image](https://user-images.githubusercontent.com/24228106/51328717-fe1caf80-1a41-11e9-96c2-ab70a111c6d4.png)

**Comment by sotte** [comment]
Yes, I have,I like it, and I'm happy that I don't have to create these plots myself anymore :)

If you're looking for inspiration regarding visualizations, ModelDB has some nice ones as well:
http://modeldb.csail.mit.edu:3000/projects

**Comment by Nimrod007** [comment]
added to project bar charts
