### ISSUE TITLE
Not compatible with pytorch multiprocessing

### ISSUE THREAD

**Issue by zhuchen03** [comet-ml/issue-tracking#202]
comet seems not compatible with multiprocessing module of pytorch. If I set torch.multiprocessing.set_start_method(“spawn”, force=True), it will exit with an error:
Traceback (most recent call last):
  File “/home/chen/anaconda3/lib/python3.6/multiprocessing/process.py”, line 258, in _bootstrap
    self.run()
  File “/home/chen/anaconda3/lib/python3.6/multiprocessing/process.py”, line 93, in run
    self._target(*self._args, **self._kwargs)
  File “/home/chen/anaconda3/lib/python3.6/site-packages/comet_ml/console.py”, line 117, in _tee_process
    r, w, x = select.select(pipes, [], [], 0.1)
OSError: [Errno 9] Bad file descriptor

**Comment by moinnadeem** [comment]
+1, is it possible to do something about this? I love Comet, but I love parallelizing my scripts more.

**Comment by dsblank** [comment]
We're are looking at this issue. Hope to report back here soon.

**Comment by dsblank** [comment]
If you use `Experiment(auto_output_logging=None)` does that allow the rest of comet_ml to work?

**Comment by dsblank** [comment]
I believe that all issue related to this problem have been addressed. Please reopen and describe if you have any questions or issues. Thanks for reporting!

**Comment by leej35** [comment]
FYI, I had the same issue and resolved it with setting `Experiment(auto_output_logging="simple")`. For set it as `None`, I could able to run the program without any problem but the logging didn't work.

**Comment by anisaha1** [comment]
Hi @dsblank, @leej35,
I am facing issues with pytorch multiprocessing code. I looked at your comments here and also in issue [#313](https://github.com/comet-ml/issue-tracking/issues/313) but I couldn't make it work. 

Comet dashboard creates multiple experiments and fails. Could you please give me a simple snippet of how to use Experiment and/or ExisitingExperiment to log metrics in this [code](https://github.com/facebookresearch/moco/blob/master/main_moco.py)? The logging would be in train().

**Comment by zhuchen03** [comment]
You can let only one process create the Experiment instance and log the data.

**Comment by anisaha1** [comment]
@zhuchen03 With computation happening in multiple GPUs, I assume the master process should only log metrics. Can you please show me how in the code I linked to above?

**Comment by zhuchen03** [comment]
I only tried similar code on a single machine with multiple GPUs. You can check the rank here https://github.com/facebookresearch/moco/blob/master/main_moco.py#L154 and only let the process with `args.rank==0` to log the metrics.
