### ISSUE TITLE
[Feature Request] Add `log_folder`

### ISSUE THREAD

**Issue by sotte** [comet-ml/issue-tracking#203]
I normally collect all artifacts of an experiment in a single folder. It would be great if there was a `log_folder(path_to_folder)` so that I don't have to scatter many `log_asset`s throughout the code.

**Comment by enpinzolas** [comment]
Hi! 

You could create a function similar to this to bypass that problem:
```python
from os import listdir
from os.path import isfile, join


def log_dir(path_to_folder):
    for f in listdir(path_to_folder):
        if isfile(join(path_to_folder, f)):
            log_asset(join(path_to_folder, f))
```

**Comment by dsblank** [comment]
This has now been added as `Experiment.log_asset_folder()`

Thanks all!
