### ISSUE TITLE
GPU graph resets every few seconds

### ISSUE THREAD

**Issue by sotte** [comet-ml/issue-tracking#205]
I'm training on a single GPU. Every few seconds the GPU utilization plots jumps between a reasonable plot (~80% utilization) and a zero utilization plot. Any ideas what this could be?

Examples:
![screenshot from 2019-01-22 14-01-24](https://user-images.githubusercontent.com/79138/51537260-5393fa80-1e4e-11e9-8996-3c1d840fce02.png)
![screenshot from 2019-01-22 14-01-46](https://user-images.githubusercontent.com/79138/51537262-5393fa80-1e4e-11e9-98f1-fce767f4ee7a.png)

**Comment by dsblank** [comment]
@sotte Looking into this... thanks for reporting!

**Comment by sotte** [comment]
Does this mean it was fixed in the newest release or you could not reproduce it?

**Comment by ceceshao1** [comment]
@sotte - the graph reset issue was fixed in the newest release 👍

**Comment by sotte** [comment]
Thanks!
