### ISSUE TITLE
[Feature Request] log_asset performance with file like objects

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#206]
Hi There!

The implementation for file like objects is:
```
        if file_like_object is not None:
            # Read the file_like_object and write it to a temporary file
            file_path = write_file_like_to_tmp_file(file_like_object)
            copy_to_tmp = False
```
This is important because (depending on the OS) performs a synchronous write to disk, which is slow (on the order of milliseconds) depending on the file size. (Note that some OS kernels treat temporary file writes as a write to memory instead of disk.)

Learn more here: https://stackoverflow.com/questions/35278482/tempfile-temporaryfile-vs-stringio 
The time to write a temporary file is 50x slower than stringio.

Would it be possible to not write the file like object to disk? Or could you make the write asynchronous?

Thanks!

**Comment by Lothiraldan** [comment]
Helo @PetrochukM, the main issue with using a stringio is that we would need to keep a copy of the file-like-object in memory which can be potentially huge.

In your case, are you trying to log lot of assets or huge assets?

**Comment by PetrochukM** [comment]
Hi There!

The file like object is already in memory at the time it's logged; I think it'd be fine to continue keeping in memory, right?

Neither, this issue is not a big concern for me! Typically, I log a couple megabytes of assets every epoch.

Thanks!

**Comment by dsblank** [comment]
We are working on a solution for this.

**Comment by dsblank** [comment]
@PetrochukM Great news! We now support `Experiment.log_image(..., copy_to_tmp=False)` and `Experiment.log_asset(..., copy_to_tmp=False)` This allows file-like objects (and all of the memory-based image formats, like arrays) to go directly to comet_ml without creating temp files. Becareful not to run out of memory!
