### ISSUE TITLE
Delete button disappeared

### ISSUE THREAD

**Issue by leej35** [comet-ml/issue-tracking#207]
I cannot see the delete button on the experiment list view page. 
<img width="928" alt="screen shot 2019-01-24 at 1 24 01 pm" src="https://user-images.githubusercontent.com/1673195/51699718-7a336c00-1fdb-11e9-8c16-739c6e304338.png">

**Comment by ceceshao1** [comment]
Hi @leej35 - we introduced a new Archive feature so users could keep their active experiment list organized.

If you'd like to hard delete your experiments, you can archive them then navigate to the Project `Archive` tab to delete them. You will also have an option to restore those experiments on the `Archive` tab.
