### ISSUE TITLE
In dashboard notes, can't type multibyte strings 

### ISSUE THREAD

**Issue by fufufukakaka** [comet-ml/issue-tracking#21]
Hello. I am a comet.ml user in Japan(It is awesome products. Thank you.)

When I trying to type multi-byte strings(japanese), these strings were not saved correctly.

(before reload)
![image](https://user-images.githubusercontent.com/13670337/38530434-6ec9971e-3ca5-11e8-8f9b-4a91192b1e44.png)

(after reload)
![image](https://user-images.githubusercontent.com/13670337/38530456-87ce6b7c-3ca5-11e8-8a05-4cbd76e1e759.png)

I think this cause may be that strings is not saved in utf-8 encodings. 

Thank you.

**Comment by gidim** [comment]
Thanks @fufufukakaka. Good catch!
Will fix asap and let you know once new version is deployed

**Comment by Nimrod007** [comment]
solved!
https://www.comet.ml/Nimrod007/test-emoji?openTab=1

**Comment by fufufukakaka** [comment]
Thanks!!!
