### ISSUE TITLE
Mobile-friendly website

### ISSUE THREAD

**Issue by alexanderkoller** [comet-ml/issue-tracking#210]
Hi,

I have some experiments running and would like to track their progress using comet.ml on my iPhone (using mobile Chrome or Safari).

However, the dashboard page for my comet.ml project is a bit clunky - I can see the top left of the running experiments, but I can't scroll down or to the right. This makes the dashboard unusable for me on the phone.

Is there any chance that the comet.ml website could be made responsive, such that it displays correctly on mobile browsers?

Best,
Alexander.

**Comment by gidim** [comment]
Hi @alexanderkoller 
Thanks for reporting. Have you tried to use the "show desktop website" option on your ios chrome app?

Currently building a responsive version of the app is not top priority.

**Comment by dsblank** [comment]
We have updated the list of projects page, and made other UX enhancements. 

If you have additional comments or questions, don't hesitate to ask. Thanks for reporting!
