### ISSUE TITLE
log_parameter fails for long list

### ISSUE THREAD

**Issue by kdmcdrm** [comet-ml/issue-tracking#211]
I'm trying to save the list of features my model is training and testing against so I can compare performance between experiments down the road.
I tried log_parameter with the list of 63 strings and found that nothing appears on the experiment page. Is this just a display issue? Or did the parameter message not get transferred?

Ideally I would like to log this as a log_other, but it looks like that method doesn't support lists at all. As a workaround I'm planning to log this as an asset but I do think it makes sense to have a simple call to log list/array objects.

**Comment by dsblank** [comment]
Does it work if you just turn the list of strings into a string, like so:

```python
experiment.log_other("long list", str(long_list))
```

If so, we can fix that.

**Comment by ceceshao1** [comment]
@kdmcdrm - just wanted to check in on your reported issue. Did @dsblank's proposed method above work for you?

**Comment by kdmcdrm** [comment]
@ceceshao1 I haven't had a chance to try it and, unfortunately, I might not get a chance for a few weeks.

**Comment by ceceshao1** [comment]
@kdmcdrm - not a problem. If you want to provide more information about your specific experiment, the team is also available on [Slack](https://join.slack.com/t/cometml/shared_invite/enQtMzM0OTMwNTQ0Mjc5LTM4ZDViODkyYTlmMTVlNWY0NzFjNGQ5Y2Q1Y2EwMjQ5MzQ4YmI2YjhmZTY3YmYxYTYxYTNkYzM4NjgxZmJjMDI)

**Comment by rezahay** [comment]
Dear @dsblank, I have the same problem. The problem occurs even if I add str(longList). The problem remains after upgrading Comet to the new version.

**Comment by dsblank** [comment]
@rezahay Can you send me a link to an experiment? If you do want to send it in public, please send to support@comet.ml and we can continue discussion there.

**Comment by rezahay** [comment]
Thanks for your response.Here is the link: Comet.ml - Supercharging Machine Learning

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Comet.ml - Supercharging Machine Learning

Comet lets you track code, experiments, and results on ML projects. It’s fast, simple, and free for open source ...
 |

 |

 |


You can see in the code:"FEATURE_COLUMNS": str(DatasetParams.FEATURE_COLUMNS), that I added "str" but it doesn't help. The DatasetParams.FEATURE_COLUMNS are:

| [ |
| 
 |  |
| 327 |                      |
| 328 |                     'sequence', |
| 329 |                     'normalized_length', |
| 330 |                     'normalized_abs_surf_acc','3_wm_normalized_abs_surf_acc','5_wm_normalized_abs_surf_acc','7_wm_normalized_abs_surf_acc','9_wm_normalized_abs_surf_acc', |
| 331 |                     'normalized_hydropathy_index','3_wm_normalized_hydropathy_index','5_wm_normalized_hydropathy_index','7_wm_normalized_hydropathy_index','9_wm_normalized_hydropathy_index', |
| 332 |                     'rel_surf_acc','3_wm_rel_surf_acc','5_wm_rel_surf_acc','7_wm_rel_surf_acc','9_wm_rel_surf_acc', |
| 333 |                     'prob_sheet','3_wm_prob_sheet','5_wm_prob_sheet','7_wm_prob_sheet','9_wm_prob_sheet', |
| 334 |                     'prob_helix','3_wm_prob_helix','5_wm_prob_helix','7_wm_prob_helix','9_wm_prob_helix', |
| 335 |                     'prob_coil','3_wm_prob_coil','5_wm_prob_coil','7_wm_prob_coil','9_wm_prob_coil', |
| 336 |                     'pssm_A','pssm_R','pssm_N','pssm_D','pssm_C','pssm_Q','pssm_E','pssm_G','pssm_H','pssm_I', |
| 337 |                     'pssm_L','pssm_K','pssm_M','pssm_F','pssm_P','pssm_S','pssm_T','pssm_W','pssm_Y','pssm_V', |
| 338 |                     '3_wm_pssm_A','3_wm_pssm_R','3_wm_pssm_N','3_wm_pssm_D','3_wm_pssm_C','3_wm_pssm_Q','3_wm_pssm_E', |
| 339 |                     '3_wm_pssm_G','3_wm_pssm_H','3_wm_pssm_I','3_wm_pssm_L','3_wm_pssm_K','3_wm_pssm_M','3_wm_pssm_F', |
| 340 |                     '3_wm_pssm_P','3_wm_pssm_S','3_wm_pssm_T','3_wm_pssm_W','3_wm_pssm_Y','3_wm_pssm_V', |
| 341 |                     '5_wm_pssm_A','5_wm_pssm_R','5_wm_pssm_N','5_wm_pssm_D','5_wm_pssm_C','5_wm_pssm_Q','5_wm_pssm_E', |
| 342 |                     '5_wm_pssm_G','5_wm_pssm_H','5_wm_pssm_I','5_wm_pssm_L','5_wm_pssm_K','5_wm_pssm_M','5_wm_pssm_F', |
| 343 |                     '5_wm_pssm_P','5_wm_pssm_S','5_wm_pssm_T','5_wm_pssm_W','5_wm_pssm_Y','5_wm_pssm_V', |
| 344 |                     '7_wm_pssm_A','7_wm_pssm_R','7_wm_pssm_N','7_wm_pssm_D','7_wm_pssm_C','7_wm_pssm_Q','7_wm_pssm_E', |
| 345 |                     '7_wm_pssm_G','7_wm_pssm_H','7_wm_pssm_I','7_wm_pssm_L','7_wm_pssm_K','7_wm_pssm_M','7_wm_pssm_F', |
| 346 |                     '7_wm_pssm_P','7_wm_pssm_S','7_wm_pssm_T','7_wm_pssm_W','7_wm_pssm_Y','7_wm_pssm_V', |
| 347 |                     '9_wm_pssm_A','9_wm_pssm_R','9_wm_pssm_N','9_wm_pssm_D','9_wm_pssm_C','9_wm_pssm_Q','9_wm_pssm_E', |
| 348 |                     '9_wm_pssm_G','9_wm_pssm_H','9_wm_pssm_I','9_wm_pssm_L','9_wm_pssm_K','9_wm_pssm_M','9_wm_pssm_F', |
| 349 |                     '9_wm_pssm_P','9_wm_pssm_S','9_wm_pssm_T','9_wm_pssm_W','9_wm_pssm_Y','9_wm_pssm_V', |
| 350 |                     'domain', |
| 351 |                     ] |


I get the same problem when my experiment uploads a long list of floats. As the following list is small it gets uploaded:test_IPB_Box [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0025906735751295338,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]
but with log lists I get problems.
Thanks in advance,Reza HaydarlouVU University Amsterdam
    On Thursday, May 7, 2020, 02:05:42 PM GMT+2, Doug Blank <notifications@github.com> wrote:  
 
 


@rezahay Can you send me a link to an experiment? If you do want to send it in public, please send to support@comet.ml and we can continue discussion there.

**Comment by dsblank** [comment]
@rezahay I'm not sure exactly what you posted above, but it isn't a link to an experiment.

In any event, I think the main issue is that logging a very long list of strings as a string isn't very helpful. Perhaps it would be more helpful for you if you logged them as numbered features, perhaps something like:

| Feature Number |  Feature Name |
| ---------------------- | -------------------- |
| feature_1            |  7_wm_pssm_W |
| feature_2            |  7_wm_pssm_H |

...

Some code to do something better:

```python
for i, feature_name in enumerate(long_list_of_features):
    experiment.log_other("feature_%s" % (i + 1), feature_name)
```

**Comment by rezahay** [comment]
Hi Doug,
I think this is the right link: https://www.comet.ml/rezahay/cnn-ppi/f6cf32a0062540faa5b07af37769382f?experiment-tab=params
    On Thursday, May 7, 2020, 06:01:11 PM GMT+2, Doug Blank <notifications@github.com> wrote:  
 
 


@rezahay I'm not sure exactly what you posted above, but it isn't a link to an experiment.

In any event, I think the main issue is that logging a very long list of strings as a string isn't very helpful. Perhaps it would be more helpful for you if you logged them as numbered features, perhaps something like:

| Feature Number | Feature Name |
| feature_1 | 7_wm_pssm_W |
| feature_2 | 7_wm_pssm_H |


...

Some code to do something better:
for i, feature_name in enumerate(long_list_of_features):
    experiment.log_other("feature_%s" % (i + 1), feature_name)
