### ISSUE TITLE
[Feature Request] Hide all experiments

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#214]
Hi There!

When using the grouping feature, it is difficult to hide all the experiments. To do so, I need to open up each individual group and hide each individual experiment.

Would it be possible to implement some short cut method for doing so? It is fairly tedious at the moment. 

Typically, I use the visualizations to compare a couple of experiments all at the same time, not all of them. It is rarely useful to compare all of my 50+ experiments for me.

Thanks,
Michael

**Comment by dsblank** [comment]
If you ungroup that will unselect all of the selected experiments. Then you can re-group to continue. Does that help?

Please reopen and describe if you have any questions or issues. Thanks for reporting!
