### ISSUE TITLE
Having a reset view/query option

### ISSUE THREAD

**Issue by backpropper** [comet-ml/issue-tracking#215]
It would be nice to have a 'reset view' button which resets the view to the last saved one which is essentially what you get if you dont save and refresh. But it would be nice to save the trouble of refreshing everytime :)

**Comment by backpropper** [comment]
A similar option for 'reset query' would be nice to have as well.

**Comment by backpropper** [comment]
Any updates on this?

**Comment by dsblank** [comment]
We'll report back when there is an update. We're busy working our way through many great enhancements. We think you will like what we are developing. Thanks for your support!

**Comment by dsblank** [comment]
I believe that all issue related to this problem have been addressed. Please reopen and describe if you have any questions or issues. Thanks for reporting!
