### ISSUE TITLE
Ability to highlight some experiments and drag them around

### ISSUE THREAD

**Issue by backpropper** [comet-ml/issue-tracking#216]
It would be great to have some experiments 'pinned' or 'highlighted with color' to easily distinguish between some important experiments. 

Also it would be nice to be able to drag some experiments (up and down) for easy comparison.

**Comment by ceceshao1** [comment]
Hi @backpropper - One way you can highlight the experiments is to use the Experiment Tags (see how to add tags [here](https://www.comet.ml/docs/python-sdk/Experiment/#experimentadd_tag)). Once you tag the experiments, you can add a filter for the tags.

I've added your second request to be able to drag + drop to our list of requests!

**Comment by backpropper** [comment]
The functionality that I am asking is that if you can tag/highlight some experiments, and be able to freeze those experiments and scroll through the rest of the experiments for faster comparison
