### ISSUE TITLE
Error when creating OfflineExperiment on Windows 10

### ISSUE THREAD

**Issue by PhilippeMarcotte** [comet-ml/issue-tracking#219]
When I try to create an instance of OfflineExperiment, the constructor execute the following code:
```
# Check that the offline directory is usable
try:
    zipfile = self._get_offline_archive(offline_directory, "test")
    # Remove the file
    os.remove(zipfile.filename)
except (OSError, IOError) as exc:
    raise InvalidOfflineDirectory(self.offline_directory, str(exc))
``` 
it creates a test.zip to verify that the specified directory is usable. However, when it tries to remove it with `os.remove` it gives the following error:
```
comet_ml.exceptions.InvalidOfflineDirectory: Invalid offline directory: ./logs
Reason:[WinError 32] The process cannot access the file because it is being used by another process: './logs\\test.zip'
```

I simply added a `zipfile.close()` before the `os.remove` and it seems to have fix the issue.

This only happens on Windows 10. I'm unable to reproduce the error on Linux.

**Comment by backpropper** [comment]
It happens on linux as well if I have multiple threads writing to the same directory

**Comment by Lothiraldan** [comment]
We merged a fix today that will fix this issue and will be part of our next release.

**Comment by NishanthVAnand** [comment]
When would the next release be?

**Comment by Lothiraldan** [comment]
@NishanthVAnand Sorry for the delayed answer, it should be fixed in latest release, could you give it a try?

**Comment by Lothiraldan** [comment]
It should be fixed, please reopen this ticket if that's not the case.
