### ISSUE TITLE
[Bug] Parallel coords selection picks wrong runs

### ISSUE THREAD

**Issue by miquelmarti** [comet-ml/issue-tracking#220]
When selecting a range of values for the target metric in the parallel coords plot wrong runs are chosen for the other plots! The best ones are missing and some not in the range appear.

Before selection:
![screenshot from 2019-02-25 12-00-56](https://user-images.githubusercontent.com/11225150/53333075-24612500-38f5-11e9-9f58-851eb27c5838.png)
After selection:
![screenshot from 2019-02-25 12-01-15](https://user-images.githubusercontent.com/11225150/53333074-24612500-38f5-11e9-96ca-7e55e1a7dbaa.png)

**Comment by ceceshao1** [comment]
@miquelmarti - thanks for reporting this. We'll investigate this and update you as soon as we can!

**Comment by Nimrod007** [comment]
fixed in `V5.4.3`
please refresh the page
