### ISSUE TITLE
[Bug] Connection to comet hangs after around 80 experiments

### ISSUE THREAD

**Issue by miquelmarti** [comet-ml/issue-tracking#221]
After around 80 runs using your parameter optimizer and tracking I get one experiment that does not even start training, just halts.

This was with a very simple example following  https://www.comet.ml/parameter-optimization

**Comment by ceceshao1** [comment]
Hey @miquelmarti - just wanted to check since you closed the issue. Were you able to resolve the issue?

**Comment by miquelmarti** [comment]
I apologize. I found out this was not related to comet.

**Comment by ceceshao1** [comment]
Gotcha - thanks for confirming @miquelmarti !
