### ISSUE TITLE
log_asset fails with overwrite=True

### ISSUE THREAD

**Issue by kdmcdrm** [comet-ml/issue-tracking#222]
It looks to me like log_asset is failing when I call it multiple times with overwrite=True

I want to log the full set of predictions and labels to allow for model comparison after the fact. If I run the following multiple times I get no asset at the end. 
``` python
y_pred = pd.Series(np.squeeze(y_pred), index=y_test.index)  # Add the index back to the prediction
y_pred_fh = tempfile.NamedTemporaryFile(suffix=".pkl.gz")
pd.to_pickle(y_pred, y_pred_fh.name, compression="gzip")
exp.log_asset(file_like_object=y_pred_fh, file_name="y_pred.pkl.gz", overwrite=True)
y_pred_fh.close()
```

**Comment by dsblank** [comment]
@kdmcdrm The following test program works (although 5 assets show in the comet.ml Assets tab):

```python
import numpy as np
import comet_ml
import tempfile
import pandas as pd

exp = comet_ml.Experiment()

for i in range(5):
    y_pred = np.array((1,1))
    y_pred[0] = i
    y_pred = pd.Series(np.squeeze(y_pred), index=y_pred) 
    y_pred_fh = tempfile.NamedTemporaryFile(suffix=".pkl.gz")
    pd.to_pickle(y_pred, y_pred_fh.name, compression="gzip")
    exp.log_asset(file_like_object=y_pred_fh, file_name="y_pred.pkl.gz", overwrite=True)
    y_pred_fh.close()
```
Do you get the same results with this test program?

**Comment by dsblank** [comment]
I believe that all issue related to this problem have been addressed. Please reopen and describe if you have any questions or issues. Thanks for reporting!
