### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by namednil** [comet-ml/issue-tracking#226]
Hi,

I guess this is not a bug but I have been noticing relatively high (audible) CPU load when I'm in project view, i.e. no diagram/code etc. is shown, I just see a few spinning arrows that tell me that my experiments are running. 
I can't image there are heavy computations that need to be performed in my browser at this point.

If that's of importance: I use a Google Chrome 72 on linux.

**Comment by gidim** [comment]
Hi @namednil  - we have made significant optimizations to the web app. Hopefully this is not an issue anymore. 

Feel free to re-open if needed.
