### ISSUE TITLE
Problem with parallel coordinates not showing lines on dowload

### ISSUE THREAD

**Issue by fabawi** [comet-ml/issue-tracking#227]
The issue with the parallel coordinates has been addressed before #194 and the problem was fixed, however, the issue still remains when downloading the images in SVG or JPEG format. The graph outline appears, but the lines do not show up

**Comment by ceceshao1** [comment]
Thanks for reporting this @fabawi - we were able to reproduce this issue and will have a fix out soon. We will update this Github issue once we deploy the fix.

**Comment by backpropper** [comment]
Updates on this?

**Comment by Nimrod007** [comment]
fixed.
