### ISSUE TITLE
[Feature Request] Color scales on the experiment list columns

### ISSUE THREAD

**Issue by leej35** [comet-ml/issue-tracking#229]
Like MS Excel's conditional formatting on a column, I think it would be very helpful to analyze the results of multiple experiments together if we can apply a color scale on a column on the experiment list.
![aced9e50-6c47-4bb1-80e8-36c103c38877](https://user-images.githubusercontent.com/1673195/54291279-b8ccb800-4582-11e9-83f6-96b2350ab5a4.png)

(image: https://support.office.com/en-us/article/apply-conditional-formatting-in-excel-34402f91-c7e7-4060-944c-65d913033d18)

**Comment by gidim** [comment]
That's a great idea! We'll look into this @leej35
