### ISSUE TITLE
Offline Experiment logging error

### ISSUE THREAD

**Issue by NishanthVAnand** [comet-ml/issue-tracking#230]
I am running my experiments on a cluster. I have 18 instances of the same code running, each instance is different (different hyperparameter). The problem is - it throws up error about the non existancy of directory in a few runs (4,5, etc randomly) and doesn't thorw error on the remaining instances. I am not sure why this is happening. I am adding a detailed traceback of the error. Also, I am not sure why it is looking for `test.zip`
```
Traceback (most recent call last):
  File "/home/nish127/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/RecurrentPolicy/lib/python3.6/site-packages/comet_ml/offline.py", line 125, in __init__
    os.remove(zipfile.filename)
FileNotFoundError: [Errno 2] No such file or directory: '../comet_offline/test.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 32, in <module>
    experiment = OfflineExperiment(project_name="recurrent-value", workspace="nishanthvanand",disabled=args.disable_log, offline_directory="../comet_offline")
  File "/home/nish127/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/RecurrentPolicy/lib/python3.6/site-packages/comet_ml/offline.py", line 127, in __init__
    raise InvalidOfflineDirectory(self.offline_directory, str(exc))
comet_ml.exceptions.InvalidOfflineDirectory: Invalid offline directory: ../comet_offline
Reason:[Errno 2] No such file or directory: '../comet_offline/test.zip'
```

**Comment by gidim** [comment]
@Lothiraldan - please take a look

**Comment by Lothiraldan** [comment]
@NishanthVAnand I think it's related to https://github.com/comet-ml/issue-tracking/issues/219 and it should be fixed in the next SDK release. Could you confirm that you are running multiple processes with the same offline directory?

**Comment by NishanthVAnand** [comment]
Yes, I am running multiple processes with the same Offline directory. multiple processes are to run the code parallelly but the write operation to the file is synced across all the processes, hence just one write operation.

**Comment by Lothiraldan** [comment]
@NishanthVAnand Sorry for the delayed answer, it should be fixed in latest release, could you give it a try?

**Comment by dsblank** [comment]
I think this is resolved. Thanks all!
