### ISSUE TITLE
[feature request] rearrange graphs/experiments

### ISSUE THREAD

**Issue by backpropper** [comet-ml/issue-tracking#232]
to be able to drag around the exp and graphs

**Comment by gidim** [comment]
Please provide additional information

**Comment by backpropper** [comment]
Rearrange graphs manually in a project/experiment. Can you do that right now?

**Comment by backpropper** [comment]
this would be quite useful. Let me know if it is done?

**Comment by gidim** [comment]
Not yet but it's on the roadmap!

**Comment by Nimrod007** [comment]
this was added, you can now resize drag and drop charts
