### ISSUE TITLE
having a more vivid color scheme like tensorboard

### ISSUE THREAD

**Issue by backpropper** [comet-ml/issue-tracking#233]
The current color scheme for experiments makes it hard to distinguish between different experiments. It would be nice to have some bright colors like the ones used in tensorboard.

**Comment by dsblank** [comment]
That is an interesting idea! I think we will have something that might help with this that we will release in the next month or two. Stay tuned!

**Comment by backpropper** [comment]
for parallel coordinates graph, it will actually make it more useful, which is not that useful as of now

**Comment by gidim** [comment]
@backpropper - the objective of the color scale in the parallel coordinates (PC) is very different than in other charts. In bar/line charts you want different colors to distinguish the different lines. In PC it's designed to allow you to see which model is better than the other (i.e more orange).

Which of these charts are you having issues with?

**Comment by backpropper** [comment]
Yes thats not what I was saying.

What I meant was that the color tones even in single experiment or parallel coordinates are not that vivid to distinguish whats going on

See this in `wandb` for example:
<img width="1174" alt="Screen Shot 2019-04-07 at 5 44 29 PM" src="https://user-images.githubusercontent.com/5422228/55690275-1fb07780-595d-11e9-853b-934b4c7af73c.png">

**Comment by backpropper** [comment]
as compared to this:

<img width="1249" alt="21-22" src="https://user-images.githubusercontent.com/5422228/55690285-45d61780-595d-11e9-9c2f-fbad98896b34.png">

**Comment by gidim** [comment]
Thanks for sharing. Seems like it's mostly the width of the lines but we'll take a look and see if we can improve!

**Comment by backpropper** [comment]
yeah and the color contrast too I guess

**Comment by gidim** [comment]
How about this option? 
https://codepen.io/plotly/pen/gGbOeG

**Comment by backpropper** [comment]
yup this is perfect!

**Comment by gidim** [comment]
Just realized the link I posted earlier is outdated. Take a look at this please:
https://codepen.io/pen @backpropper

**Comment by backpropper** [comment]
How about you give user the option to choose among a set of plotly color configs?

**Comment by backpropper** [comment]
this is way better now! Thanks!
