### ISSUE TITLE
Jupyter Notebook stdout and stderr not showing up in the Output Tab

### ISSUE THREAD

**Issue by kevinyang372** [comet-ml/issue-tracking#234]
Hi! I am using comet.ml on jupyter notebook to log my experiment results.

```
# initialization cell
from comet_ml import Experiment
experiment = Experiment(api_key=api_key,project_name=project, workspace=workspace)

# output cell
print("This is an output")

# end cell
experiment.end()
```

However, I noticed the stdout and stderr in the cell output is not getting logged into the Output Tab. Is there any way I could solve this problem? Thank you!

**Comment by dsblank** [comment]
@kevinyang372 Output to the cell is not standard out. So, in general, print won't be the command that you want to use. However, if you can change print() to experiment.log_html() then you can log your output to the HTML tab of the experiment.

If you wanted to, you could redefine print itself; something like:

```python
def new_print(*args):
    for arg in args:
        experiment.log_html("<p>%s</p>" % arg)
print = new_print
```
Hope that helps!

**Comment by kevinyang372** [comment]
@dsblank Thank you for your response! Just wondering if there is any other way to log cell outputs? Maybe like transforming the notebook output into stdout so it will be easier for other developers in my team to log model training results and errors.

**Comment by dsblank** [comment]
@kevinyang372 That is an interesting idea! Let us think about what the best way to do that would be. Thanks for the suggestion!

**Comment by dsblank** [comment]
As a workaround (sorta) you can use the `Experiment(auto_output_logging="simple")` This isn't perfect in the Jupyter notebook because all of the output afterwards goes to that cell. But it might work for a small subset of uses. 

We'll find a real solution and report back.

**Comment by dsblank** [comment]
We are still working on this.

**Comment by dsblank** [comment]
This has been implemented and will be included in the next release.
