### ISSUE TITLE
Finding currently running experiments with the REST API

### ISSUE THREAD

**Issue by moinnadeem** [comet-ml/issue-tracking#235]
Hi,

I would like to build upon the API to deliver push notifications when my experiments complete an epoch. Could you tell me how to determine which experiments are currently running in a project? I didn't see this in the documentation.

Thanks!

**Comment by dsblank** [comment]
You could look at `end_server_timestamp` to see if enough time has passed with out an update (see https://www.comet.ml/docs/rest-api/endpoints/#experiments )

Perhaps better would be to have:

```python
experiment.log_other("status", "running")
## your code
experiment.log_other("status", "done")
```
and then you could report on those experiments that are not "done". See https://www.comet.ml/docs/rest-api/endpoints/#experimentlog-other

Let us know if that doesn't work.
