### ISSUE TITLE
Show Step Slider also when figure opened

### ISSUE THREAD

**Issue by Haydnspass** [comet-ml/issue-tracking#236]
The Filter by step slider is really useful, however it's a petty that one can only use it when the figure is not opened / maximised. It would be nice if one could still use the slider in the maximised mode. For me looking at the output images over different epochs is really useful.

**Comment by Haydnspass** [comment]
and/or response to keyboard arrow keys.

**Comment by ceceshao1** [comment]
@Haydnspass - Thanks for suggesting this Lucas! We'll add it to our feature backlog and update you on this Github issue once any changes are made.

**Comment by Haydnspass** [comment]
@ceceshao1 nice! This has also the benefit that currently it is ambiguous what a step means. A step in a training process, for example, could mean a single batch but for the test process a complete epoch.

**Comment by Nimrod007** [comment]
internal issue `10129`
