### ISSUE TITLE
Putting the GPU logging flag back

### ISSUE THREAD

**Issue by backpropper** [comet-ml/issue-tracking#237]
Please put this flag back :)

`os.environ['COMET_OVERRIDE_FEATURE_SDK_GPU_MONITOR'] = '0'`

**Comment by Nimrod007** [comment]
you can now use `log_env_gpu` in the `Experiment` (since version  `comet-ml 1.0.50`)

**Comment by backpropper** [comment]
Can you update the docs as well?

**Comment by dsblank** [comment]
Thanks! The docs have been updated and will be visible when they are deployed next week.
