### ISSUE TITLE
Reproduce not working

### ISSUE THREAD

**Issue by Haydnspass** [comet-ml/issue-tracking#238]
Hey there,

in my case the reproduce button does not work. I also linked it to the github repository.
Clicking on "Click here to learn about Git Integration" is also a dead end (https://www.comet.ml/docs/reproduce/ - 404 not found).

Environment Information
No environment information available

Git Information
Not Available - Click here to learn about Git Integration

Run
No run command available.

**Comment by ceceshao1** [comment]
Hi @Haydnspass - are you in a git directory or a Jupyter notebook running your experiments? The reproduce button will display the environment and run command information when you're in either of those scenarios.

Regarding the 404 error page, I've added a task on our end to update the link to the right documentation. Here's the correct page: https://www.comet.ml/docs/user-interface/#the-reproduce-button

**Comment by Haydnspass** [comment]
@ceceshao1 Hi! 
Yes, not only am I in a git directory, but I also connected the project with my GitHub repository.

**Comment by gidim** [comment]
Hi @Haydnspass - can you please add the following lines to the *top* of your file and share the log file with us? You can email it support@comet.ml
```
import os
os.environ['COMET_LOGGING_FILE'] = '/tmp/comet.log'
os.environ['COMET_LOGGING_FILE_LEVEL'] = 'DEBUG'
```

**Comment by Haydnspass** [comment]
Works! Can be tricky because the git might get corrupted, however it can then be just pushed again.
