### ISSUE TITLE
Making the filtering of experiments faster

### ISSUE THREAD

**Issue by backpropper** [comet-ml/issue-tracking#239]
It would be great if there is an option to specify all the filters and then run ok to filter the experiments faster. Right now it takes a lot of time when you remove lets say all the filters and try to add new ones (if you have any logged experiments). Most of the times, it just hangs and there is no option to do this otherwise.

**Comment by gidim** [comment]
HI @backpropper  - we are actually in the process of deploying a highly optimized version of the query builder. I'm closing this for now because we believe that with the new version this won't be an issue anymore.

If you still feel this is important please reopen

**Comment by backpropper** [comment]
Do you have a specific ETA on this?

**Comment by gidim** [comment]
You should see improvements in about two weeks.
