### ISSUE TITLE
Option to expand each visualization individually

### ISSUE THREAD

**Issue by backpropper** [comet-ml/issue-tracking#241]

**Comment by dsblank** [comment]
Can you give a little more detail about what you mean? What view would you like to change? What would like to see?

**Comment by backpropper** [comment]
When we add a chart/visualization right now, we can only expand the view for all charts and not for just one of them

**Comment by dsblank** [comment]
I see. Thanks for the clarification!

**Comment by gidim** [comment]
Following up on this: Are you expecting a modal opening with a full screen chart?
Also are you referring to the experiment or projects charts?

**Comment by backpropper** [comment]
I dont understand the question. 
I'm referring to expanding individual project charts.

**Comment by gidim** [comment]
I'm not sure I understand what you mean either (: 
1. Which charts are you referring to? the one on the project level or inside an experiment?
2. What do you mean by "expand"

**Comment by backpropper** [comment]
1. As I said project level charts
2. 
<img width="166" alt="Screen Shot 2019-04-05 at 4 47 55 PM" src="https://user-images.githubusercontent.com/5422228/55655625-b98fed00-57c2-11e9-8cd1-c24cd186087b.png">

**Comment by gidim** [comment]
Thanks for clarifying! This is not currently on the roadmap but we'll add it now.

**Comment by backpropper** [comment]
I'm aksing this because for graphs like PC you need expanded view but not for other normal graphs

**Comment by dsblank** [comment]
This has now been deployed as a "Layout" option on the views. Thanks for the suggestion!
