### ISSUE TITLE
Option to filter based on hostname

### ISSUE THREAD

**Issue by backpropper** [comet-ml/issue-tracking#242]

**Comment by gidim** [comment]
Can you please provide more information? Are you referring to the query builder in the projects page?

**Comment by backpropper** [comment]
So there's is param named 'hostname' which comes from the system_metrics but right now we cannot use it for filtering the experiments

**Comment by gidim** [comment]
Got it. We'll add it! (and the rest of the system info).

**Comment by backpropper** [comment]
Any update on this, seems like this should be straight-forward?

**Comment by dsblank** [comment]
It is on our list, and we'll report here when done. As a workaround:

```
import socket
if socket.gethostname().find('.')>=0:
    name=socket.gethostname()
else:
    name=socket.gethostbyaddr(socket.gethostname())[0]
experiment.log_other("hostname", name)
```
