### ISSUE TITLE
Add pid (process-id) to system metrics as well

### ISSUE THREAD

**Issue by backpropper** [comet-ml/issue-tracking#243]

**Comment by gidim** [comment]
Great idea!

**Comment by backpropper** [comment]
Any update?

**Comment by gidim** [comment]
Still on the roadmap but you can easily achieve this by adding:
`experiment.log_system_info("pid", os.getpid())`

**Comment by dsblank** [comment]
An experiment's pid (process ID) should now show on the System Metrics tab. Thanks for the idea!
