### ISSUE TITLE
Add live progress bar for epochs and steps in current epoch

### ISSUE THREAD

**Issue by nlynn12** [comet-ml/issue-tracking#245]
Possibly something like [Aetros](https://d2gn4xht817m0g.cloudfront.net/p/product_screenshots/images/original/000/860/496/860496-96861544f1c7f59fe7a5356d5938b727104e7b5f.png?1518823513)

It's annoying to be forced to return to the terminal just to see how far the training has come.

**Comment by gidim** [comment]
Thanks @nlynn12 
That's a good idea. For non Keras users we'll have to figure a way to handle this. Something like this maybe?
`experiment.set_max_epoch()`
and then
```
for i in range(EPOCHS):
    experiment.set_curr_epoch(i)
```

what do you think?

**Comment by nlynn12** [comment]
That’s looks like a clean way to do it. :-) I’ve only worked in TensorFlow and PyTorch (in addition to Keras) but it looks like your suggestion fits those frameworks.

Venlig hilsen

Nicolai Anton Lynnerup

ErhvervsPhD Stipendiat
Mærsk Mc-Kinney Møller Instituttet, SDU
Konsulent, Teknologisk Institut
T 72 20 27 13
nicolai_lynnerup@hotmail.com
________________________________
