### ISSUE TITLE
Customize x-axis in Experiment page

### ISSUE THREAD

**Issue by KaleabTessera** [comet-ml/issue-tracking#247]
When viewing a single experiment, you can't customize the x axis to be epoch count. This is problematic because for example if you want to plot (train and test loss) vs number of epochs, this is not possible.

**Comment by KaleabTessera** [comment]
![image](https://user-images.githubusercontent.com/10942061/55650232-72672380-57e5-11e9-9540-b0df8134a5a1.png)

I am referring to this view @gidim , when you add a chart for an individual experiment.

**Comment by KaleabTessera** [comment]
Context from ticket : https://github.com/comet-ml/issue-tracking/issues/169

**Comment by gidim** [comment]
We are in the process of consolidating both chart builders (project/experiment). The project level builder already has this functionality.

Expected deliverable May 1st.

**Comment by felixkreuk** [comment]
Has this been implemented?
I am logging using log_metric and providing the step and epoch parameters, but I cant set the x-axis to be epochs.

**Comment by KaleabTessera** [comment]
As far as I know, it is still not supported.

**Comment by KaleabTessera** [comment]
When I try and set a custom x axis to one of my custom metrics, I get the error : `No data for this chart`. Any info on this? @gidim 

I know that metric has data and at correct time intervals.

**Comment by KaleabTessera** [comment]
So this works sometimes. I think the bug is when certain experiments don't have the custom x axis field that you are looking for. 

This is quite vital, as I can't log results over epochs using comet. @gidim  Any chance you could look at this? I can also provide more info if needed.

**Comment by gidim** [comment]
@KaleabTessera  - I'm assuming you're referring to the project level chart builder? 
If you can share a link to a project that reproduces this issue that would be great. You can share here (if it's public) or send to support@comet.ml and we will review!

**Comment by KaleabTessera** [comment]
Closing this.
Workaround to save and plot epochs: 
```
exp.log_metric("loss", test_loss, step=epoch)
```
I know you can do `epoch=epoch`, but I couldn't find a way to plot it on the web view.
