### ISSUE TITLE
Experiment Selection Bug

### ISSUE THREAD

**Issue by brennanNichyporuk** [comet-ml/issue-tracking#249]
![cometml_bug](https://user-images.githubusercontent.com/10503797/55995573-d9238b80-5c82-11e9-9f6f-15cade85a21d.gif)

**Comment by gidim** [comment]
Thanks for reporting @brennanNichyporuk! We'll look into this

**Comment by PetrochukM** [comment]
Hey! This is happening to me as well, not being able to checkmark, makes a lot of features hard to use.

This was happening on January 6th too...

![image](https://user-images.githubusercontent.com/7424737/56453031-fe05a780-62ef-11e9-8e32-0ef1d14bf460.png)

**Comment by PetrochukM** [comment]
Hi! The bug isn't fixed. Now that I am running 4 experiments, I am still experiencing it.

**Comment by dsblank** [comment]
I believe that all issue related to this problem have been addressed. Please reopen and describe if you have any questions or issues. Thanks for reporting!
