### ISSUE TITLE
[feature request] Filtering in charts

### ISSUE THREAD

**Issue by ceyzaguirre4** [comet-ml/issue-tracking#250]
It would be awesome to have two charts showing different experiments.
For instance, on the left show resnet 50 training graphs, and on the right resnet 101.

**Comment by ceceshao1** [comment]
Hi @ceyzaguirre4 - it sounds like your goal is to compare the training for different experiments. You have two different options:

1) Project visualizations - you can add a chart with the `Add Chart` button and select the metric you're interested in seeing over time across experiments.
![image](https://user-images.githubusercontent.com/24228106/56238110-a949fe80-605b-11e9-8217-f95c9cef8e87.png)

2) If you're just trying to compare two different experiments, you can also select those experiments (using the checkboxes) in the experiment table and select `diff` to see how the training graphs compare.

Let me know if those recommendations help!

**Comment by ceyzaguirre4** [comment]
I would like to compare two "sets" of experiments side by side.
What you propose is a posible solution, but it can be dificult to distinguish which lines correspond to which models.
For instance:
- If I want to compare a baseline model to my implementation it would be useful to have the chart you propose for the baseline on the left, and the one of my implementation on the right. this is necesary when each model is trained multiple times, as it can be difficult to distinguish amongst many lines in one chart

**Comment by dsblank** [comment]
We are exploring a solution to this.

**Comment by dsblank** [comment]
Stay tuned... solution is being tested!

**Comment by Nimrod007** [comment]
this can be done with comet panels https://www.comet.ml/docs/user-interface/panels/
each panel has its own query
