### ISSUE TITLE
Nothing is being logged!

### ISSUE THREAD

**Issue by tshrjn** [comet-ml/issue-tracking#251]
![Nothing is being logged](https://i.ibb.co/9tCSwcr/Screen-Shot-2019-04-16-at-6-49-50-PM.png)
Nothing is being logged on the comet dashboard since today morning.
I even tried the MNIST example script in the comet docs.

**Comment by amitfishy** [comment]
It seems that after the update comet-ml-1.0.51 is not uploading anything for me as well. Code that was working earlier is not working now.

**Comment by Nimrod007** [comment]
Hi @tshrjn @amitfishy , we had a data delay in our backend, data was not showing in the UI. should have been resolved by now and all your experiments will show data. please re-open if needed
