### ISSUE TITLE
Add scatter plots

### ISSUE THREAD

**Issue by miquelmarti** [comet-ml/issue-tracking#252]
I would like to have scatter plots (2d AND 3d, third dim with color is fine). My use case is to plot parameter values vs metric across different experiments, mainly for visualising results of hyper-parameter search. I think this would be a quite commonly used visualization, but I'm sure there are many other uses.

There is an open issue mentioning scatter plots: https://github.com/comet-ml/issue-tracking/issues/99

**Comment by dsblank** [comment]
@miquelmarti We are looking into this.

**Comment by dsblank** [comment]
We are developing a solution for this.

**Comment by dsblank** [comment]
There is now a scatter plot available in the Project level view. Further enhancements are in development.
