### ISSUE TITLE
Delete all experiments in archive button

### ISSUE THREAD

**Issue by pierthodo** [comet-ml/issue-tracking#253]
When I have a lot of experiments it can be tedious to delete 1 page of experiments at a time. It would be easier if there was a delete all archived experiment.

**Comment by dsblank** [comment]
As a workaround, did you know you can set the visible experiments on a page to 100, and thus archive 100 at a time? Setting is at bottom of table. By the way, how many experiments do you typically have in a project?

**Comment by dsblank** [comment]
I believe that this is now fixed, as you can select all experiments (even ones not on the page). Please reopen if this issue is not resolved.

**Comment by perceptualrobots** [comment]
How do you select all experiments (even ones not on the page)?
