### ISSUE TITLE
Changing layout when adding new columns to project

### ISSUE THREAD

**Issue by backpropper** [comet-ml/issue-tracking#254]
1. There seems to be a bug when I add a new column to a saved view which messes up the whole order of the columns.
2. It would be nice to be able to arrange the column order (in the add column dialog box)

**Comment by backpropper** [comment]
Any updates on this?

**Comment by gidim** [comment]
@backpropper  - are you still seeing issues with #1?

**Comment by backpropper** [comment]
I'm not sure if it that's issue you wanted to link but seems it's doing fine now.

**Comment by gidim** [comment]
ah it was supposed to be item number one in your first message. Closing this
