### ISSUE TITLE
Metrics Not Loading for experiment - through website and API

### ISSUE THREAD

**Issue by KaleabTessera** [comet-ml/issue-tracking#256]
Metrics aren't loading for any experiments. This started about an hour ago (4:30 pm SAST).

It doesn't work through the front-end: 
![image](https://user-images.githubusercontent.com/10942061/56594752-b16ee480-65ed-11e9-84f9-430cbed5ae12.png)

It also doesn't work through API, using the `.metrics_raw` function on an experiment.

**Comment by KaleabTessera** [comment]
This is only with older experiments, I can access data from new experiments.

**Comment by ceceshao1** [comment]
Hi @KaleabTessera - we've pushed a number of fixes that should have resolved this issue. Can you please confirm whether you can see your older experiment metrics now?

**Comment by KaleabTessera** [comment]
This has been fixed, thanks!
