### ISSUE TITLE
Per-experiment 'System Metrics' seem like 'System Parameters'?

### ISSUE THREAD

**Issue by PhilMiller** [comet-ml/issue-tracking#258]
<img width="945" alt="Screen Shot 2019-04-26 at 4 32 08 PM" src="https://user-images.githubusercontent.com/126464/56834971-f048a880-6840-11e9-9090-aafc55c6d0de.png">

These are all things that are fixed for the individual experiment, not things that evolve over time. That seems to fit your use of 'parameter' better than 'metric'

**Comment by dsblank** [comment]
@PhilMiller Perhaps. But also on this tab appear GPU percentage usage and GPU memory usage, which can change over the course of the experiment. Think of these other "system metrics" as slowly changing over the course of your life :) Also, we think of parameters as items that you set dynamically, and metrics are items that are measured or queried. Perhaps a better name is "System Information and System Metrics" but that is too long. Thank you for your note... we think a lot about things like this too!
