### ISSUE TITLE
Record exit code of experiment process, other failure data

### ISSUE THREAD

**Issue by PhilMiller** [comet-ml/issue-tracking#259]
If an experiment crashes or otherwise exits abnormally, it would be useful to see that listed. Besides the expected process exit code or received signal, it would be great to record a stack trace on failures where possible.

**Comment by dsblank** [comment]
I believe that we catch all of the exceptions that we can. Are you using `COMET_LOGGING_FILE` and `COMET_LOGGING_FILE_LEVEL`? See https://www.comet.ml/docs/python-sdk/advanced/#python-configuration for more information.
