### ISSUE TITLE
Unable to use Pytorch's Bottleneck util with Comet

### ISSUE THREAD

**Issue by tshrjn** [comet-ml/issue-tracking#261]
Comet needs to imported before pytorch and other packages so that it can start tracking, however, for utilities like pytorch's [bottleneck](https://pytorch.org/docs/stable/bottleneck.html) which runs the library module as a script like `python -m torch.utils.bottleneck /path/to/source/script.py [args]` we get the error:
```
ImportError: You must import Comet before these modules: torch
```

Is there a way around it?

**Comment by dsblank** [comment]
@tshrjn Interesting problem. We're looking into a solution.

**Comment by dsblank** [comment]
We are now testing a solution.

**Comment by dsblank** [comment]
This is scheduled to be released in comet_ml version 2.0.8 which should be released in the next week or so.

**Comment by mrartemev** [comment]
Just got the same problem with version `3.1.12`

```ImportError: You must import Comet before these modules: torch```

**Comment by Lothiraldan** [comment]
If anyone has the same issue, instead of running `python -m torch.utils.bottleneck ...` or `python -m torch.distributed.launch ...`, you can run `comet python -m torch.utils.bottleneck ...` or `comet python -m torch.distributed.launch ...`
