### ISSUE TITLE
Some metrics cut off from early in run

### ISSUE THREAD

**Issue by PhilMiller** [comet-ml/issue-tracking#262]
I have a long-running experiment that's steadily reporting metric values.

Charts of metrics visible in charts that I had open while it's been running will only load values up to some early point in the run, say up to step ~15,000, while other charts added later will load values up to the current step 4.8 million.

Names of metrics seemingly affected in the referenced experiment:
* step
* nplive
* npdead
* nparraylength

![Screen Shot 2019-05-02 at 10 18 53 AM](https://user-images.githubusercontent.com/126464/57082577-fddcb300-6cc4-11e9-8065-6954d265bdce.png)

**Comment by Nimrod007** [comment]
Hi @PhilMiller , when you refresh the page, do all charts get updated ? or some chart are missing data from some step ?

**Comment by PhilMiller** [comment]
It's durable, even after loading the page afresh, two weeks later.

Have a look at my experiment b79ec7c1450f499e98dcb16c2f146ee5

**Comment by Nimrod007** [comment]
from our records the last reported step for `nplive` is `7924` 
are you sure this metric is reported every step ? or after that step ?

**Comment by PhilMiller** [comment]
I'm pretty sure it should have been, yeah. 

Is there a way I can manually dump the metrics that were captured, to see which ones end at what step? Would I need to code something against the API to do that?

**Comment by Nimrod007** [comment]
yes, you can use the api to get all metrics back with steps:
https://www.comet.ml/docs/python-sdk/API/#apiget_experiment_metrics_raw

**Comment by PhilMiller** [comment]
I'm not particularly interested in seeing these particular values - this is all prototyping use of Comet.ml anyway. This really looked like something went wrong between my job and the service, though.

**Comment by Nimrod007** [comment]
might be we had a network issue or something went wrong. 
but from our logging everything looks normal.
if you can run the same flow again it would be great (since it might recreate the issue)
if thats not possible ill close for now
