### ISSUE TITLE
Customized columns are reset when refreshing site

### ISSUE THREAD

**Issue by HOMyklebust** [comet-ml/issue-tracking#263]
When I try to add custom columns in my project dashboard they appear just as expected. When I refresh the site again, however, the column is gone. I use the free version.

**Comment by ceceshao1** [comment]
Hello @HOMyklebust - have you saved the view? Saving the view will save the state of your custom columns, project visualizations, and queries.

See the screenshot for reference on where the `Save View` option is:
![ceceshao1_mnist-classification__Using_Keras](https://user-images.githubusercontent.com/24228106/57234576-f3852680-6fee-11e9-9fe2-24a865ac757f.png)

**Comment by dsblank** [comment]
@HOMyklebust You should now find the UX much better at temporarily remembering changes, and easier to save them. Please let us know how you find the new interface. Thanks for reporting!
