### ISSUE TITLE
Chart/drop down shifts when clicking drop down menu

### ISSUE THREAD

**Issue by ballcap231** [comet-ml/issue-tracking#265]
Original
![image](https://user-images.githubusercontent.com/40708323/57950977-72f7dd00-78ae-11e9-952e-da30a255cc0d.png)

After clicking drop down menu of 2nd chart:

![image](https://user-images.githubusercontent.com/40708323/57950989-7be8ae80-78ae-11e9-84a4-846fca740849.png)

**Comment by dsblank** [comment]
@ballcap231 Do you still see this issue?

**Comment by dsblank** [comment]
I believe that all issue related to this problem have been addressed. Please reopen and describe if you have any questions or issues. Thanks for reporting!
