### ISSUE TITLE
Zombie experiments in web UI

### ISSUE THREAD

**Issue by PhilMiller** [comet-ml/issue-tracking#267]
![Screen Shot 2019-05-22 at 5 29 24 PM](https://user-images.githubusercontent.com/126464/58210386-40d3ea00-7cb7-11e9-8efd-b70c04d22644.png)
These grey-blob lines are an enduring feature of my workspace, `philmiller/general`. I believe they result from a strange network pathology in which the experiment process's initial HTTPS connection succeeds, but the subsequent WebSocket connection does not, and so no metrics at all get reported.

Pending experiments should perhaps expire after a time-out, or otherwise not permanently clutter the usefully recorded data.

**Comment by Nimrod007** [comment]
fixed.
