### ISSUE TITLE
Cannot catch Exception when no Internet connection

### ISSUE THREAD

**Issue by AntoinePrv** [comet-ml/issue-tracking#270]
Hello,

Comet-ml version 2.0.1

The motivation would be to be able to have something like:
```python
import comet_ml as comet

try:
    exp = comet.Experiment()
except [SomeConnectionException]:
    exp = comet.OfflineExperiement("/somedir")
```

But the following does not execute the `except section` (`caught == False`):
```python
import comet_ml as comet

try:
    exp = comet.Experiment()
    caught = False
except Exception:
    caught = True
```

Even with the not recommended bare `except:` does not work.

**Comment by gidim** [comment]
Hey @AntoinePrv  
Thanks for reporting. Are you trying to solve for the case where the connection drops after it was established or for cases it never was available?

**Comment by AntoinePrv** [comment]
Never available, so that I can dynamically choose between `Experiment` and `OfflineExperiment`.

For the moment however, I'm no longer relying on this that, as I realize I could get Internet access with an HTTP proxy.

**Comment by gidim** [comment]
The reason we don't raise an exception is that we never want to crash a user's training script. That's an early design decision that we made based on the fact that users move their workloads across clouds/machines. 

A simple workaround would look like this:
```
import comet_ml as comet

exp = comet.Experiment()
if not exp.alive:
    exp = comet.OfflineExperiement("/somedir")
```

closing this for now.
