### ISSUE TITLE
Allow Archiving Projects

### ISSUE THREAD

**Issue by ChrisCameron1** [comet-ml/issue-tracking#271]
This is a feature request for archiving projects. There seems to be no way to archive projects. Projects can be deleted but but there is no way to keep old projects around without cluttering the workspace. I would also be satisfied if there was a way to group projects together or sort/rearrange them.

**Comment by dsblank** [comment]
Please checkout the latest UI changes. On the main workspace page, there is now a list view that allows sorting by project names. You can now rename a Project so that it sorts where you would like it.
