### ISSUE TITLE
Legend keys not working with experiment names

### ISSUE THREAD

**Issue by ChrisCameron1** [comet-ml/issue-tracking#273]
The legend keys often show up as experiment keys after I change to experiment names in the drop down menu. It sometimes works as expected but usually not. See example in attached image where one experiment is labelled by name and the other labelled by key.
<img width="248" alt="Screen Shot 2019-06-21 at 4 34 38 PM" src="https://user-images.githubusercontent.com/5004239/59956031-81538e80-9442-11e9-93ab-879ce32eda09.png">

**Comment by gidim** [comment]
Under development thanks for reporting.

**Comment by dsblank** [comment]
Do you still see this issue?
