### ISSUE TITLE
Graphs are messed up when metric name is too long

### ISSUE THREAD

**Issue by backpropper** [comet-ml/issue-tracking#275]
The legend overlaps with the graph.

<img width="520" alt="Screen Shot 2019-07-11 at 5 01 10 PM" src="https://user-images.githubusercontent.com/5422228/61085130-8aaa9800-a3fd-11e9-8317-b43d9ff7f7bf.png">

**Comment by dsblank** [comment]
We're working on a solution.

**Comment by dsblank** [comment]
Thanks! This should now be fixed. Let us know if you have any additional comments or questions.
