### ISSUE TITLE
Colors of loss and val_loss reversing

### ISSUE THREAD

**Issue by kdmcdrm** [comet-ml/issue-tracking#277]
I'm running an experiment and finding that the colors of the loss and val_loss curves are reversing for each iteration of the network.

Here are examples, these are moment apart from the view of a single experiment that is running in a Jupyter notebook.

![val_loss_orange](https://user-images.githubusercontent.com/5034163/62311275-db903800-b461-11e9-8a3c-2c361ddf3eb4.png)

![val_loss_blue](https://user-images.githubusercontent.com/5034163/62311284-de8b2880-b461-11e9-8376-e7c11a7c7527.png)

**Comment by gidim** [comment]
Under development. Thanks for reporting

**Comment by dsblank** [comment]
Do you still see this issue?

**Comment by kdmcdrm** [comment]
No, haven't seen it recently.

**Comment by dsblank** [comment]
Great to hear! Let us know if you have any other issues or questions.
