### ISSUE TITLE
Native cross-validation support

### ISSUE THREAD

**Issue by bednarrski** [comet-ml/issue-tracking#28]
In the current version of Comet during the experiment it is possible to log metrics split into steps (of iterations through a dataset) and epochs.

It could be useful to have a third layer of hierarchy - folds. It would be useful to have overlapping charts plotted coming from different folds of cross-validation.

It can be overcome as separate experiments however in fact these are different folds of one experiment.

**Comment by Nimrod007** [comment]
hi @bednarrski - have you considered using context ? 
https://www.comet.ml/docs/python-sdk/keras/#context-manager-traintestvalidate

**Comment by bednarrski** [comment]
Hi @Nimrod007, in fact the context doesn't help a lot when doing cross validation. Every fold is a 'separate' experiment with training and testing phase. It would be helpful to have possibility to keep the metrics together in one experiment but split into different folds.

**Comment by gidim** [comment]
Hi @bednarrski,
That's a good point. We're looking into adding another level of hierarchy in the form of "grouping".
For example you'll report 10 experiments (one for each fold) and then group them in the table by some key.

Would that be a sufficient solution for your use case?

**Comment by bednarrski** [comment]
Hi @gidim, That would be exactly what I need! Is this a plan for some nearest future?

Thanks!

**Comment by ceceshao1** [comment]
@bednarrski - thanks for suggesting this! We're making quick progress on the grouping feature for this month! I sent you an email asking if you're available for some quick user feedback around this feature - looking forward to your response 👍

**Comment by ceceshao1** [comment]
**Update on this issue:** We've pushed our new grouping feature that covers this request. You can log custom IDs via `log_other`then group by that value in a column! 

We'll be closing this issue, but can re-open if needed.

**Feedback and questions always appreciated on our [Slack channel](https://join.slack.com/t/cometml/shared_invite/enQtMzM0OTMwNTQ0Mjc5LTM4ZDViODkyYTlmMTVlNWY0NzFjNGQ5Y2Q1Y2EwMjQ5MzQ4YmI2YjhmZTY3YmYxYTYxYTNkYzM4NjgxZmJjMDI)**

> Pinged you via email @bednarrski !

**Comment by leej35** [comment]
Question: How can we get the average (or min/max) value of a  group-by column?

Even after group by, it seems there is no way to get averaged/min/max value of a column.

**Comment by gidim** [comment]
@leej35  - the GroupBy column does not currently support aggregates.
