### ISSUE TITLE
Have the REST API asset upload endpoint return the asset UID

### ISSUE THREAD

**Issue by zwade** [comet-ml/issue-tracking#280]
The return value from the `/rest/v1/write/upload-asset` endpoint currently returns 

```
{
  "msg":"saved"
}
```

Returning the asset ID would save us a round trip.

**Comment by zwade** [comment]
Hmm, it looks like this has actually been changed in the week or so since I tried. However the docs themselves still report the old response. 

Thanks!

**Comment by dsblank** [comment]
Thanks for the note! Will update docs.

**Comment by gidim** [comment]
@dsblank please close this once docs are updated.
