### ISSUE TITLE
Add support for setting tags via the Rest API

### ISSUE THREAD

**Issue by zwade** [comet-ml/issue-tracking#281]
The Python SDK has support for setting tags on experiments, however I could not find a similar method from the Rest API. Currently we have a workaround that involves using the Python SDK, but it would be much more convenient to do it from the Rest API.

**Comment by dsblank** [comment]
Yes, you are right. Currently you have to create an ExistingExperiment() and then add the tag that way. That is a fairly heavy procedure. We'll look into what you suggest.

**Comment by dsblank** [comment]
(Alternative way, FYI: you can easily tag experiments in the UI on the experiment's webpage.)

**Comment by gidim** [comment]
@zwade  - under development

**Comment by dsblank** [comment]
@zwade You'll find a new function in comet_ml version 2.0.9 `API.add_experiment_tags(experiment_key, list_of_tags)` Let us know if you have any questions. Thanks for the idea!

**Comment by dsblank** [comment]
And details for the REST API:

## Add Tags
POST
url: `www.comet.ml/api/rest/v1/write/add-tags-to-experiment`
request:
```
{
  "experimentKey": "someExperimentKey"
  "addedTags": ["someTag", "anotherTag]
}
```
response:
```
{
  "msg": "saved"
}
```

**Comment by zwade** [comment]
Thanks so much for this! Sorry for the delay, I haven't been monitoring github recently.
