### ISSUE TITLE
[Bug] - Filters tend to sporadically not work

### ISSUE THREAD

**Issue by KaleabTessera** [comet-ml/issue-tracking#284]
When applying filters on the experiment page, sometimes they don't work. This isn't always the case, but it happens sporadically. 

Example:
![image](https://user-images.githubusercontent.com/10942061/62620896-c5c7ba80-b91a-11e9-966c-8678db43f613.png)

**Comment by KaleabTessera** [comment]
Once I start to chain filters, it appers to work.

**Comment by neighthan** [comment]
I've been seeing this too. As a workaround, I think refreshing the page has always fixed it for me (so that the filters are properly applied).

**Comment by KaleabTessera** [comment]
@neighthan I have tried that and it works sometimes, other times not. I think it is some sort of race condition.

**Comment by gidim** [comment]
Thanks for reporting. Looking into this.

**Comment by gidim** [comment]
@KaleabTessera  - still under development

**Comment by KaleabTessera** [comment]
@gidim Any news on this?

**Comment by gidim** [comment]
@KaleabTessera are you still encountering this? If so can you share more information  - any specific filters? is there anything else with your view that we should know about?
Feel free to send to support@comet.ml if that's easier

**Comment by KaleabTessera** [comment]
Yep, this is still an issue. I have send an email to support@comet.ml, with a screen recording.

**Comment by ferc** [comment]
@KaleabTessera it's fixed in the latest UI version (`5.10.204`), thanks for reporting this and for the screen recording, it was very useful

**Comment by lemairecarl** [comment]
I seem to be encountering a similar issue. The project is `lemairecarl/jobml`

![Screenshot from 2020-12-04 18-17-27](https://user-images.githubusercontent.com/13444373/101224666-502e4480-365d-11eb-8a41-c71a4dec71d4.png)
