### ISSUE TITLE
Experiments page crashes

### ISSUE THREAD

**Issue by 10zinten** [comet-ml/issue-tracking#285]
I can not view the experiments pages. Here is screenshot of the error page

![cometml_error](https://user-images.githubusercontent.com/16164304/62681630-c2decf80-b9d7-11e9-872b-e91d57357373.png)

User ID: 10zinten

**Comment by gidim** [comment]
Hi @10zinten  - we are aware and working on an immediate fix.

**Comment by dsblank** [comment]
@10zinten Is this resolved for you?

**Comment by 10zinten** [comment]
Yes, I guess this issue is due to not saving the view. I have created a new project and started saving the view whenever I made some changes.

**Comment by dsblank** [comment]
Great that you figured it out. Thanks for the update!
