### ISSUE TITLE
Output Tab Broken

### ISSUE THREAD

**Issue by jwfromm** [comet-ml/issue-tracking#29]
As of this morning, it looks like the output tab of experiments has been changed to a black background. That's all well and good, however, when monitoring a live experiment, the screen flashes very quickly, making it unreadable. Attached is a quick video showing the issue.

![comet_flash](https://user-images.githubusercontent.com/9874242/39139666-60ec5190-46d7-11e8-8b35-8a7af0dc1a3c.gif)

**Comment by Nimrod007** [comment]
Hi @jwfromm - we did introduce changes in the output tab (to boost performance)
can you please try again and verify issue is resolved ?

if so please close.

**Comment by jwfromm** [comment]
Looks much better now, thanks!
