### ISSUE TITLE
Sending Stop signal from the project page

### ISSUE THREAD

**Issue by backpropper** [comet-ml/issue-tracking#290]
Can you please add a stop button next to the show/hide/archive... buttons which stops the selected experiment(s)?

**Comment by gidim** [comment]
Thanks for the feedback!
We will be moving a lot of the actions (move, delete, show etc)to an "Action" dropdown menu. Once we built that we can add stop as well. Right now we don't want to overwhelm the UI

**Comment by backpropper** [comment]
I think adding just a stop button won't overwhelm the UI since it makes sense to put it next to those buttons
