### ISSUE TITLE
timer to manually control auto refreshing

### ISSUE THREAD

**Issue by backpropper** [comet-ml/issue-tracking#291]
It would be great to have a manually controlled timer for auto-refreshing page or for a start just an on/off button that toggles the setting

**Comment by gidim** [comment]
Hi @backpropper  - can you share what's the pain point you're trying to solve with this?

**Comment by backpropper** [comment]
Its just that there is often a lag when the exp refreshes since it renders everything again, which makes the web page unresponsive for a while. Adding this feature, would solve this issue because may a times you're just looking at the graphs for analyzing and dont want them to refresh.

**Comment by gidim** [comment]
@backpropper  - closing this as we added support to turn off auto refresh or manually refresh
