### ISSUE TITLE
How to continue an OfflineExperiment?

### ISSUE THREAD

**Issue by vict0rsch** [comet-ml/issue-tracking#292]
Looking at the documentation from ExistingExperiment, I don't understand how it would be possible to continue one that is not on comet.ml, rather on my filesystem

**Comment by dsblank** [comment]
@vict0rsch Do you mean use an ExistingExperiment() after an OfflineExperiment()? Currently, ExistingExperiment() only picks up experiments that have been uploaded, or run live. Did I understand your question correctly?

**Comment by dsblank** [comment]
@vict0rsch Is there a reason you can't upload the OfflineExperiment before continuing?

**Comment by vict0rsch** [comment]
Either ExistingExperiment after OfflineExperiment, or OfflineExperiment picking up existing data if there's already one in the offline_dir for instance.

The problem I'm facing is the following:

* I work on a slurm-based cluster
* Compute nodes don't have an internet access
* Job may be killed at any point in the code
* Workarounds:
  * (Create an experiment at the beginning of training)
  * Dump OfflineExperiment at the end of every epoch
    * **not possible** to dump the OfflineExperiment without ending it
  * Ending the experiment at the end of an epoch, picking it up at the beginning of the next one
    * **not possible** to pick up (=continue) the OfflineExperiment

**Comment by dsblank** [comment]
Thanks for explaining your use-case. Let me get back to you on possible solutions...

**Comment by dsblank** [comment]
You should be able to "continue" an `ExistingExperiment` in a way:

1. `experiment = ExistingExperiment()`
2. Log additional items
3. `experiment.end()`
4. Go to step 1

**Comment by dsblank** [comment]
Please let us know if you have any additional questions.
