### ISSUE TITLE
Git is not detected if scripts run in a different cwd

### ISSUE THREAD

**Issue by timaebi** [comet-ml/issue-tracking#293]
I have a git repository with my python code. In my setup I run the scripts with a working directory outside the git repository.

Unfortunately the `comet_ml.Experiment` class is unable to detect the git repository in the `set_git_metadata` method.

I see two solutions to this:

1. make the path to the git repository configurable
2. or better resolve the git path relative to the currently executing file as resolved in `_get_filename`. For Jupyter environments the solution can still fall back to the current working directory.

Am I correct that there is no public github repo with the python-sdk? If yes, I would be happy to create a PR for that.

**Comment by dsblank** [comment]
@timaebi Thanks for the interesting suggestion! Let us explore this idea.

**Comment by timaebi** [comment]
Any plans whether and when this will be solved? I would really like to make use of the git integration feature. If you don't plan to fix it in the near future, I will adjust my scripts such that I can call them with a cwd which is under git version control.

**Comment by dsblank** [comment]
Testing possible solutions...

**Comment by dsblank** [comment]
This has not been implemented in comet_ml version 3.1.3. See https://www.comet.ml/docs/python-sdk/releases/#release-313 for more information. Thanks for the suggestion!
