### ISSUE TITLE
Feature request: view yaml / json assets in UI

### ISSUE THREAD

**Issue by dsblank** [comet-ml/issue-tracking#294]
By Yifan Gu in slack.

**Comment by gyf304** [comment]
There's already a preview feature. It would be nice to have the content of YAML / txt / JSON, or other plain text assets viewable in the web UI.

**Comment by sebamenabar** [comment]
+1, also .txt, .log, would be very useful since current hyperparameters tab does not work well with anidation

**Comment by dsblank** [comment]
`.txt`, `.yaml`, and `.json` are now displayed in the Assets Tab. Here is the fill list of extensions:

Extension | Meaning
------------- | ----------------
  'txt' | Text
  'log' | Log File
  'yaml' or 'yml' | YAML File
  'json' | JSON
  'js', | JavaScript
  'py' | Python
  'csv' | Comma-Separate Value
  'tsv' | Tab-Separated Value
  'md' | Markdown
  'rst' | Rust
