### ISSUE TITLE
Tensorflow 2.0 support

### ISSUE THREAD

**Issue by paulang22** [comet-ml/issue-tracking#296]
Hi, 
I am just checking if Tensorflow 2.0 is officially supported by comet-ml?
Thanks.

**Comment by dsblank** [comment]
@paulang22 comet_ml release 2.0.10 introduced support for tensorflow 2.0 using v1 compatibility, and comet_ml release 2.0.12 (to be released this week) will introduce support for tensorflow 2.0 using v2. Would you be willing to try it out when ready?

**Comment by dsblank** [comment]
@paulang22 We released comet_ml 2.0.12 today introducing tensorflow v2 compatibility with our auto loggers. Please try it out and let us know how it works for you. Note that it also has support for summary histogram logging. I'll post back here when that is ready at comet.ml.

**Comment by dsblank** [comment]
New histograms for time series are now available on comet_ml. Release notes for 2.0.12 will appear here shortly: https://www.comet.ml/docs/python-sdk/releases/#release-2012

**Comment by paulang22** [comment]
Thanks, @dsblank . I will give it a go soon.

**Comment by paulang22** [comment]
@dsblank , I am having the same error from the previous comet_ml's version.
`ValueError: You tried to call `count_params` on vg_g16unet, but the layer isn't built. You can build it manually via: `vg_g16unet.build(batch_input_shape)`.`

vg_g16unet is a custom model built by subclassing the keras model class.

**Comment by dsblank** [comment]
@paulang22 I believe that the two messages are unrelated; I think that there are two issues:

1. not being able to log the graph (which isn't supported directly in TF2 I believe)
2. not having built the the layer

It sounds like you fixed the second. The first may require that you manually figure out how to get the graph in the new tensorflow, and log it: https://www.comet.ml/docs/python-sdk/Experiment/#experimentset_model_graph

It sounds like your code is actually doing everything else correctly, such as logging metrics and parameters? If not, can you send me a Comet debug file? See: https://www.comet.ml/docs/python-sdk/advanced/#trouble-shooting

support@comet.ml

**Comment by dsblank** [comment]
@paulang22 Any update?

**Comment by dsblank** [comment]
Closed due to inactivity.
