### ISSUE TITLE
[UI] Better code highlighting in the code tab

### ISSUE THREAD

**Issue by lleewwiiss** [comet-ml/issue-tracking#299]
The current code tab makes reading through your code quite difficult due to lack of contrast and highlighting, I understand code themes are subjective but something slightly more than what is now would be greatly appreciated.

**Comment by dsblank** [comment]
Hello @lleewwiiss ! You should see some highlighting in the Code tab. Here is what a section looks like in my browser:

![Screenshot from 2019-09-06 01-24-54](https://user-images.githubusercontent.com/168568/64403107-5f32db00-d045-11e9-843f-f44e106d9860.png)

Does yours look different? Even so, it would be nice to have user-selectable colors or a theme for this tab.

**Comment by lleewwiiss** [comment]
Looks the same to me, but not having the function calls highlighted makes all the text just seem as one in a large block of code

**Comment by dsblank** [comment]
Adding to wish list; thanks for reporting!
