### ISSUE TITLE
[UI] Add more detailed tags to graph point overlay

### ISSUE THREAD

**Issue by lleewwiiss** [comet-ml/issue-tracking#300]
It would be very handy to have tensorboard like tags for graph points on the dashboard. Currently, the dashboard will show just the value when you hover over a point but it would be great to have something like this (black box with point information):

![alt text](https://www.tensorflow.org/images/mnist_tensorboard.png  "tboard")

Being able to see the exact step would be very useful as currently visually interpolating it can be tricky, especially when comparing different lines on a graph which may not produce a point at the same time/step.

**Comment by gidim** [comment]
Hi @lleewwiiss - just to clarify -> do you want something like the blackbox to show on hover? or there's something else that caused it to pop?

**Comment by lleewwiiss** [comment]
Yeah on hover, similar to what happens now, just with more details

**Comment by gidim** [comment]
Got it. Thanks for the feedback we will look into it!

**Comment by dsblank** [comment]
@lleewwiiss Please see our latest enhancements to our built-in panels in regards to hover, click, and double-click.
