### ISSUE TITLE
Import order shouldn't matter

### ISSUE THREAD

**Issue by jaklan** [comet-ml/issue-tracking#301]
Hi,

as we can see in docs:

> Comet.ml will not interfere with your run, unless you attempt to use one of the auto logging Python libraries, but you have imported comet_ml after the library. For example:
```
import tensorflow
import comet_ml

experiment = comet_ml.Experiment()
```
> When you create an Experiment then you will get an ImportError. To fix, simply move the import comet_ml above the other import statement.

What's the problem with that solution? It's an anti-pattern. The following statement covers it pretty well:
> Technically, changing import order could change behavior, because modules can have initialization code that runs when they are first imported. If that initialization code has side effects it's possible for modules to have interactions with each other. However, this would be a design flaw in those modules. Import order is not supposed to matter, so initialization code should also be written to not depend on any particular ordering.

One thing - It's directly related to Python Zen & _Explicit is better than implicit_. But another, more practical - with such an approach, tools like isort could create serious mess (and they're quite often used in some automated way, e.g. via git hooks).

I guess it's something you've already thought about and it's hard to advise how to preserve auto-logging "magic" without such dirty hacks, because obviously we don't know implementation details behind that. But if you at least share with us the idea of how it works under the hood, then maybe we could potentially help with making it a bit more pythonic and error-proof ;) Anyway, it would be valuable to not let it be as it is.

**Comment by Nimrod007** [comment]
Hi @jaklan, Thanks for sharing this feedback. comet is a python package and you can take a look at its content to understand whats going on or how the "magic" works.

We will take this into consideration when we work on our `v2` package.
