### ISSUE TITLE
COMET WARNING: Failed to save keras graph model

### ISSUE THREAD

**Issue by alberduris** [comet-ml/issue-tracking#304]
CometML version: 2.0.13
Keras version: 2.2.4
Tensorflow version: 1.14.0

I have run an Experiment with this Keras model:

```
class CustomModel:

    def __init__(self):
        self.backend = "keras"
        self.model = None
        self.embed = hub.Module("https://tfhub.dev/google/nnlm-es-dim128-with-normalization/1", trainable=False)

    def _NNLMEmbedding(self, x):
        return self.embed(tf.squeeze(tf.cast(x, tf.string)), signature="default")

    def build_model(self, args, data_holder, verbose=False):
        """
        Build the Keras prediction model.
        :param verbose:
        """
        print('Building model...')
        inp = Input(shape=(None,), dtype=tf.string)

        x = NNLMLayer(output_dim=(128,), name="Custom_NNLMLayer")(inp)

        dense = Dense(128, activation='relu')(x)
        outp = Dense(data_holder.num_classes, activation="sigmoid")(dense)

        adam = Adam(lr=args.learning_rate)

        self.model = Model(inputs=inp, outputs=outp)
        self.model.compile(loss='binary_crossentropy',
                           optimizer=adam,
                           metrics=['accuracy'])
        if verbose:
            self.model.summary()

```

And it seems that Comet have failed to automatically save the graph model.

```
COMET WARNING: Failed to save keras graph model
```
It works fine with other models though, so it may be something related with the model definition itself.

**Comment by dsblank** [comment]
What versions of `comet_ml`, `tensorflow`, and `keras` are you using?

**Comment by alberduris** [comment]
> What versions of `comet_ml`, `tensorflow`, and `keras` are you using?

Thanks for the quick reply, just updated the issue.

CometML version: 2.0.13
Keras version: 2.2.4
Tensorflow version: 1.14.0

**Comment by dsblank** [comment]
Interesting. You could see if you get an error if you attempt to manually get the graph, and then see what happens if you call `graph.to_json()` If that works, you can manually `experiment.set_model_graph(graph.to_json())`

**Comment by alberduris** [comment]
Yes! I tried that before (but with `to_yaml()`) and it worked.

To be precise, it worked when executing `experiment.set_model_graph(graph.to_yaml())` **before** the call to the fit function, if executed **after**, then it prompted a warning message telling that _it was already saved_, although it wasn't due to the previous warning (`COMET WARNING: Failed to save keras graph model`)

It's not a severe issue because it happens only with some models and there is a workaround, but would be great if we can find the cause. Please, count on me if you need something else to fix this issue.

**Comment by dsblank** [comment]
Excellent! Thanks for the details. We'll look at this and try to solve the underlying issue.

**Comment by dsblank** [comment]
@Lothiraldan This is the issue I mentioned in the issue tracker.

**Comment by Lothiraldan** [comment]
@alberduris Hello, thank you for your report. I'm not aware of any limitation of tensorflow `to_json` method.

Could you try running with debug logs by adding the following environment variables `env COMET_LOGGING_FILE_LEVEL=debug COMET_LOGGING_FILE=/tmp/comet.debug.log python script`? Then looks for a Traceback in the file `/tmp/comet.debug.log` or send us the the debug logs via Slack https://chat.comet.ml/.

**Comment by alberduris** [comment]
Hi @Lothiraldan 

Thank you very much for your answer. Since the problem arised several months ago, right now I can't reproduce the problem easily, so I won't be able to perform the running with debug logs, sorry about that.

If I came to this at some point in the future I will do it and let you know.

**Comment by dsblank** [comment]
@alberduris Thanks for the info. I think we have a solution for this in general, and you also can do the conversion yourself (as you discovered). I think you can also could also add methods to your class that would define `__repr__` or `__str__` to return the appropriate string, and that would have worked.

Closing this for now. Thanks again!
