### ISSUE TITLE
No axis labels or legend in exported line graph

### ISSUE THREAD

**Issue by kdmcdrm** [comet-ml/issue-tracking#305]
Hello,
This is hopefully a fairly minor change but I would like axis labels and legends for both the x and y axis for charts on both the top level project page and within experiments. The legend appears as sidebar in the online interface but does not get included in the export at all, making it very hard to include these plots in a report.

**Comment by kdmcdrm** [comment]
Writing to bump this. I notice the labels are actually missing for the plots on the web interface as well, this makes them nearly impossible to read, especially if you have multiple.

**Comment by dsblank** [comment]
@kdmcdrm Thanks! This is on our list, and should have something out soon to address this.

**Comment by nikvaessen** [comment]
Is there a solution yet?

**Comment by xylee95** [comment]
Following this issue as I'm also interested in having this feature!

**Comment by dsblank** [comment]
Engineering taking a look at this.
