### ISSUE TITLE
Sort project names naturally

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#308]
Natural sorting is the default sort used in a number of platforms (including Macbook filesystem). The sorting will handle the discrepancy between number and string sorting intuitively: 
https://stackoverflow.com/questions/4836710/does-python-have-a-built-in-function-for-string-natural-sort

**Comment by dsblank** [comment]
@PetrochukM Do you mean to suggest this in the web UI, in the Python SDK, or both?

**Comment by PetrochukM** [comment]
I was thinking about the web UI.
