### ISSUE TITLE
Experiment ends abruptly while training script is still running

### ISSUE THREAD

**Issue by mithun2595** [comet-ml/issue-tracking#31]
I log my experiments from a pod running on a cluster managed by kubernetes. I get the following error just before the dashboard says experiment ended. However, my training script is still running. I followed the guide to log metrics and I don't think there is a problem in that. Could you help me figure this out?  

`COMET ERROR: Streaming error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/comet_ml/comet.py", line 117, in _loop
    self.ws_connection.send(messages)
  File "/usr/local/lib/python3.5/dist-packages/comet_ml/connection.py", line 336, in send
    self._send(data)
  File "/usr/local/lib/python3.5/dist-packages/comet_ml/connection.py", line 364, in _send
    self.wait_for_connection()
  File "/usr/local/lib/python3.5/dist-packages/comet_ml/connection.py", line 384, in wait_for_connection
    "Could not connect to server after multiple tries. ")
ValueError: Could not connect to server after multiple tries.
`

**Comment by Nimrod007** [comment]
first thought is it looks like a network issue.
can you please try to re-run and see if problem still exist ?
if so please add your experiment key so I can take a look.

**Comment by dewalg** [comment]
Hey @Nimrod007 (i'm working with @mithun2595), this problem is still persisting and this time it didn't print any error. Does comet time out if nothing is reported for a couple minutes? We're using the tensorflow dataset API and when we shuffle our dataset it has to pause the training and build a shuffle buffer. Comet seems to have stopped the experiment when our training paused.

**Comment by jwfromm** [comment]
I'm seeing similar behavior when using pytorch. Although my training run continues fine locally, comet indicates the experiment has ended and stops updating with no error message.

**Comment by Nimrod007** [comment]
we have a heartbeat mechanism set to keep the UI updated if experiment is alive.

@jwfromm , @dewalg - after experiment finished running locally. can you go to the metric tab in the experiment or the chart tab. check if all data is there (all step exist for example)

if so i think the table view isn't updating correctly.

Thanks for the input

**Comment by dewalg** [comment]
Both the chart tab has incomplete data, and as for the metric it doesn't really show me any raw data. However, the metric tab does not include my validation metric that it was supposed to log so i assume it just was not uploaded. The experiment did end on comet ml before the log_metric command for the validation score in our code was reached. 

I don't believe its the table view that is the problem here. Is there any way a user could manually change the timeout?

**Comment by jwfromm** [comment]
For the case I mentioned, both the output and metrics stop updating along with the chart. As far as I can tell, there's no indication that the experiment continued running.

**Comment by jwfromm** [comment]
This might be the error that is causing these problems, just hit it on a run.
```
COMET ERROR: Streaming error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/comet_ml/comet.py", line 117, in _loop
    self.ws_connection.send(messages)
  File "/opt/conda/lib/python3.6/site-packages/comet_ml/connection.py", line 336, in send
    self._send(data)
  File "/opt/conda/lib/python3.6/site-packages/comet_ml/connection.py", line 364, in _send
    self.wait_for_connection()
  File "/opt/conda/lib/python3.6/site-packages/comet_ml/connection.py", line 384, in wait_for_connection
    "Could not connect to server after multiple tries. ")
ValueError: Could not connect to server after multiple tries.
```
The annoying part is this also stops the job as its a full error, it'd be nice if it could keep running and try again next iteration.

**Comment by gidim** [comment]
That's indeed annoying. We shouldn't blow up if we fail to connect.
It's taking a long time probably because it's trying to reconnect multiple times.

We're looking into this now and will release a new version that revisits this. Thanks for your feedback

**Comment by Nimrod007** [comment]
resolved on [![PyPI version](https://badge.fury.io/py/comet-ml.svg)](https://badge.fury.io/py/comet-ml)
