### ISSUE TITLE
Logging PyTorch Images

### ISSUE THREAD

**Issue by matthewpurri** [comet-ml/issue-tracking#310]
I am running some experiments using PyTorch library and wanted to log metrics as well as generated images. 

When attempting to log an image, I received the following error:
`COMET ERROR: Could not convert image_data into an image; ignored`

I am unable to log images if they are in the following format [channel, height, width], but logging works if the image is in [height, width, channel] format.  I believe that logging PyTorch tensors in the first format  should be the correct way because the [PyTorch developers designed the library to use the later format](https://discuss.pytorch.org/t/dimensions-of-an-input-image/19439).

To show proof I wrote some scrap code:

Failure:
```
from comet_ml import Experiment
import torch

logger = Experiment(api_key="VuSyZ3mBZyDrJ3jkMZuor1YAa",
                    project_name="trial", 
                    workspace="matthewpurri")

image = torch.zeros([3, 100, 100])

logger.log_image(image) . # Failure
```

Success:
```
from comet_ml import Experiment
import torch

logger = Experiment(api_key="VuSyZ3mBZyDrJ3jkMZuor1YAa",
                    project_name="trial", 
                    workspace="matthewpurri")

image = torch.zeros([100, 100, 3])

logger.log_image(image) . # Success
```

Library versions:
Pytorch          1.2.0
Comet ML     2.0.15

**Comment by dsblank** [comment]
Indeed, the shape of the array must be (width, height) or (width, height, channel). If your image isn't in that format, you can send in an `image_shape=(width, height, channel)` or just reformat the image.

**Comment by matthewpurri** [comment]
Thank you for the info!
