### ISSUE TITLE
Server_end_time on project page not matching Server_end_time on experiment page (wrong either way)

### ISSUE THREAD

**Issue by RhyanJohnson** [comet-ml/issue-tracking#311]
Note: my project + experiments are private.

When I am viewing an experiment [95eb3dd66ed94427a885aaae116059eb] as a row in my project [wellsaid-labs/0-stft-model-bases], I see a server_end_time of 10/31/19 10:11 PM:
<img width="814" alt="Screen Shot 2019-11-01 at 3 35 38 PM" src="https://user-images.githubusercontent.com/52676253/68060356-43eaf180-fcbd-11e9-893e-b8a713ce9f02.png">

When I open the experiment on its own, I see a server_end_time of 11/1/19 12:10 AM:
<img width="964" alt="Screen Shot 2019-11-01 at 3 27 11 PM" src="https://user-images.githubusercontent.com/52676253/68060067-16517880-fcbc-11e9-8f88-594c7ca24908.png">

That said, I also noticed that after a minute or so on the experiment page, the server_end_time goes back to saying 10/31/19 10:11 PM...

When I request the server_end_time from the REST API, I get 11/1/19 12:10 AM.

Finally, I expect the actual server_end_time to match last_message_time (which, at the time of this post is 11/1/19 03:34 PM). The experiment is currently running. So, neither of the times shown above are correct.

Thank you!

**Comment by dsblank** [comment]
Sounds like times on the server are in a different time zone from your local Python SDK. So, you'll probably want to adjust on your end. If you are using our server www.comet.ml then I'll have to check to see what we use. Each on onprem server will set its own timezone. 

Note that the Python API caches the results. If you are talking directly to the server via REST, they should be the same.

**Comment by dsblank** [comment]
Closing. Please feel free to ask more questions.
