### ISSUE TITLE
log_figure not working with empty subplot

### ISSUE THREAD

**Issue by V3RGANz** [comet-ml/issue-tracking#312]
let's write a simple code:

```
from matplotlib import pyplot as plt
from comet_ml import Experiment

experiment = Experiment(project_name="comet-bug")

fig, ax = plt.subplots(2)

ax[0].plot([1, 2, 3])

experiment.log_figure(figure=fig)
```
what I want to log: 

<img src="https://user-images.githubusercontent.com/14924440/68325779-28c41b80-00db-11ea-91d2-bf91cc7ffab9.png" width="400" height="350" />

what i get:

```
COMET WARNING: Refuse to upload empty figure, please call log_figure before calling show
COMET WARNING: Failing to save the matplotlib figure
```

I believe that fig.gca().has_data() is not the best way to determine the entire figure is empty, also I think there is should be a way to force log even an empty figure

**Comment by dsblank** [comment]
Thank you for the very nice repeatable error and hints! Reproduced, and we should have a fix out soon!

**Comment by dsblank** [comment]
Should be fixed. in comet_ml 2.0.17. Thanks for reporting!
