### ISSUE TITLE
Is there an example of using `Comet.ml` with `Tensorflow 2.0` and the `tf.keras` api?

### ISSUE THREAD

**Issue by 00krishna** [comet-ml/issue-tracking#316]
Hello, I was just wondering if anyone had a simple example of using `Comet.ml` with the `Tensorflow 2.0` and the `tf.keras` api? I know that the `tf.keras` api is a re-implementation of `Keras`, so I am not sure that the callbacks to `Comet` will work with same way. If anyone has even a minimal example to see how things are different that would really help. I just want to see what a working example looks like before starting to experiment with training pipeline. Thanks.

**Comment by dsblank** [comment]
Yes, the callbacks in keras with tensorflow 2.0 work in the same way. We have an extensive test matrix at Comet to test the different versions of tensorflow across different versions of Python. So, you don't need to do anything special or different. Once you have Comet configured, just inserting these two lines at the top is all that you need:

```python
from comet_ml import Experiment
experiment = Experiment()
```
Let us know if you have any questions or comments.

**Comment by dsblank** [comment]
Close. Please feel free to ask more questions.
