### ISSUE TITLE
How to de fine fit/train function in keras when using Comet.ml Hyperparameter Optimization serivice

### ISSUE THREAD

**Issue by s255298** [comet-ml/issue-tracking#317]
I could not find the methods to define fit function anywhere. Could you please give an example?

# define fit function here!

# Finally, get experiments, and train your models:
for experiment in opt.get_experiments():
    # Test the model
    loss = fit(experiment.get_parameter("x"))
    experiment.log_metric("loss", loss)

**Comment by dsblank** [comment]
@s255298 Sure! Are you using a particular machine learning framework, like keras or scipy? If so, then the fit function is usually just `model.fit()`. But in general, it is whatever function or code that gives you the value that you want to minimize or maximize.

**Comment by s255298** [comment]
Thank you so much. I am using keras. In Comet.ml Hyperparameter Optimization, arguments for fit function are hyperparameters:
      loss = fit(experiment.get_parameter("size"),
                 experiment.get_parameter("lr"))
However, in keras, the arguments do not include hyperameters except epoch and batch size.

When I using model.fit function directly, the results are: 

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "C:\AppData\Local\Programs\Python\Python35\lib\site-packages\comet_ml\monkey_patching.py", line 246, in wrapper
    return_value = original(*args, **kwargs)
  File "C:\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training.py", line 952, in fit
    batch_size=batch_size)
  File "C:\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "C:\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training_utils.py", line 92, in standardize_input_data
    data = [standardize_single_array(x) for x in data]
  File "C:\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training_utils.py", line 92, in <listcomp>
    data = [standardize_single_array(x) for x in data]
  File "C:\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training_utils.py", line 27, in standardize_single_array
    elif x.ndim == 1:
AttributeError: 'int' object has no attribute 'ndim'

**Comment by dsblank** [comment]
@s255298 My recommendation is to get your keras code working first. Then add the Optimizer to change whatever hyperparameters you wish as per the examples: https://development.comet.ml/docs/python-sdk/introduction-optimizer/

**Comment by s255298** [comment]
Yes. I followed the examples from https://www.comet.ml/docs/python-sdk/introduction-optimizer/. I could not define the fit function properly. Could you provide an example about defining the fit function because it is not given in the introduction or github examples. Thank you so much!

**Comment by dsblank** [comment]
The "fit function" is nothing more than what computes the "loss" (eg, error) for your model. Keras with Comet already automatically logs "loss", so you shouldn't really need to do anything more. Does that help?

**Comment by s255298** [comment]
Thank you for you patient answer. But my problem about fit function has not solved yet. I know the "fit"  in comet and model.fit() in keras  has the same function, but their arguments should be different. If  I use the model.fit() of keras  directly, errors as shown above would occur . And according to the the examples in introduction-optimizer, "fit function" in comet should be redefined.
  
![optimizer example](https://user-images.githubusercontent.com/42739520/69500521-e0d33000-0ef3-11ea-91d2-bd9d2ef2e651.PNG)

**Comment by dsblank** [comment]
@s255298 If you are using keras, then the loss metric is already being logged. Simply remove the lines in the for loop, and build your model and train it there. You don't need to do anything else!

**Comment by dsblank** [comment]
Closing. Please feel free to ask more questions.
