### ISSUE TITLE
What is the benefit of using Comet.ml Hyperparameter optimization versus say Tensorflow `Hparams`?

### ISSUE THREAD

**Issue by 00krishna** [comet-ml/issue-tracking#318]
I saw that Comet.ml has a hyperparameter tuning service with the paid subscription. But I was trying to find a feature comparison between using the Comet.ml service versus just using something like Tensorflow's `Hparams` package for hyperparameter optimization--and then logging those updates to Comet.ml?

I suppose both of these approaches will work, but one is free and one has a cost. So I just wanted to see what the added benefit is from paying the additional charge? Thanks.

**Comment by dsblank** [comment]
@00krishna I don't know tensorboard's hparam well enough to give a complete comparison, but I can mention some of the useful features of Comet's Optimizer (off the top of my head):

1. You can perform a sequential search, parallel search, or mix and match. 
2. Your runs can be on a single machine, or distributed.
3. You can choose between a variety of search algorithms, including grid, random, and bayes
4. If an experiment crashes, the server can send out the parameters again
5. You can ask for a number of trials for each parameter set (say, you want to do 10 trials of each combination, to make sure you get an appropriate measure)
6. Integrated with the rest of Comet. For example, you could do a "study" as a "project", or tag the experiments inside a project.
7. You can do a grid search, followed by a bayes search with more fine-grained ranges.
8.  Nothing additional to install or manage
9. All of the data necessary to replicate a search is saved with each experiment; even searches should be reproducible!
10.  Can be used with Experiment, or OfflineExperiment.
11. For easy use in deploying on a cluster or in parallel, use the `comet optimize` command line API
12. Has many additional controls such as max combinations, and grid size for setting the search resolution for each parameter

There are probably some additional things I forgot. How does that compare?

To read more see:

* https://www.comet.ml/docs/python-sdk/introduction-optimizer/
* https://www.comet.ml/docs/command-line/#comet-optimize

**Comment by dsblank** [comment]
Closing. Please feel free to ask more questions.

**Comment by 00krishna** [comment]
@drormoran I think this is easier to do through the deep learning libraries themselves. So I have been using Pytorch Lightning nowadays, and you can distribute parameter tuning over several machines using the Ray library. There is a plugin for using Ray with Pytorch Lightning, and it is as easy as just one line of code to train or tune over multiple machines.
