### ISSUE TITLE
Reproduce button doesn't support some branch names

### ISSUE THREAD

**Issue by awlego** [comet-ml/issue-tracking#319]
The experiment reproduce button does not track the git branch correctly if the branch name has a forward slash ('/') in it. For example, a branch named `awlego/comet_ml_test` would be converted to `comet_ml_test`. Both the link to the branch and the reproduction steps appear to not support this style of branch names.

**Comment by dsblank** [comment]
Thanks for reporting and providing detail about what is wrong. We'll take a look!

**Comment by dsblank** [comment]
Apparently, there is a git ambiguity when branch names have slashes in them. One can use the slash to mean a "local branch" or a regular branch name. See for example: https://stackoverflow.com/questions/2527355/using-the-slash-character-in-git-branch-name

Checking with our engineers to see if it makes a difference to us.
