### ISSUE TITLE
multiple select - on filter select all bug

### ISSUE THREAD

**Issue by Nimrod007** [comet-ml/issue-tracking#32]
in experiment table:
* filter 
* select all
* all experiment on page are selected
* expected only the filtered experiment to select.

![comet_ml___supercharging_machine_learning](https://user-images.githubusercontent.com/3535799/39196042-2ed32818-47af-11e8-9374-9dddaf97f134.png)

![comet_ml___supercharging_machine_learning](https://user-images.githubusercontent.com/3535799/39196080-4639f068-47af-11e8-9915-65562d58f24e.png)

**Comment by rememberlenny** [comment]
@Nimrod007 Issue identified and solution is being worked on.

**Comment by rememberlenny** [comment]
![2018-04-24 10_57_21](https://user-images.githubusercontent.com/1332366/39196229-92f923c4-47af-11e8-90e9-dea8246851fa.gif)

@Nimrod007 Solution was identified and being tested on staging.

**Comment by rememberlenny** [comment]
Fix is confirmed working on staging. Combining with next production release.

**Comment by rememberlenny** [comment]
Production deploy is up.
