### ISSUE TITLE
Chart colours used for lines should be the same for same experiments in visualization

### ISSUE THREAD

**Issue by karankurani** [comet-ml/issue-tracking#320]
Hi,

![Screenshot 2019-11-26 at 7 26 33 PM](https://user-images.githubusercontent.com/443145/69639543-b5328000-1082-11ea-9264-63388426a942.png)

As you can see from the image above. Its super confusing to see different colours across different charts because the colours clash and or are completely different. While visually comparing the various metrics its impossible to move quickly between charts. 

**Suggested fix - keep the line colours same for same experiments across all the rendered charts.**

**Comment by dsblank** [comment]
@karankurani If the automated color assignment system doesn't work like you want, you can always override an experiment's color. You can read more about that here:

* https://www.comet.ml/docs/user-interface/#experiment-table

**Comment by karankurani** [comment]
The problem is not the colour itself. If you see the image above - experiment #1 is green in graph on left, but experiment #1 is red in graph on right. 

Same issue for experiment #2. Its red on the left graph and green on the right graph. This problem happens only while diffing between two experiments.

**Comment by dsblank** [comment]
@karankurani Ok, thanks for the details. We'll look into that.

**Comment by gidim** [comment]
@karankurani  - do you mind sharing a link to the diff page? this is a bug

**Comment by karankurani** [comment]
Have sent the link to the email.

**Comment by gidim** [comment]
thanks. will review
ᐧ

**Comment by dsblank** [comment]
@karankurani Please see our latest enhancements for these project built-in panels. It should be the case now that an experiment will always have the same color.
