### ISSUE TITLE
NameError: name 'fit' is not defined

### ISSUE THREAD

**Issue by duckroll** [comet-ml/issue-tracking#323]
Hello, I'm trying to run optimizer as described here: https://www.comet.ml/docs/python-sdk/introduction-optimizer/ and get this error:

Traceback (most recent call last):
  File "example-2.py", line 15, in <module>
    loss = fit(experiment.get_parameter("x"))
NameError: name 'fit' is not defined

**Comment by dsblank** [comment]
@duckroll That is example code. You would call whatever function gives you a measure of loss/error. For example, many machine learning frameworks have a fit, such as model.fit(). We recommend getting your training method working first, then factoring out the hyperparameters, then having the Optimizer generate those hyperparameters.

**Comment by duckroll** [comment]
Thanks for answering. I use uber's ludwig and I already trained my model and have an experiment in comet.ml with all the parameters visible. Can you help me with next step? How do I factor out the hyperparameters? And does ludwig have a fit?

**Comment by dsblank** [comment]
Are you using Ludwig CLI (with no code) or as a library?

**Comment by dsblank** [comment]
Closing for now. If you have more information please let us know.
