### ISSUE TITLE
The name parameter passed to Experiment.get_metric function is not honoured.

### ISSUE THREAD

**Issue by KaleabTessera** [comet-ml/issue-tracking#324]
When you pass a name parameter to Experiment.get_metric, the function returns values that don't match that name.

Example:
I passed "test_loss" and got metrics related to "train_loss".

**Comment by dsblank** [comment]
Thanks for reporting! What version of comet_ml are you using?

**Comment by dsblank** [comment]
Also, can you post or send me (privately) your code? I'm doug@comet.ml

**Comment by KaleabTessera** [comment]
Cool, email just send :)

**Comment by dsblank** [comment]
Something definitely looks fishy. Backend engineers looking into it. As a workaround, you can write your own:

```python
def get_metric(api_experiment, metric_name):
    metrics = api_experiment.get_metrics()
    return [x for x in metrics if x["metricName"] == metric_name]

get_metric(experiment, "test_loss")
```

**Comment by KaleabTessera** [comment]
Cool, thanks will use the workaround until the issue is fixed.

**Comment by dsblank** [comment]
I believe that the fix has been made, tested, and is now deployed in production. Please try again without the workaround and let us know if that fixes the issue for you.

**Comment by dsblank** [comment]
Please let us know if you have any additional questions.
