### ISSUE TITLE
log_asset_data throws Exception if experiment is disabled

### ISSUE THREAD

**Issue by kdmcdrm** [comet-ml/issue-tracking#326]
Basically just the subject, I had an experiment that I was debugging so I passed disabled=True to the __init__. Later I call exp.log_asset_data and got this Exception:

`
 File "/home/user1/anaconda3/envs/FraudML/lib/python3.6/site-packages/comet_ml/experiment.py", line 1309, in _log_asset_data
   self.streamer.put_messge_in_q(upload_message)
AttributeError: 'NoneType' object has no attribute 'put_messge_in_q'
`

Also of interest, it looks like message might be misspelled as messge.

**Comment by dsblank** [comment]
@kdmcdrm Good catch! We'll make a check on all methods to make sure they respect `disabled` and fix our misspelled method name. Thanks!

**Comment by dsblank** [comment]
Fixes are being tested.

**Comment by dsblank** [comment]
The fix should be available in our latest version of comet_ml. Thanks for reporting!
