### ISSUE TITLE
Parallelizing the Optimizer across multiple GPUs

### ISSUE THREAD

**Issue by ashwindcruz** [comet-ml/issue-tracking#327]
I'm trying to figure out how to get the Optimizer to use multiple gpus to speed up the search for hyperparameters.
Currently, the [documentation](https://www.comet.ml/docs/python-sdk/introduction-optimizer/) mentions that you can use the `comet optimize` command line tool with the `j` flag to run processes in parallel. However, I tracked the gpu usage while doing this and the different experiments were still competing for just one gpu.
Does Comet's Optimizer have an option for using multiple gpus for the different experiments?
If not, what do you recommend?

**Comment by dsblank** [comment]
@ashwindcruz The `comet optimize -j` will automatically create a number of Python processes to run in parallel, but all in the same environment. If you want to provide special settings, you'll probably want to spawn each instance yourself. Perhaps something like:

```shell
$ edit opt.json # create your Optimizer options
$ export COMET_OPTIMIZER_ID=$(comet optimize opt.json)
$ USE_GPU=1 script.py opt.json
$ USE_GPU=2 script.py opt.json
```

where `USE_GPU` is some environment argument that will signal script.py to configure which GPU to use, and how.

Does that help?

**Comment by ashwindcruz** [comment]
So in a case like this, would each instance of the script be linked to the same optimizer object? 
On this note, does this hold across multiple machines as well as in if I set the optimizer ID to be the same across multiple machines, then all the experiments will be communicating to a single optimizer object that will manage the information coming in from the multiple sources and appropriately choose new hyperparameters for new experiments?

**Comment by dsblank** [comment]
> So in a case like this, would each instance of the script be linked to the same optimizer object?

Yes, exactly.

> On this note, does this hold across multiple machines as well as in if I set the optimizer ID to be the same across multiple machines, then all the experiments will be communicating to a single optimizer object that will manage the information coming in from the multiple sources and appropriately choose new hyperparameters for new experiments?

Yes, that is the design. It is pretty powerful, and allows many distributed, parallel, and serial options.

**Comment by dsblank** [comment]
Please let us know if you have any additional questions.
