### ISSUE TITLE
[FR] Ignite

### ISSUE THREAD

**Issue by jan-matthis** [comet-ml/issue-tracking#328]
I'd be great if comet provided a handler for [Ignite](https://pytorch.org/ignite/) -- similar to existing [contributed handlers](https://pytorch.org/ignite/contrib/handlers.html) such as `tensorboard_logger`, `mlflow_logger`, `polyaxon_logger` et cetera.

**Comment by dsblank** [comment]
Great idea! We'll add this to our list, or if you would like to add this yourself, let us know, and we'd be glad to lend a hand!
