### ISSUE TITLE
Experiment log_git_patch freezes execution

### ISSUE THREAD

**Issue by tracek** [comet-ml/issue-tracking#329]
`log_git_patch` parameter on Experiment effectively grinds to a halt execution of a script, i.e. likely it takes so much time that I abort the program. 

`experiment = Experiment(log_git_patch=False)`

I am on `comet_ml=3.0.2`. The issue is perfectly reproducible regardless of the environment and I can confirm it affects only a single repo. What makes the latter a little special are ~30k files checked in via git LFS.

**Comment by dsblank** [comment]
Thanks @tracek ... we are looking into this issue.

**Comment by tracek** [comment]
Thanks @dsblank , let me know if I can help.

**Comment by Lothiraldan** [comment]
@tracek What is the average size of the files tracked on git LFS? Also how many files do you track on your git repository in total? `git ls-files | wc -l` should be quick way to get the answer, even a ballpark number would help us.

**Comment by tracek** [comment]
@Lothiraldan As mentioned, that's roughly ~30k files. They're rather small, average ~300 kB.

**Comment by Lothiraldan** [comment]
@tracek We have identified an issue with LFS that interprets all files tracked with LFS as different.

Would you have some time to discuss about your usage of LFS and how the git patch feature could be helpful in your use-case? We can do it here or on our Slack instance http://chat.comet.ml/.

**Comment by tracek** [comment]
@Lothiraldan Thanks! Sure, happy to join you there. My answer though is plain and simple: I am not using this feature. The issue here is that the default is set to True, meaning anyone with the same LFS case will get the headache. The report was much less about fixing it for me, but so that others don't run into this problem.

**Comment by dsblank** [comment]
Thanks, @tracek ! I think this is helpful, for us to know what happened, and for future users to workaround possible issues.

**Comment by tracek** [comment]
Thanks @dsblank ! Is this fixed then or just closed?
