### ISSUE TITLE
Comet.ml python 

### ISSUE THREAD

**Issue by makrvasil** [comet-ml/issue-tracking#33]
I am interested in using comet.ml for my projects. I have projects in Java and Python. Is it possible to use Java code with Comet ? 
Do you have any documentation ? I can only find with python.

**Comment by gidim** [comment]
Hi @makrvasil 
We're working on the JAVA SDK but it's not yet available publicly.
Do you want to take part in the beta? we'd love your feedback.

**Comment by gidim** [comment]
Closing for now. Will ping you once the Java version is ready.
