### ISSUE TITLE
COMET ERROR: Failed to log asset data as JSON

### ISSUE THREAD

**Issue by stefanknegt** [comet-ml/issue-tracking#331]
After adding the following line to my script, I get the above mentioned error.

`EXPERIMENT.log_confusion_matrix(labels=["A", "B", "C"], matrix=confusion)`

Where confusion is a 3x3 matrix.

**Comment by dsblank** [comment]
@stefanknegt What are the types of the numbers in the 3 x 3 matrix? Do you have a small reproducible example?

**Comment by stefanknegt** [comment]
Here is a small example that throws this error:

`
from comet_ml import Experiment
import numpy as np
import os
SCRIPT_DIR = os.path.dirname(__file__)
EXPERIMENT = Experiment(api_key=X, project_name=X, workspace=X)
confusion = np.zeros((3,3))
EXPERIMENT.log_confusion_matrix(labels=["Noise", "Question", "Answer"], matrix=confusion)`

**Comment by dsblank** [comment]
Thanks for reporting. We will add the ability to automatically convert the numpy array to a list of numbers. As a workaround until next release, you can:

```python
EXPERIMENT.log_confusion_matrix(
    labels=["Noise", "Question", "Answer"], 
    matrix=confusion.tolist())
```

**Comment by stefanknegt** [comment]
Ah yes this works, thanks a lot!
