### ISSUE TITLE
comet optimize with cuda_device

### ISSUE THREAD

**Issue by EntilZha** [comet-ml/issue-tracking#332]
Hi, I've been starting to use comet and looking into use `comet optimize` to explore hyper parameters. In particular, `comet optimize -j 8` when I have an 8 GPU machine. I didn't see in the docs, but can this handle setting `CUDA_VISIBLE_DEVICES` for each worker, or is that something I'd have to do manually?

**Comment by dsblank** [comment]
Take a look at https://github.com/comet-ml/issue-tracking/issues/327

Should be able to do something programmatically. If you come up with a solution, please do share. It would be great to have a general approach.

**Comment by EntilZha** [comment]
My tentative plan is to create a lockfile of sorts that tracks which GPUs are currently being used. When one of the instances of my script (one worker in `comet optimize -j 8`) starts up it would consult this and grab lock to a GPu and set CUDA_VISIBLE_DEVICES correctly. Its not great, but seems workable.

On the comet side, something like handing out locks to a resource would be nice (e.g., in hyper parameter config say there are 8 of a resource named `GPU` and to give each experiment `n` of that resource). One potential issue though is if an experiment fails, to make sure to release the resource.

**Comment by dsblank** [comment]
Interesting ideas! 

Perhaps if each process could access an assigned integer, then you could match the resource to the process. For example, if running with `-j 8` and you have 8 GPUs, each process would know which of the devices it should use. Would that help?

**Comment by dsblank** [comment]
To help with these types of situations, there is now an environment variable `COMET_OPTIMIZER_PROCESS_ID` that will have a unique integer (0 through j - 1) for this `comet optimize` invocation. You can allocate resources based in the value, if you wish. This will appear in comet_ml version 3.1.3 and later. Hope that helps!
