### ISSUE TITLE
Archive button always grayed out

### ISSUE THREAD

**Issue by lemairecarl** [comet-ml/issue-tracking#333]
When I check the checkbox of an experiment, the Archive button does not light up, and clicking it does nothing.

**Comment by gidim** [comment]
Hi @lemairecarl -  thanks for reporting! Is it possible you don't have permissions to archive experiments in that project?

**Comment by lemairecarl** [comment]
It's my own projet.

But now it's working, I just got to archive the experiment. No idea what has changed...

**Comment by lemairecarl** [comment]
I will reopen if it happens again or if I can provide more info
