### ISSUE TITLE
Allow adding/editing tags from UI for existing experiments

### ISSUE THREAD

**Issue by benbogin** [comet-ml/issue-tracking#334]
It seems like tags for experiments can only be set during the initialization of the experiment.

It would be useful to be able to add or edit tags from the UI, just as you can change the name of existing experiments.

**Comment by nikolaskaris** [comment]
Hi Ben,

You can add tags from the UI:

![demo_confusionmatrix](https://user-images.githubusercontent.com/10041710/75356106-75e01f00-587d-11ea-9d40-56b71ed33f4b.png)

Select an experiment and click the tag button — you'll be able to either create a new tag or assign an existing tag to an experiment or group of experiments. 

Hope this helps,
Niko

**Comment by benbogin** [comment]
Oh I see, not sure how I missed it :) Thanks
