### ISSUE TITLE
[feature request] add support for pytorch models in function set_model_graph

### ISSUE THREAD

**Issue by Idodox** [comet-ml/issue-tracking#335]
Currently, there's only support for TF model graphs.

**Comment by dsblank** [comment]
Good idea! Do you have code that turns a pytorch model graph into JSON or a string rep?

**Comment by Idodox** [comment]
You can get some info by simply printing the model:

```
from torchvision import models
model = models.vgg16()
print(model)
```


There's also a package called torchsummary that offers more detail:

```
from torchvision import models
from torchsummary import summary

vgg = models.vgg16()
summary(vgg, (3, 224, 224))
```

**Comment by dsblank** [comment]
That is useful info. Thanks @Idodox , it is on our list!

**Comment by george-gca** [comment]
There is also the option of converting the model to [ONNX](https://pytorch.org/docs/stable/onnx.html).

**Comment by dsblank** [comment]
Indeed! We have some work on that front coming soon. I'll report back here.
