### ISSUE TITLE
Data points missing in graphs

### ISSUE THREAD

**Issue by b02901071** [comet-ml/issue-tracking#336]
As titled, data points were missing in some graphs, but normal in others, for example:

![截圖 2020-02-28 下午10 12 38](https://user-images.githubusercontent.com/22560619/75555728-bf945980-5a77-11ea-9c91-fb181f8b521b.png)

As shown in the figure above, the train_loss before 54K steps were missing, while the dev_loss is fine. It keeps the same no matter how many times I reload the page. However, everything seemed right yesterday, it just happened today.

Could anyone help me with it?

**Comment by b02901071** [comment]
It also happens in other graphs:

![截圖 2020-02-28 下午10 23 48](https://user-images.githubusercontent.com/22560619/75556401-1e0e0780-5a79-11ea-9276-3d4b3262770d.png)

and also in other experiments:

![截圖 2020-02-28 下午10 27 29](https://user-images.githubusercontent.com/22560619/75556626-89f07000-5a79-11ea-8d8d-2b8134c3f27d.png)

as shown above, the dev_103 missed data points before 27k and between 27k to 65k.
For different experiments, they have different corrupted graphs.

**Comment by dsblank** [comment]
@b02901071 I see that in both the first and last that the experiments are still running. Do the graphs look the same when the experiment has completed? 

To try to find the problem, you might be interested to try logging to an `OfflineExperiment(offline_directory="./")` and then exploring the data to make sure it is being sent. See, for example: https://www.comet.ml/docs/command-line/#comet-offline

Please send a note to support@comet.ml with a link to an experiment and we can try to find the issue from our end too.

**Comment by b02901071** [comment]
Now I've stopped the last experiment, and it keeps the same.

For the offline suggestion, since I only use `Experiment` instead of  `OfflineExperiment`, I couldn't find a zip file that saves information about my experiment, so I believe that those experiment data has been sent completely.

Maybe I would send a link to this issue and links to those experiments with corrupted graphs later to  support@comet.ml later. Thanks for your help!

**Comment by simopal6** [comment]
Any news on this issue? I'm also experiencing the same thing.

**Comment by dsblank** [comment]
We're looking into this on our end. Could your experiment have been throttled? See https://www.comet.ml/docs/python-sdk/warnings-errors/#rate-limits

**Comment by simopal6** [comment]
Thanks @dsblank. I don't think the rate limits have been reached. A strange thing I experience is that, as new points get added, the set of points shown in the chart changes. I'll try and get some screenshot when I can.

**Comment by dsblank** [comment]
@simopal6 Thanks, that would be useful! We have engineers looking at that, so any info would be helpful.

**Comment by corneliusphi** [comment]
Is the chart changing in that random points are getting downsampled or is the region with the missing datapoints expanding?

**Comment by simopal6** [comment]
It's more like the sets of point shown in two consecutive updates are selected randomly; the last update is always shown though.

Here is an example of two consecutive updates.

![s1](https://user-images.githubusercontent.com/4355487/75791357-bf90a400-5d6c-11ea-8c6e-58fb75973f84.png)![s2](https://user-images.githubusercontent.com/4355487/75791360-c0293a80-5d6c-11ea-94f4-dc03aa0dccd4.png)

**Comment by corneliusphi** [comment]
what's the experiment key?  That looks like it might just be expected downsampling and unrelated, but I'd like to check

**Comment by simopal6** [comment]
The experiment key is 160751e8e29045f1b7cd4a08761fb02d. However, I just noticed that the above problem only appears on the project page, where the list of all experiments is shown. If I open the experiment page, it seems that all data points are shown.

**Comment by corneliusphi** [comment]
The project page shows a much smaller number of points in order to minimize load times.  You can change that by selecting "sample size" in the 3 dots button on the project page chart

**Comment by corneliusphi** [comment]
can I get the experiment keys for the other experiments that you've mentioned?

**Comment by simopal6** [comment]
The figures I posted above all referred to the same experiment, for which you correctly pointed me to the sample size setting.

You might want to have a look at experiment c573b39933a4442596c2f880564792a6. Here, even in the experiment page, if you have a look at the `loss` chart (which, by the way, is not one I explicitly save), you can see that the initial part of the plot is heavily downsampled. However, the other plots look fine.

**Comment by corneliusphi** [comment]
It looks like there might be a bug in the algorithm to ensure that we down sample evenly across steps.  Given that you logged on the order of 124k data points when we only keep 15k you might workaround by only logging every 10th point?

**Comment by corneliusphi** [comment]
@b02901071 are you missing data on other experiments than e78bcfe35d914607a29eed4186945bec from the screenshots you logged in this bug?
Your issue appears to be different than the one simopal6 was having

**Comment by b02901071** [comment]
> @b02901071 are you missing data on other experiments than e78bcfe35d914607a29eed4186945bec from the screenshots you logged in this bug?
> Your issue appears to be different than the one simopal6 was having

It also happens on 5b5ecebffd1f47a29d4003a0a5ec7a6f and 5ab9cca5274c4a46860a93c2937ebb1b

**Comment by corneliusphi** [comment]
how often did you generate dev_106-tagalog_loss on 5b5ecebffd1f47a29d4003a0a5ec7a6f?

**Comment by b02901071** [comment]
every 2500 steps

**Comment by Nimrod007** [comment]
Hi @b02901071 , @simopal6 
We are currently working on this issue. 
This is related to our "live" downsample vs "finished" downsampling and moving our metrics storage to a `consistent` (currently its `eventually consistent`) storage
Will update on progress.

**Comment by corneliusphi** [comment]
Are you still seeing these issues?  We have deployed several fixes in the last couple days

**Comment by b02901071** [comment]
Yeah, still with these issues.

**Comment by corneliusphi** [comment]
which experiment?  The old experiments or on new experiments?

**Comment by b02901071** [comment]
Only on those three old experiments, not on new experiments.

**Comment by corneliusphi** [comment]
ah ok.  For the old experiments I believe that the missing data at the beginning of those experiments is gone.  We have changed configuration on Cassandra to ensure consistency over availability of data to prevent this happening for future experiments.

I still haven't figured out what it was about your particular usage pattern that was triggering this issue when it was not affecting most other users.  I'd be interested if you have thoughts on what you are/were doing that is unique

**Comment by b02901071** [comment]
I have no idea why it happens... I have several other experiments using the same code with only minor changes, but they're fine without any problem. And also as mentioned, the old experiments used to be fine at the beginning (training before 50k steps) but losing data afterward. Maybe newly sent data would somehow affect those already sent? Not sure about it.

**Comment by corneliusphi** [comment]
Yeah I believe we fetched inconsistent data from Cassandra at some point and then overwrote the old good data because of a misconfiguration, which we've since tracked down and fixed.

**Comment by corneliusphi** [comment]
@simopal6 are you still experiencing any issues?
