### ISSUE TITLE
logging for all the related codes 

### ISSUE THREAD

**Issue by suwoncjh** [comet-ml/issue-tracking#337]
Can I log all the codes that are related in 'main.py'?

For example, I have three python scripts as below:

-- model.py
-- loss.py
-- main.py

In 'model.py' and 'loss.py', there are classes about model and loss and I use those classes in my 'main.py' script using import.

What I want to do is logging all the codes not only 'main.py' but also 'loss.py' and 'model.py'.

For now, I can not find any information about this feature in documents.

**Comment by dsblank** [comment]
@suwoncjh You can log them as assets:

* Experiment.log_asset_folder(...)
* Experiment.log_asset(file_name)

More information, please see: 

https://www.comet.ml/docs/python-sdk/Experiment/#experimentlog_asset

**Comment by gidim** [comment]
@suwoncjh  - we actually log all the code diffs using the reproduce button. If you have git initialized in your folder you can click the reproduce button, apply the commands and see everything on github.

**Comment by suwoncjh** [comment]
@dsblank @gidim 
Thank you very much for the prompt reply.
