### ISSUE TITLE
A lot of unwanted output in jupyter notebook

### ISSUE THREAD

**Issue by sbysiak** [comet-ml/issue-tracking#340]
I am using comet in jupyter notebook,  with `Experiment(..., auto_output_logging='simple')`
I observe there is a lot of rubbish logged in the output tab, it's something like a list of all variables repeated multiple times.
Comet.ml version: 3.1.1

Example experiment:
https://www.comet.ml/phd/bc-vs-udsg/e20bd4c5589f43f4979bc285725f8a2b?experiment-tab=stdout

Is there a way to suppress these and still log real outputs in jupyter notebook?

**Comment by dsblank** [comment]
@sbysiak Could those be command-line completions when you press TAB?

**Comment by sbysiak** [comment]
Not exactly, it seems to appear each time a cell is executed by hand. 
See attached screenshot for minimal working example. As next cells were executed, the output was added in area below 2nd cell. The 3rd cell was run 3x. I didn't press TAB.

As you can see, the output is also not printed directly below cells, but it is logged in comet.

![image](https://user-images.githubusercontent.com/15728684/76458230-85617b00-63da-11ea-964d-e173a18a6c23.png)

**Comment by dsblank** [comment]
@sbysiak Thank you for that additional detail. We hope to be able to support output logging in the Notebook, but it is not currently supported. But we are working on it!

**Comment by sbysiak** [comment]
Oh, I just figured out what was causing the problems - it's one of jupyter's extensions called **"variable inspector"**. After disabling it, I no longer see the list of variables, so the output in experiment/output tab is fully correct.   
The only drawback is that the output is not printed under corresponding cell, but for me that's fine.

Thank you for prompt response, cheers!

**Comment by dsblank** [comment]
Ah, that makes sense. I was hoping that Jupyter wasn't showing some new behavior. Yeah, the output going to one cell is the last thing we have to fix. Thanks for the update!
