### ISSUE TITLE
[Feature request] Sort/filter audio by metadata

### ISSUE THREAD

**Issue by dorekhov1** [comet-ml/issue-tracking#341]
It would be great if it was possible to sort/filter audio by some metadata tags. I have audio from different sources, I train on them and log the files that the model performs worst at (I add the "error" as a metadata key for each file). So at this point, I have to manually look through the metadata to find the files with the highest error, but ideally I would be able to tell the platform something like "show me the files from sources X, Y and Z only and sort them by decreasing error".

**Comment by dsblank** [comment]
Interesting!
