### ISSUE TITLE
[Feature Request] Show id of experiments when diffing

### ISSUE THREAD

**Issue by lleewwiiss** [comet-ml/issue-tracking#343]
Is it possible to add to the top where the names are shown which experiment is experiment 1 and experiment 2, aside from the charts there is no way to tell which is which

**Comment by dsblank** [comment]
You should be able to see the experiment names/keys at the very top of the page:

![Screenshot from 2020-03-19 08-25-43](https://user-images.githubusercontent.com/168568/77067458-5db27a00-69bb-11ea-9819-6824835986f3.png)

Do you see that on your view? Would it also be useful if "Experiment 1" were also the name/key?

**Comment by lleewwiiss** [comment]
Yeah possibly adding a column up the top to show which is 1 and 2, as it isn't always obvious which is which

**Comment by ferc** [comment]
Internal tracking number CH-10128

**Comment by aviadr1** [comment]
done
