### ISSUE TITLE
[Feature Request] Accentuate individual experiment in charts when highlighting over legend

### ISSUE THREAD

**Issue by joeddav** [comet-ml/issue-tracking#344]
Once you have more than around half a dozen experiments showing in the same chart, it becomes difficult to distinguish individual experiments. The first problem is that when transformations are applied, the legend shows the color of the light, background lines rather than the bold transformed ones, which makes it pretty difficult to match the colors in the legend to the colors of the lines.
![image](https://user-images.githubusercontent.com/9353833/77234906-41176d00-6b88-11ea-9fbc-8e1146c12f80.png)
In addition to making the colors in the legend match the chart, another feature that would help a lot would be to accentuate particular experiments when the mouse hovers over them. For example, if I hover my mouse over `topics_schedule` in the legend, I'm envisioning that all of the other experiments in the chart would be faded out while only `topics_schedule` remains in bold.

**Comment by gidim** [comment]
Thanks for the feedback @joeddav 
The first issue is easily solvable and we will get to it this week.
The second request might be more involved (Plotly often requires us to render the entire plot from scratch on any change) but we will look into it!

**Comment by joeddav** [comment]
This works great now, thanks!
