### ISSUE TITLE
Can't add custom system metric to columns of experiments table

### ISSUE THREAD

**Issue by benbogin** [comet-ml/issue-tracking#346]
I am adding a system metric through the code:
`experiment.log_system_info('serialization_dir', serialization_dir)`

I can then see this metric in "system metrics" as expected, but when I click on "customize columns" in the experiments page, this metric is not listed

**Comment by dsblank** [comment]
True, but you could use:
```
experiment.log_other('serialization_dir', serialization_dir)
```
and that should work.

**Comment by benbogin** [comment]
Right, this works. Thanks
