### ISSUE TITLE
Metric curves always start at duration 0

### ISSUE THREAD

**Issue by TevenLeScao** [comet-ml/issue-tracking#347]
Plotting a metric vs duration always has the curve start at x = time = 0. When logging an infrequent metric (ie. validation loss), this is an issue, as the first measurement might be late into training. With a significant x-axis offset, comparing the evolution of different metrics over time becomes impossible. It's also an issue for comparing two runs with a different logging frequency. 

![image](https://user-images.githubusercontent.com/26709476/79234593-c3830c00-7e6a-11ea-84fd-228b20c00df6.png)
For example, here, the first validation epoch was at 400s curve that starts at 4.8 and 200s for the one that starts 5, yet they're shown both starting at 0.

**Proposed fix - storing the time of the `Experiment` object creation as the start of the experiment, and reporting duration relative to that time.**

**Comment by dsblank** [comment]
Duration is the time between steps, so it would make sense that they start at 0. 

Perhaps what you want is Wall Time, another selection from the X Axis choices?

**Comment by TevenLeScao** [comment]
It would be more convenient to start counting the duration from the experiment start time rather than from the first log for that particular metric. This would allow consistent comparisons side by side in a consistent way across metrics and across runs.

Wall time doesn't allow that either, so I'm pretty sure it's not what I want here :)

**Comment by TevenLeScao** [comment]
It would be more convenient to start counting the duration from the experiment start time rather than from the first log for that particular metric. This would allow consistent comparisons side by side in a consistent way across metrics and across runs.

Wall time doesn't allow that either, so I'm pretty sure it's not what I want here :)

**Comment by dsblank** [comment]
I think I see your point now. I guess this makes sense for the Experiment View (where each line will be meaningful in relation to the start time).

**Comment by Nimrod007** [comment]
we not allow to set the start time and end time of line charts in the project view
