### ISSUE TITLE
Feature request: Confusion matrix exception handling

### ISSUE THREAD

**Issue by Idodox** [comet-ml/issue-tracking#350]
CM error handling looks like the following at the moment.

```
            except Exception:
                LOGGER.error("Error creating confusion matrix; ignoring", exc_info=True)
                return
```

Although this keeps the program going (which isn't in the users interest in my personal opinion), it doesn't relay any info about the error itself.

**Comment by dsblank** [comment]
Yes, you are correct. Try setting `COMET_LOGGING_CONSOLE=info` (or using a config file) and see if that is better.

**Comment by dsblank** [comment]
We have written a section in the docs addressing this common issue:

https://www.comet.ml/docs/python-sdk/advanced/#debugging-with-comet

Please reopen if any further advice is needed.
