### ISSUE TITLE
Cannot directly switch between filter values on web dashboard

### ISSUE THREAD

**Issue by ericzhao28** [comet-ml/issue-tracking#351]
If a filter (e.g. "name") is set to some value (e.g. "is (x)"), the web UI does not allow for changing the said filter to a different value (e.g. "is (y)"). This is because the current UI limits multiple choice filter values to values present under the current filter. Would it be possible to temporarily remove this feature?

For example, when adding a new filter, all options are available:
![image](https://user-images.githubusercontent.com/17482791/80531661-d5c37680-894f-11ea-9ac3-76907c888529.png)

However, if I now try to change the filter value, only the current option is available:

![image](https://user-images.githubusercontent.com/17482791/80531740-f1c71800-894f-11ea-812f-5e127a5d8e99.png)

**Comment by ericzhao28** [comment]
Just emailed.

**Comment by Nimrod007** [comment]
Thanks for reporting this @ericzhao28 we will add this to our roadmap and fix. will notify here once its done!

**Comment by Nimrod007** [comment]
Hi @ericzhao28 this was fixed in out latest version.
