### ISSUE TITLE
Multiple Confusion Matrix view 

### ISSUE THREAD

**Issue by jdegange** [comet-ml/issue-tracking#354]
Hi 

Thanks for update to the confusion matrix documentation and API!  My question is simple - is it possible to show two confusion matrices or more within the main UI at same time?  

While I can log separate matrices, I cannot find a way to render multiple matrices at same time, or if it's even currently a possibility.

**Comment by dsblank** [comment]
@jdegange Glad you like the updates to docs and API! 

Currently, on the Histogram Tab, you can only see one confusion matrix at a time (you could open two browser windows). You could show two (or more) basic confusion matrices with the new custom Panels [1]. We are working on having custom Panels for the Experiment View, but you could use the workaround [2] and do it yourself to see confusion matrices for one experiment. You'd need to be able to process the confusion matrix JSON. Let me know if you are interested in this option.

[1] - https://www.comet.ml/docs/javascript-sdk/getting-started/
[2] - https://www.comet.ml/docs/javascript-sdk/getting-started/#single-experiment-workaround

**Comment by Sicily-F** [comment]
Hi there, I am having this same issue and do not understand the work around - do you have any recommendations?
