### ISSUE TITLE
ImportError in release 3.1.7 for Python

### ISSUE THREAD

**Issue by fabalbertoni** [comet-ml/issue-tracking#356]
I just got an error when trying to get the current global Comet experiment, which seems to be related to the latest Comet release for Python (which happened today):
`ImportError: cannot import name 'get_global_experiment' from 'comet_ml'`

You can reproduce it just by running `from comet_ml import get_global_experiment`
It works Ok for versions <= 3.1.6

**Comment by dsblank** [comment]
Thanks for the note, @fabalbertoni . We tried building the library a different way, and it must have an issue.

**Comment by dsblank** [comment]
As another workaround, you can also try `from comet_ml.config import get_global_experiment`. Looks like this is unrelated to conda... the regular pip install has the same "feature". We must have removed an import.

**Comment by fabalbertoni** [comment]
That works, thank you!

**Comment by dsblank** [comment]
We have restore the import in the latest comet_ml release. Thanks for reporting!
