### ISSUE TITLE
Incorrect bounds in optimizer config will lead to unclear error message for random and bayes algorithm

### ISSUE THREAD

**Issue by kjappelbaum** [comet-ml/issue-tracking#357]
Using comet-ml 3.1.7 on OSX. The following snippet, with some fit method that returns a score

```python
config = {
        "algorithm": "bayes",
        "parameters": {
            "learning_rate": {
                "type": "float",
                "min": 0.00,
                "max": 0.3,
                "scalingType": "loguniform",
            }}
}
opt = Optimizer(config, api_key=os.environ["COMET_API_KEY"])

for i, experiment in enumerate(opt.get_experiments()):
        params = {
            "learning_rate": experiment.get_parameter("learning_rate"),
        }
        loss = fit(experiment, X_train, y_train, params)
        experiment.log_metric("loss", loss)
```

"Fails" with `algorithm=bayes` without error message, just printing 
```
COMET INFO: Optimizer search 83050ee9015f4c1db1cbe883934dda31 has completed
```

With `algorithm=random` it raises an error, but on the first look it seems unrelated to the real issue 
```
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://optimizer.comet.ml/create
```

Only with `algorithm=grid` the error message shows what the real problem is
```
comet_ml.exceptions.OptimizerException: Optimizer server: Range exceeds valid bound
```

Using a non-zero bound the snippets works fine for all algorithms, but I guess it would be nice if the error would be caught for all algorithms and maybe even point out more clearly what the issue is (e.g, it should be non-zero).

**Comment by dsblank** [comment]
Thanks @kjappelbaum for the detailed report. We are now investigating...

**Comment by dsblank** [comment]
We'll work towards making all of the errors bubble up to be messages for the client. Thanks for the report!
