### ISSUE TITLE
Can I have two experiments in one script concurrently?

### ISSUE THREAD

**Issue by seungjaeryanlee** [comet-ml/issue-tracking#359]
Here is what I hope to do:
```python
meta_experiment = Experiment()

for ... # Meta loop
    individual_experiment = Experiment()
    for ... # Training loop
        individual_experiment.log_metrics(...)
    meta_experiment.log_metrics()
```

**Comment by dsblank** [comment]
Maybe, but you have to do at least these two things:

1. after the first experiment you need to clear the global experiment, something like this:

```
from comet_ml.config import set_global_experiment

meta_experiment = Experiment()

set_global_experiment(None)
```

2. make sure you call experiment.end() for each experiment you create.

You also need to make sure you aren't trying to log the standard output from each experiment. Also, multiple CPU, and GPU logging problems could arise if logging from both.

Let us know how it works.

**Comment by IanQS** [comment]
@seungjaeryanlee 

Did you get this working? I'm looking to do something very similar but I ran into an issue where creating the second logger caused the first to get closed out

**Comment by seungjaeryanlee** [comment]
My memory fails me, but I don't think it worked for me. I think I ended up using two separate experiment tracking solutions.

**Comment by IanQS** [comment]
Thanks for the response! And damn, that sucks bc I really like Comet. Mind sharing what you used?

**Comment by gidim** [comment]
@IanQS it should be possible with the example Doug provided. Have you tried that? After you call `experiment.end()` you can continue reporting to the same one using `ExistingExperiment()`

**Comment by IanQS** [comment]
Ahh, gotcha! Okay, I'll look into that then, thanks!
