### ISSUE TITLE
refreshing experiments doesn't always save "hidden" state

### ISSUE THREAD

**Issue by benbogin** [comet-ml/issue-tracking#360]
When I click on the refresh button, even if I had some of the experiments hidden, the hidden/visible state is not saved, and all experiments are then shown. This doesn't always happen, only sometimes. Not sure what exactly reproduces it, but it happens about 50% of the times I refresh (in the other cases the hidden state is kept as expected)

**Comment by Nimrod007** [comment]
Hey @benbogin, thanks for reporting this
I did not manage to re-create this issue

Ive tested the following scenario:
* go to a project page
* navigate to experiments table
* hide a few experiments (click on the eye icon)
* refresh the browser tab
* experiments are hidden (as expected)

did this several times (with hide / show)

if this isn't the same scenario that you tested please share
in addition can you test again and verify if this is still an issue?
Thanks.

**Comment by benbogin** [comment]
Thanks, yes this is still an issue - the only thing different than what you describe is that I click on the refresh button of the experiments page (next to the Auto Refresh button)

**Comment by Nimrod007** [comment]
Hey @benbogin thanks for the clarification. I managed to recreate and opened an issue on our internal systems. will update here once resolved and deployed.

**Comment by dsblank** [comment]
@benbogin We believe that this has been fixed. Please let us know if you still have issues. Thanks!

**Comment by benbogin** [comment]
@dsblank This is still happening...

**Comment by dsblank** [comment]
@benbogin Can you send me a link to a comet project where this happens? You can direct-message me if you like (doug@comet.ml)

**Comment by benbogin** [comment]
sure, sent you.
