### ISSUE TITLE
`API.get_metrics_summary(metric=name)` returns an empty list instead of dict

### ISSUE THREAD

**Issue by neighthan** [comet-ml/issue-tracking#362]
If you call `API.get_metrics_summary` with the name of a particular metric, and the experiment has data for that metric, a dictionary is returned. If the experiment lacks data for that metric, then an empty list is returned. An empty dictionary would make more sense here so that the return type in this case doesn't depend on whether the metric exists or not. This makes further processing easier because you don't have to handle two different possible return types. As an example, here's what I would like to do:

```python
from comet_ml.api import API, Parameter
api = API()
workspace = "..."
project = "..."
query = Parameter("something") == "another thing"

exps = api.query(workspace, project, query)
metric_name = "return"
default = float("nan")
max_metrics = [exp.get_metrics_summary(metric_name).get("valueMax", default) for exp in exps]
```

but if the metric might not exist on some experiments, then I have to handle empty lists instead by doing something like

```python
max_metrics = []
for exp in exps:
    metric = exp.get_metrics_summary(metric_name)
    if isinstance(metric, list):
        max_metrics.append(default)
    else:
        max_metrics.append(metric["valueMax"])
```

**Comment by dsblank** [comment]
Yes, good idea!
