### ISSUE TITLE
add option to disable "upgrade comet pip INFO message"

### ISSUE THREAD

**Issue by Vozf** [comet-ml/issue-tracking#363]
Please remove the annoying warning to update comet ml package.
```
COMET INFO: old comet version (3.1.9) detected. current: 3.1.11 please update your comet lib with command: `pip install --no-cache-dir --upgrade comet_ml`
```
This warning pops up every script run. It has no value. Everybody knows that package are updated. If every package I have will print this warning, there would be no space in my terminal at all. It takes attention from more important warnings by deep learning frameworks. Your package is not Windows to update whenever if feels like it. If the current version satisfies my needs I will stick to it. No need to print a warning every script run. I don't believe such warnings are appropriate for any dependency.

**Comment by Nimrod007** [comment]
Hi @Vozf I appreciate the feedback and your architectural suggestions.
We will add a flag to disable this warning and will update here once its done.

Thanks for taking the time and sharing your feedback

**Comment by dsblank** [comment]
Assigned to internal tracking CB-9464

**Comment by dsblank** [comment]
@Vozf Update: this issue has been addressed in the latest versions of the comet_ml SDK. Currently, it will only show the message once per session (individual import of comet_ml in a process). In a future change, we will allow you to completely hide the message.

Note that disabling the message is not recommended in general, and `comet_ml` is not like other Python packages. It is more like `pip` which does emit a message if there is a new version available.
