### ISSUE TITLE
Typo in Comet.ml warning

### ISSUE THREAD

**Issue by LSgeo** [comet-ml/issue-tracking#364]
`COMET WARNING: Websocket connection didn't **closed** properly after 10 seconds`

Noticed this typo earlier (closed -> close). Couldn't find the code line reference.

Thanks for a great program!

**Comment by Lothiraldan** [comment]
Thank you for your issue, it will be fixed in the next Python SDK release

**Comment by Lothiraldan** [comment]
This has been fixed on the Python SDK release 3.1.12, thank you again for your ticket.
