### ISSUE TITLE
how to turn off logging `storage_size_bytes` in `other` tab? 

### ISSUE THREAD

**Issue by ZENGXH** [comet-ml/issue-tracking#365]
I found the `storage_size_bytes` is always logged in the `other` tab, is there any way to remove it or stop logging it? 

Thanks!

**Comment by Nimrod007** [comment]
Hi @ZENGXH this is added by comet automatically and determines what is the storage size for this experiment. 
each workspace  plan has storage assigned to it
https://www.comet.ml/site/pricing/
