### ISSUE TITLE
Is it possible to download the entire metrics?

### ISSUE THREAD

**Issue by yosider** [comet-ml/issue-tracking#367]
Is it possible to download the entire metrics (not a summary of metrics) of an experiment in a format like csv?
Thanks!

**Comment by Nimrod007** [comment]
Hi @yosider you can download it as JSON via 
* rest api : https://www.comet.ml/docs/rest-api/read-endpoints/#get-all-metrics-for-name
* python api : https://www.comet.ml/docs/python-sdk/APIExperiment/#apiexperimentget_metrics
* js api: https://www.comet.ml/docs/javascript-sdk/api/#apiexperimentmetricexperimentkey-metricname-interval-promise
