### ISSUE TITLE
Running Experiment Graphics Tab Refreshes Too Often

### ISSUE THREAD

**Issue by ryanhausen** [comet-ml/issue-tracking#368]
During a running experiment, the Graphics Tabs refreshes every few seconds resetting any filters that are set. It seems to happen more often than when graphics are logged as there isn't a new graphic every time its refreshed. It may be the case that the graphics tab is refreshing when anything is logged, for example an update to the output tab.

I think the expected behavior is for the graphics tab to refresh whenever a new graphic is logged by an experiment.

Thanks!

**Comment by dsblank** [comment]
Note that this is the `graphics filters` being reset on the Graphics Tab.

**Comment by Nimrod007** [comment]
Thanks for reporting, we will update here once resolved

**Comment by dsblank** [comment]
Internal tracking number CH-9492

**Comment by Nimrod007** [comment]
fixed on Jul 23 2020

**Comment by ryanhausen** [comment]
@Nimrod007  This works wonderfully now! I really appreciate it!
