### ISSUE TITLE
Archive Experiment Link Doesn't work

### ISSUE THREAD

**Issue by ryanhausen** [comet-ml/issue-tracking#369]
The link to view archived projects, when you archive an experiment doesn't work.

Steps to reproduce:

From the project overview page:
- click a check box selecting an experiment
- click the archive button 
- at the "Are you sure?" screen click the "archive page" link
- Shows an Error box, "The experiment doesn't exist anymore"

The "archive page" links points to:

https://www.comet.ml/[user]/[project]/view/[experiment]/archive

but maybe it should point to

https://www.comet.ml/[user]/[project]/archive

**Comment by dsblank** [comment]
Thanks @ryanhausen ... taking a look.

**Comment by dsblank** [comment]
Yes, looks correct. This is the link that is wrong:

![Screenshot from 2020-07-15 12-48-49](https://user-images.githubusercontent.com/168568/87589162-d350fd00-c6b2-11ea-847c-49b6c3d92e60.png)

**Comment by ryanhausen** [comment]
Right

**Comment by dsblank** [comment]
Internal tracking number CH9596.

Thanks for reporting!

**Comment by Nimrod007** [comment]
Hi @ryanhausen thanks for reporting, the link should be 
* https://www.comet.ml/[user]/[project]/view/[experiment]/archive
and ive tested this in various scenarios and it seems to be working. 

There might be another issue happening in your project. please re-open if this is still an ongoing problem.

Thanks

**Comment by ryanhausen** [comment]
@Nimrod007 Thanks for looking into the issue. The link seems to have been updated to:
