### ISSUE TITLE
Is there a way to import Tensorboard experiments

### ISSUE THREAD

**Issue by danielhomola** [comet-ml/issue-tracking#370]
Our teams is in the process of migrating our experiment tracking over to comet. We have a lot of data collected in TB log event files and hparams.yaml files (standard setup for tensorboard). is there a way to port / import these to comet somehow?

Many thanks,
d

**Comment by dsblank** [comment]
@danielhomola Sure, you can recreate the experiments using the Comet Python API, specifically the APIExperiment. Please see:

* https://www.comet.ml/docs/python-sdk/API/
* https://www.comet.ml/docs/python-sdk/APIExperiment/

Let us know if you have any questions! If you end up making your code public, let us know and we'd be glad to make comments/suggestions, and share with others.

**Comment by danielhomola** [comment]
@dsblank  Thanks a lot for the prompt reply! I might be missing something obvious here, but which method should be used to init an experiment from a saved `.events` file of a previous tensorboard run? I.e. if I have a folder with let's say the following files:

- `log.events` (binary file for tensorboard)
- `hparams.yaml` (yaml file with the hyperparams)

is there a method already in the sdk that will parse the events file and create a new experiment in  comet that I can upload? 

Thanks,
d

**Comment by dsblank** [comment]
> is there a method already in the sdk that will parse the events file and create a new experiment in comet that I can upload?

No, it will take a little work. BTW, are you an enterprise Comet customer? 

The script would look like this:

```
for each experiment to upload:
    # parse the log.events and yamls
    experiment = APIExperiment() # creates a new experiment
    experiment.log_metrics(...)
    experiment.log_parameters(...)
    experiment.log .... whatever else you have: models, histograms, images.. everything!
```
