### ISSUE TITLE
What is comet-git-pure ?

### ISSUE THREAD

**Issue by lemairecarl** [comet-ml/issue-tracking#371]
`comet-git-pure` is a dependency of the `comet-ml` python package. I would like to know more information about this package, as there is nothing on PyPI: https://pypi.org/project/comet-git-pure/

I'm mostly wondering why you need two packages; can't this functionality be included in `comet-ml` ?

Thank you!

**Comment by dsblank** [comment]
@lemairecarl I believe that that is a fork of dulwich, a pure-python implementation of some git functionality. We are in the process of moving the fixes upstream, and should be able to remove this shortly. 

Our engineer working on this project will be back next week and can provide more details, or correct me.

**Comment by dsblank** [comment]
@lemairecarl Upstream fixes have been accepted, and we have been able to remove this in the current version of comet_ml. Let us know if you have any questions or issues. Thanks!

**Comment by lemairecarl** [comment]
That's awesome, thanks!
