### ISSUE TITLE
Feature Request: Cumulative Wall Time Duration for Experiments

### ISSUE THREAD

**Issue by ryanhausen** [comet-ml/issue-tracking#372]
The Duration column in project summary page isn't useful for any resumed experiments. To be specific, the formula for the duration column seems to be:

Duration = experiment.EndTime - experiment.StartTime

For a single experiment run this is fine, but if you resume an experiment this becomes uninformative. Consider the following:

Experiment 1 
- Starts at 12:00am and ends at 12:00pm
- The duration is 12 hours

Experiment 2 
- Starts at 12:00am and ends at 1:00am
- It's resumed at 11:00am and ends at 12:00pm
- The duration is also 12 hours, but should be 2 hours.

I think that CPU wall time might be more intuitive. Thanks!

**Comment by dsblank** [comment]
Thanks @ryanhausen ! Adding this to our list.
