### ISSUE TITLE
Creating the experiment is extremely slow

### ISSUE THREAD

**Issue by lleewwiiss** [comet-ml/issue-tracking#375]
Using comet version 3.1.17 based in Australia creating an experiment object can take up to 1 minute, my network speeds are quite fast ~100mb/s so I don't think its network speed.

```
    start = time.time()
    # create comet experiment
    experiment = Experiment(
        api_key=config["comet_api"],
        project_name=config["comet_project"],
        workspace=config["comet_workspace"],
        auto_param_logging=False,
    )
    end = time.time()
    print(end - start)
```
```
52.54585528373718
```

Is there anything I can do to speed this up? This on Ubuntu 20.04 LTS via WSL 2

**Comment by dsblank** [comment]
@lleewwiiss If you know how to use Python Profiling, it would be useful to know exactly where the slow down is occurring. 

Some things to try:

1. If your code is on a very large git repo, it might be taking some time to gather the git metadata or git patch. You might try: `Experiment(log_git_metadata=False)` and/or `Experiment(log_git_patch=False)`. You'll be turning off the connection to your repo though.
2. There are some other parameters to turn off particular logging, including `log_env_details` (controls GPU, CPU, and host logging)
3. In a pinch, you could use `OfflineExperiment()` and then `comet upload` afterwards. You won't be able to see live updates in the comet.ml GUI, but you will have all of the information, and may save some time if it is related to networking.

**Comment by lleewwiiss** [comment]
1. seemed to fix my problems, thank you for the suggestion, will have to look into a work around so i don't lose reproducability functionality.
