### ISSUE TITLE
log_metric tracking epoch even though None argument is passed

### ISSUE THREAD

**Issue by potipot** [comet-ml/issue-tracking#376]
I'm trying to manually track my metrics. Tracking both step and epoch for a single data point results in bumpy charts when switching from `step` to `epoch` view. This happens because comet plots many datapoints for the same epoch (instead of taking the average or other value of an array). I attach a view of the resulting charts:

![batch_loss_step](https://user-images.githubusercontent.com/52150545/91982729-f7cc6b80-ed2a-11ea-97ef-38020176ceae.jpeg)

![batch_loss_epoch](https://user-images.githubusercontent.com/52150545/91982750-0155d380-ed2b-11ea-844b-7808efa08aa6.jpeg)

I tried to use a walkaround to log separately datapoints with `step` specified and `epoch` set to `None`, and the other way round for epoch tracking. The issue here is that comet still records epoch value for a metric point when `epoch=None` is passed. 

I  set up my experiment with 
```python
experiment = Experiment(api_key=API_KEY project_name=PROJECT_NAME, auto_param_logging=False, auto_metric_logging=False)
````
My tracker callback is the following:
```python
    def on_batch_end(self, last_loss, iteration, epoch, num_batch, **kwargs:Any) ->None:
        if num_batch == 0: self.experiment.log_metric('batch_loss', last_loss, step=iteration, epoch=epoch, include_context=True)
        self.experiment.log_metric('batch_loss', last_loss, step=iteration, epoch=None, include_context=True)
```

One solution would be to prevent multiple values per single x plotting but I think the unexpected behavior is a question of its own.

**Comment by potipot** [comment]
One hint might be that even though I'm switching `auto_param_logging=False`, the following parameters appear in my Hyper Parameters card on the web app:
```
curr_epoch 4 
curr_step 4
```

**Comment by Nimrod007** [comment]
Hey @potipot batch_loss is an auto logged metric from keras on each batch (called in `on_batch_end`)
in this case you end up with multiple points for the same epoch.

you can add a callback (like you did) and give the on epoch end a different name (batch_loss_epoch_end) and keep `auto_metric_logging` as `True`

another question is if you have multiple values for the same X data point would you want to:
* pick last (by timestamp)
* average them
* min
* max

probably a config option, for this use case we built custom code panels ,you can code and average, pick last, random etc... and plot that

**Comment by potipot** [comment]
Hey @Nimrod007 I didn't realize that you can create custom code panels - that's a great feature and will solve my problem.
