### ISSUE TITLE
Mypy static checking import fails

### ISSUE THREAD

**Issue by Vozf** [comet-ml/issue-tracking#378]
When using mypy checker for import of comet ml it fails with 
```
/config.py:4: error: Skipping analyzing 'comet_ml': found module but no type hints or library stubs
```
Your code has type hints so this is probabably due to missing `py.typed` file

**Comment by dsblank** [comment]
@Vozf Thanks for the report! How are you running mypy?

**Comment by Vozf** [comment]
`mypy . `
:)

**Comment by dsblank** [comment]
We've added this to our list; item number CH10528.

**Comment by dsblank** [comment]
We've (and will continue to) add mypy support to comet_ml. Should work much better these days.
