### ISSUE TITLE
Code is not logged when using also using Facebook Hydra framework

### ISSUE THREAD

**Issue by bradenkinard** [comet-ml/issue-tracking#379]
[Hydra](https://github.com/facebookresearch/hydra) is a popular framework for composing configuration files. Its typical usage involves using a decorator that points to your configuration yaml file on your main function. However, when this is done, Comet will fail to log the script's code.

The following is a minimal example in which the code is properly logged, as the Hydra configuration is not used:
```
from comet_ml import Experiment


def main():
    experiment = Experiment(project_name="my_project", workspace="my_workspace", log_code=True)
    print("Hello, world")


if __name__ == "__main__":
    main()
```

Once the hydra is used to implement a configuration (here it is an arbitrary YAML file at `configs/config.yaml`), the code will now fail to log to Comet:
```
import hydra
from comet_ml import Experiment


@hydra.main(config_path="configs", config_name="config")
def main(cfg):
    experiment = Experiment(project_name="my_project", workspace="my_workspace", log_code=True)
    print("Hello, world")


if __name__ == "__main__":
    main()
```

**Comment by dsblank** [comment]
@bradenkinard Thanks for the easily-reproducible report! We're taking a look at this.

**Comment by dsblank** [comment]
Yes, we can reproduce the bug. Seems to be related to hydra changing the working directory away from the source code. We're working on both a workaround, and a solution.

**Comment by dsblank** [comment]
Here is a workaround:

```python
import hydra
from comet_ml import Experiment


@hydra.main(config_path="configs", config_name="config")
def main(cfg):
    experiment = Experiment(project_name="my_project", log_code=False)
    experiment.set_code(filename=hydra.utils.to_absolute_path(__file__))
    print("Hello, world")


if __name__ == "__main__":
    main()
```

Working on a solution. Stay tuned...

**Comment by bradenkinard** [comment]
Thanks. The workaround is very helpful. And thanks for the quick response on this!
