### ISSUE TITLE
support pull request creation for empty repo

### ISSUE THREAD

**Issue by Nimrod007** [comet-ml/issue-tracking#38]
### how to reproduce:
* create empty repo (can have a readme file)
* linked comet project with the empty repo
* create comet experiment
* issue a PR from view experiment page
* PR failed.

temporary fix is to move training files inside a folder with repo name and re-run experiment
long term fix is to support empty repo for pull request

**Comment by ceceshao1** [comment]
Closing this issue because we're moving to a new git patch functionality. 

Feel free to stay up to date on our Release Notes [here](https://www.notion.so/cometml/Comet-ml-App-Release-Notes-93d864bcac584360943a73ae9507bcaa) about the new Git capability.
