### ISSUE TITLE
Enhance log_curve docs

### ISSUE THREAD

**Issue by vict0rsch** [comet-ml/issue-tracking#381]
https://www.comet.ml/docs/python-sdk/Experiment/#experimentlog_curve only says "Log timeseries data". I think it would be useful to add that it ends up in the assets folder and that they are not plotted

**Comment by dsblank** [comment]
Good points! Thanks for the suggestion, and we will add those items to the docs.

**Comment by Nimrod007** [comment]
Hi @vict0rsch were working on adding them in the assets folders and plotting them automatically on the panels tab. will update once this is done

**Comment by dsblank** [comment]
More docs in progress: 

* https://www.comet.ml/docs/user-interface/panel-associations/#curve

Need to link these with the SDK calls. Stay tuned.
