### ISSUE TITLE
Failed to setup the std logger (Python 3.8.5)

### ISSUE THREAD

**Issue by khirotaka** [comet-ml/issue-tracking#384]
Dear comet-ml team.

I got
```shell
COMET ERROR: Failed to setup the std logger
```
 when using comet.ml with Python 3.8.

Also, if I ran the code using `tqdm.auto.tqdm`, I got
 
```shell
 /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appears to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

And I also checked on the website and found that three logs were taken per experiment, as shown in the screenshot below.

<img width="1552" alt="comet web page" src="https://user-images.githubusercontent.com/24205015/95081059-f63ffa00-0753-11eb-9d1b-314881f52200.png">

## Expected behavior
1. record the results of one experiment per experiment.
2. display a summary at the end of the experiment

## Environment

- Comet.ml version: 3.2.3
- Python version: 3.8.5
- OS: macOS 10.15.7
- Other: PyTorch v1.6, Poetry v1.1.0

## Error messages, stack traces, or logs

```shell
user@user$ python test_code.py
COMET ERROR: Failed to setup the std logger
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/XXXXXXXXXXXXX

COMET INFO: Uploading stats to Comet before program termination (may take several seconds)
user@user$ /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

```

## Reproducible examples (optional)

```python
# test_code.py
from comet_ml import Experiment
from tqdm.auto import tqdm
import torch
import torch.nn as nn
import torch.optim as optim


experiment = Experiment(project_name="test_code")

model = nn.Linear(5, 5)
optimizer = optim.Adam(model.parameters())
criterion = nn.CrossEntropyLoss()

data = torch.randn(512, 5)
targets = torch.randint(5, size=(512, ))


for epoch in tqdm(range(100)):
    optimizer.zero_grad()
    out = model(data)
    loss = criterion(out, targets)
    loss.backward()
    optimizer.step()


```

## Additional context (optional)

There was no problem with Python 3.7.9.

**Comment by dsblank** [comment]
@khirotaka Thanks for the report and reproducible example. We're looking into this.

**Comment by dsblank** [comment]
Due to issues with the default native output logger with Python 3.8 and MacOS, we've set the default to be "simple" for now. See: https://www.comet.ml/docs/python-sdk/releases/#release-3212

We are continuing to look for a better solution.
