### ISSUE TITLE
SpaCy V3 Comet Logger

### ISSUE THREAD

**Issue by ynouri** [comet-ml/issue-tracking#387]
SpaCy is a widely used tool in the NLP space, and the version 3 of the package is coming out soon with a bunch of new features:
https://explosion.ai/blog/spacy-v3-nightly

Among the new features, SpaCy offers a modular integration for experiment tracking tools in their `training.loggers` module. As of November 2020, they offer the following loggers out of the box:
* A regular console logger: `spacy.ConsoleLogger.v1`
* An integration with Weight & Biases: `spacy.WandbLogger.v1`

It would be awesome if Comet had an integration available out of the box in the SpaCy package too!

For more details, see:
* API reference: https://nightly.spacy.io/api/top-level#WandbLogger
* Custom logger example: https://nightly.spacy.io/usage/training#custom-logging
* Github source for 3.0.0rc2: https://github.com/explosion/spaCy/blob/v3.0.0rc2/spacy/training/loggers.py#L104

**Comment by nikolaskaris** [comment]
Hi @ynouri thanks for suggesting this integration. Letting you know it's in the roadmap and will be completed soon!
