### ISSUE TITLE
Default graphs not showing correctly multiple updated values for epoch

### ISSUE THREAD

**Issue by potipot** [comet-ml/issue-tracking#388]
Hi
When working on warm restarts in my experiments I noticed that default comet graphs don't correctly display metric values for overlapping epochs. Eg. when I update some metric values on a second, third training the values displayed are randomly chosen from the logged metrics.

I'll display it with an example:
```python
from comet_ml import Experiment, ExistingExperiment
from comet_ml.api import API, APIExperiment

import pandas as pd

# here doing a first training
experiment = Experiment(project_name="test", disabled=False, auto_metric_logging=False)
experiment.set_name('overlapping_3.2.7')
for i in range(100):
    experiment.log_metric('test_metric', i**2/100, epoch=i, include_context=False)
experiment.end()

# next doing a warm restart and re-training
experiment = ExistingExperiment(previous_experiment=experiment.id, disabled=False, auto_metric_logging=False)
for i in range(50, 100):
    experiment.log_metric('test_metric', i*0.5/100, epoch=i, include_context=False)
experiment.end()

# and finally fine-tuning
experiment = ExistingExperiment(previous_experiment=experiment.id, disabled=False, auto_metric_logging=False)
for i in range(75, 100):
    experiment.log_metric('test_metric', i**1.5/100, epoch=i, include_context=False)
experiment.end()
```

Logged metric generates a following graph:
![test_metric](https://user-images.githubusercontent.com/52150545/101461415-24e87580-393b-11eb-8780-a0b13e3c6224.jpeg)

However, checking experiment data with APIExperiment shows that data is logged as expected:
```python
api_experiment = APIExperiment(previous_experiment=experiment.id)
metrics = api_experiment.get_metrics('test_metric')
df = pd.DataFrame(metrics)
df[df.epoch>95]
```
![image](https://user-images.githubusercontent.com/52150545/101461764-a5a77180-393b-11eb-9fb7-69908e3c791f.png)

So the problem might lay in the graph selecting the right (freshest I imagine) value to display.
Here is a link to example [experiment](https://www.comet.ml/potipot/test/507d9da87eb94b6b90496b65a28e7ab4?experiment-tab=chart&showOutliers=true&smoothing=0&transformY=smoothing&viewId=BDKFHHURRKKieMGP0i5MJDVzQ&xAxis=epoch).

**Comment by Nimrod007** [comment]
Hi @potipot Thanks for reporting. 
We pick the last point on each epoch and display that on the chart. (since they share the same X axis point)

steps and timestamps are all shown.

hope this answers your question.

**Comment by potipot** [comment]
I posted this issue because that expected behavior doesn't always work. If it was so, the spikes wouldn't appear

**Comment by Nimrod007** [comment]
Hey @potipot Im not sure I understand, lets take an example (epoch 96)
metric value:
* 92.16
* 0.48
* 9.406

we have 3 Y values for the save X value (epoch 96) only 1 is displayed (seems like `92.16`) 
what would you expect to see in this case ? (first point, last point, avg ? mean ?) 

in addition you can rename your metrics on each warm restart or even create a new experiment so charts wont overlap and you can have a more fine grained look on each attempt.

**Comment by potipot** [comment]
In this case I would expect to see the metric with the freshest timestamp. Yes I could name another metric but that would disenable me from using common plot for all experiments in the "panels" section. 
For now I just decided to start new experiments whenever I do a warm restart but the issue with unexpected value display remains.

**Comment by Nimrod007** [comment]
@potipot you can plot multiple metrics on the same plot in the panel section
![my-team_123123__β_β_β_β](https://user-images.githubusercontent.com/3535799/102080460-2b815c00-3e17-11eb-82ad-f1eaa7251541.jpg)


Ill take a look at this, we are supposed to pick the `last` metric (by timestamp) @Camru please take a look

**Comment by potipot** [comment]
@Nimrod007 thanks for the workaround! Looking forward to updates on this

**Comment by Nimrod007** [comment]
Hi @potipot , also when using the line chart panel, when you select X axis value from the time series options (time, epoch, step etc...) you can pick the aggregation function :
![my-team_new-tags](https://user-images.githubusercontent.com/3535799/102087785-b74cb580-3e22-11eb-83a9-012e2f9e0d76.jpg)

**Comment by potipot** [comment]
Thanks, when manually creating a panel, the graph is displayed as expected. I stumbled upon the issue reported initially, when using automatically generated panels.

**Comment by Nimrod007** [comment]
got it, you are referring to the single experiment page charts tab! 
![my-team_new-tags](https://user-images.githubusercontent.com/3535799/102096172-144d6900-3e2d-11eb-8ff1-b9aa131118ee.jpg)

this is probably a bug!
will take a look into this and fix 
Thanks again for letting us know

**Comment by potipot** [comment]
I accidentaly archived the originally linked experiment but made it available again, so you can take a look here: https://www.comet.ml/potipot/test/507d9da87eb94b6b90496b65a28e7ab4?experiment-tab=chart&showOutliers=true&smoothing=0&transformY=smoothing&viewId=BDKFHHURRKKieMGP0i5MJDVzQ&xAxis=epoch
