### ISSUE TITLE
Incompatible with Swift for Tensorflow Python Interoperability

### ISSUE THREAD

**Issue by xanderdunn** [comet-ml/issue-tracking#389]
I am attempting to use comet-ml from [Swift for Tensorflow](https://www.tensorflow.org/swift) via its [Python interoperability](https://www.tensorflow.org/swift/tutorials/python_interoperability). This works with neptune.ai and wandb. With comet the experiment is created and shows up in the web dashboard, but no parameters or metrics ever appear in the dashboard.  Here is an example: 
```swift
        let comet = Python.import("comet_ml")
        let experiment = comet.Experiment(api_key: "MY_KEY",
                                          project_name: "my_project",
                                          workspace: "xanderdunn")
        experiment.log_parameter("test", 123)
        for i in (0..<10) {
            sleep(1)
            experiment.log_metric(name: "test_metric", epoch: i, value: Double.random(in: 0...1.0))
        }
```
This produces the output:
```
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/xanderdunn/my_project/b59fcedfd62f40fa97c1e068f9c76af6
```
This experiment does indeed show up in the dashboard, but the logged test parameter and test_metric never show up. On long training runs I see the dashboard shows a green checkmark with "experiment finished running" after just a handful of seconds, even before the first epoch has completed.

This appears to be specific to running comet-ml from within Swift. When I perform the same program in a Python script, it works:
```python
#!/usr/bin/env python3

import time
import random

from comet_ml import Experiment

experiment = Experiment(api_key="MY_KEY",
                              project_name="my_project",
                              workspace="xanderdunn")

experiment.log_parameter("test", 123)
for i in range(0, 10):
    time.sleep(1)
    experiment.log_metric("test_metric", random.uniform(0.0, 1.0))
```
The output:
```
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/xanderdunn/my_project/38e1a40f764b43d1b7570e52fb60792c

COMET INFO: ---------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     url                   : https://www.comet.ml/xanderdunn/my_project/38e1a40f764b43d1b7570e52fb60792c
COMET INFO:   Metrics [count] (min, max):
COMET INFO:     test_metric [10] : (0.015929073289666418, 0.8472326129268148)
COMET INFO:   Parameters:
COMET INFO:     test : 123
COMET INFO:   Uploads:
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (2 MB)
COMET INFO:     installed packages       : 1
COMET INFO:     os packages              : 1
COMET INFO: ---------------------------
COMET INFO: Uploading stats to Comet before program termination (may take several seconds)
```
Indeed, the parameter and metric show up without issue In the online dashboard.

Python 3.7.9. comet-ml 3.2.9. Swift for Tensorflow 0.12. Ubuntu 18.04. GCP virtual machine with full outbound network access and whitelisted inbound network access.

**Comment by Nimrod007** [comment]
Hi @xanderdunn thanks for reporting this, can you run in debug and share the log with us ? https://www.comet.ml/docs/python-sdk/advanced/#troubleshooting

**Comment by dsblank** [comment]
Closing due to lack of information to diagnose issue. Please re-open if you have more info. Thanks!
