### ISSUE TITLE
Comet breaks Keras's progress bar

### ISSUE THREAD

**Issue by alkamid** [comet-ml/issue-tracking#39]
When using `comet_ml`, the Keras progress bar refreshes with every minibatch, as if the `end='\r'` parameter was ignored in `print()`:

```
1/30 [>.............................] - ETA: 45s - loss: -0.2396
 2/30 [=>............................] - ETA: 43s - loss: -0.2406
 3/30 [==>...........................] - ETA: 42s - loss: -0.2410
```
FWIW, I'm using `multi_gpu_model` in Keras.

**Comment by Nimrod007** [comment]
Hi , is this view from the IDE or from Terminal ? 

<img width="454" alt="1__root_client-lib-py3_____ssh_" src="https://user-images.githubusercontent.com/3535799/39764719-3a2a28b0-52ae-11e8-8280-279d20851c25.png">

**Comment by alkamid** [comment]
Terminal when `ssh`d into a remote server.

**Comment by ptschandl** [comment]
I have a similar issue when using `tqdm` for epoch and training_loader tracking in `pytorch`.
On the Comet-ML output page of an experiment, the "return" command of `tqdm` seems to be ignored.

<img width="457" alt="output_breaks" src="https://user-images.githubusercontent.com/17539789/40891799-ef2228c0-6740-11e8-991b-466479044509.png">

The progress bar on the terminal itself looks fine.

**Comment by ceceshao1** [comment]
Thank you to both of you @ptschandl + @alkamid for reporting this - marked it as a bug! I'll update both of you when it's fixed 👍

**Comment by alkamid** [comment]
@ceceshao1 It's been a while since this was reported, and this is still an issue in version 1.0.22. Were you able to reproduce this? I'm happy to help debugging.

**Comment by gidim** [comment]
@alkamid this is a tricky one to fix based on the way keras progbar is implemented.
Given that this doesn't affect functionality in any case we're listing this one as low priority.

**Comment by PetrochukM** [comment]
Hi encountering this too...

It's limiting in a UX way the logs are flooded with the progress bar updates:
![image](https://user-images.githubusercontent.com/7424737/48747295-ba671e80-ec27-11e8-89b9-62af400f437a.png)

**Comment by nlynn12** [comment]
Still an issue. @ceceshao1 what's the status on this?

**Comment by gidim** [comment]
Hi @nlynn12! Thanks for checking in
The way the progress bar is implemented in keras makes it very hard to fix. We can rewrite our own progress bar but that seems unproductive. Most of our users found the charts more useful than the progress bar. 

Is it the "noise" in stdout that's bothering you or the usability of the progress bar?

**Comment by nlynn12** [comment]
Hi @gidim 
So, the output in the terminal wouldn't annoy me as much if there were some way that I could see the progress of my experiments in the GUI as I've requested in #245.

**Comment by davidparks21** [comment]
In base tensorflow I've been using a python based progressbar: https://pypi.org/project/progress/

This also breaks with comet.ml, as soon as I add `Experiment(...)` the progress bar fails, remove the experiment and it works.

**Comment by gidim** [comment]
@davidparks21  - yes you can disable stdout logging. From the docs:
```
auto_output_logging: Default("native") - allows you to select which output logging mode to use. The default is "native" which will log all output even when it originated from a C native library. You can also pass "simple" which will work only for output made by Python code. If you want to disable automatic output logging, you can pass None.
```

**Comment by dsblank** [comment]
I believe that this issue has been noted on our log term planning list, and a work-around provided for the short term.

Thanks for reporting!

**Comment by alkamid** [comment]
It looks like this is fixed in Comet 3.0 and Keras 2.3.1.

**Comment by el3ment** [comment]
What exactly is comet doing with stdout/stderr in the "native" setting? I also have some really unusual behavior with a custom tqdm and I could possibly fix if I knew how it was redirecting things in the "native" setting (simple works fine -- which I imagine is just redirecting sys.stdout/stderr?)

**Comment by dsblank** [comment]
@el3ment The "native" logger does some fancy stuff to capture low-level output. Basically, it replaces sys.stdout with a non-standard object, which makes it hard to "fix".
