### ISSUE TITLE
Line plot not showing correct legend values in report

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#390]
When making a report, line chart doesn't show the correct legend values in report. It shows correct when editing the plot, but when clicking done, it overrides in the visualization with the experiment name.

When clicking edit option
![image](https://user-images.githubusercontent.com/31376482/105110739-0d55ee00-5a9e-11eb-98da-c1400a27cb11.png)

After clicking done
![image](https://user-images.githubusercontent.com/31376482/105110846-5312b680-5a9e-11eb-9060-20bc26f77cce.png)

If I click edit again, the correct value is selected as legend keys, and the same image as the previous one is displayed, with the correct values in the legend.

**Comment by dsblank** [comment]
Thanks for the report. We are looking into this.

**Comment by dsblank** [comment]
@george-gca We made some enhancements to the plot UI. Is this still an issue for you?

**Comment by george-gca** [comment]
It fixed, thanks.
