### ISSUE TITLE
Add scale option for individual attributes in parallel coordinates graph

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#391]
In this kind of plot would be useful to have an option to select scale for individual attributes.
![image](https://user-images.githubusercontent.com/31376482/105191583-05d22b80-5b16-11eb-8473-972ed9b8d2fa.png)
As shown in this example, policy_lr and vf_lr are variables in log scale, with values varying from 0.1 to 0.00001. The visualization in linear scale as it is make its differentiation impossible.

**Comment by dsblank** [comment]
That would be handy. Adding this to our list to explore. Thanks!
