### ISSUE TITLE
Unable to edit custom panels in report

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#392]
I have made a report with custom panels. I've updated their code for another report in the past, but forgot to update them in this specific report. I opened the report in edit mode, and click "edit" in the options, but nothing happens.

![image](https://user-images.githubusercontent.com/31376482/107290721-ca0bf100-6a45-11eb-8081-fe79f50e5765.png)

**Comment by dsblank** [comment]
Thanks for reporting! We have a fix for this going to our production server very soon (later today or tomorrow).

**Comment by george-gca** [comment]
It fixed it. Thanks.
