### ISSUE TITLE
Order of compare on Github

### ISSUE THREAD

**Issue by lleewwiiss** [comet-ml/issue-tracking#393]
This may be an assumption but experiments listed on the comet dashboard are usually sorted in newest to oldest (at least for me), so when doing the compare on Github it shows no changes, and you have to reverse the commit hashes in the URL to see actual changes. Would it be possible to swap them, so it's `newer...older` in the URL?

**Comment by dsblank** [comment]
@lleewwiiss Can you post an image/text of what part of the UI/url that you mean? You can sort the table on the Project in any order you wish. Not sure I understand the connection to github.

**Comment by dsblank** [comment]
Closing due to lack of info. Please re-open if you have additional data. Thanks!
