### ISSUE TITLE
Error when duplicating report

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#394]
I have a custom report that I want to create a different version of it. I click in duplicate, rename it (or use the default name), press save, and it throws a `There was an error duplicating your report`.

**Comment by dsblank** [comment]
@george-gca Thanks for reporting... we're looking into it.

**Comment by dsblank** [comment]
We've been able to replicate the issue. Working on a resolution...

**Comment by dsblank** [comment]
Solution has been found, and is being tested. Scheduled for release on Thursday if all goes well. Thanks again for reporting!

**Comment by aviadr1** [comment]
Hey @george-gca , I'm Aviad, Head of Product at comet.ml, I noticed you opened a few valueable UX requests, i'd love to have the opportunity to chat, hear your comet usecase and get any feedback you might have on the product. when is the best time and the best way to reach you?

Regards,
Aviad Rozenhek
Head of Product @ comet.ml

**Comment by george-gca** [comment]
Hi @aviadr1, you can contact me at george.gcac at gmail. We can continue the conversation there.

**Comment by george-gca** [comment]
Just tried again to duplicate report and it worked. Closing this issue.
