### ISSUE TITLE
Reorder columns in Customize Columns

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#396]
When I am customizing which columns should be shown in experiments table view, it would be nice to be able to change their orders without having to delete and re-add them again. For example, if I wanted my metric (DIV2K/MS-SSIM) to be the first column and keep the rest right after, I'd have to delete the rest and re-add them again.
![image](https://user-images.githubusercontent.com/31376482/108440958-e4f31800-7232-11eb-905f-06c7aef3641e.png)

**Comment by dsblank** [comment]
@george-gca Yes, good idea and it is on out list.

**Comment by aviadr1** [comment]
internal ticket 9839

**Comment by aviadr1** [comment]
workaround: you can drag-to-reorder columns in the table itself.

**Comment by george-gca** [comment]
Wow, haven't tried that. Good to know.

**Comment by george-gca** [comment]
@aviadr1 don't know if you saw it, but I answered you in the other bug
