### ISSUE TITLE
[Feature Request] Slider value small adjustment

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#398]
It would be nice if in the sliders (e.g. when choosing Y-axis smoothing)

![image](https://user-images.githubusercontent.com/31376482/109535753-add6ff00-7a9b-11eb-8f51-4bb286b1156c.png)

we could do some unitary changes. I know that it is possible using the keyboard left and right arrows, but a clickable solution would be useful. A few suggestions are adding some buttons to the text field

![image](https://user-images.githubusercontent.com/31376482/109536667-c4ca2100-7a9c-11eb-9875-9f70006dcc37.png)

or slider

![image](https://user-images.githubusercontent.com/31376482/109536714-d9a6b480-7a9c-11eb-8f3a-56ce7c562bba.png)

**Comment by dsblank** [comment]
Thanks for the suggestions! Passing these along to the frontend design team.

**Comment by dsblank** [comment]
This has been added to the TODO list.
