### ISSUE TITLE
Chart X-axis going to step=epoch after each epoch

### ISSUE THREAD

**Issue by alkamid** [comet-ml/issue-tracking#40]
Again, with `multi_gpu_model` (haven't tried with normal model) I get the following chart if using "steps" as X axis:
![chart steps](https://user-images.githubusercontent.com/703479/39576605-99a9897e-4ed6-11e8-824d-7b8d31128a41.png)
I looks like it's going back to step=epoch after each epoch, i.e. after the first epoch it logs the loss with step=0, then logs all the subsequent steps correctly, then again goes back to the left side of X axis. It makes the chart unreadable. "Wall time" on X axis works fine:
![chart wall time](https://user-images.githubusercontent.com/703479/39576669-dc4fd710-4ed6-11e8-9c40-3f876a459621.png)

**Comment by Nimrod007** [comment]
Hi @alkamid , are you using TensorBoard ?

**Comment by alkamid** [comment]
Yes, I am.

**Comment by Nimrod007** [comment]
we are working on a fix for this issue - see https://github.com/comet-ml/issue-tracking/issues/22
closing this issue. will update once resolved.
