### ISSUE TITLE
Code refreshing when pressing `s` during custom panel edit

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#400]
I am trying to edit a new custom panel starting from a duplicate. I am trying to add a new option to the panel, named `max_epochs`, but everytime I press the `s` key it refreshes the code, deleting some of the part that I already typed, like
![image](https://user-images.githubusercontent.com/31376482/110143084-9bb7d200-7db5-11eb-9418-ece3682a967c.png)
when I press `s` to write `epochs` it goes to
![image](https://user-images.githubusercontent.com/31376482/110143204-bdb15480-7db5-11eb-883d-f8cffe910c06.png)

To be able to type the `s` there I currently have to copy the char and paste it when I need it.

PS: this happens sporadically, but enough to make it annoying. Don't know it this happens when the internet is throttling.

**Comment by dsblank** [comment]
> have to copy the char and paste it when I need it.

Yes, that would be very annoying! Thanks for reporting... we're on it!

**Comment by dsblank** [comment]
What browser/version are you using?

**Comment by george-gca** [comment]
Google Chrome Version 89.0.4389.72 (Official Build) (64-bit) on Ubuntu 20.04.2 LTS

It appears that this happens if I don't save or run the code in a while.

**Comment by dsblank** [comment]
Thank you; that is useful. The engineering team is looking into it.

**Comment by dsblank** [comment]
Should be fixed now. Please let us know if you have any issues.
