### ISSUE TITLE
[Feature Request] Log File Viewer

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#401]
It would be great if Comet had a log file viewer with syntax highlight support, like [lnav](https://github.com/tstack/lnav).

When I am running my experiments I save log files (generated with python built-in logging) for later checking if anything goes wrong and upload them, but reading them on Comet is currently not very useful. The file is open in a small side view, so usually I download it to read on my pc.
![image](https://user-images.githubusercontent.com/31376482/110249184-b031d100-7f53-11eb-8732-1615d6649502.png)

**Comment by dsblank** [comment]
Noted; added to our list. Thanks for the suggestion!
