### ISSUE TITLE
[Feature Request] Let user decide max size of name in plot

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#403]
Currently in the plots the max size of the experiments' names (when using parameters) is decided by Comet

![image](https://user-images.githubusercontent.com/31376482/111494291-1a4d3180-871d-11eb-8ba7-5026197ecabb.png)

but it would be useful if I could set manually the max allowed size and I could scroll right like when I use experiments names that are too long.

![image](https://user-images.githubusercontent.com/31376482/111494411-3224b580-871d-11eb-871a-33029132430b.png)

**Comment by dsblank** [comment]
Added to our list; thanks!
