### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Prateekkalkonda** [comet-ml/issue-tracking#404]
import IPython.display as ipd
import comet
#import comet_ml
import numpy as np
import pandas as pd
import librosa
import matplotlib.pyplot as plt
from comet_ml import Experiment
from scipy.io import wavfile as wav
from sklearn import metrics 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split 
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import Adam
from keras.utils import to_categorical

experiment = Experiment(
    api_key="l8nz3MHq7zdRr696oWNf8u0hT",
    project_name="safe",
    workspace="prateekkalkonda",
)

df = pd.read_csv('D:\\PUPILmesh\\Rail_matlab\\fan\\tet\\book1.csv')# Create a list of the class labels
labels = list(df['class'].unique())
# Let's grab a single audio file from each class
files = dict()
for i in range(len(labels)):
    tmp = df[df['class'] == labels[i]][:1].reset_index()
    path = 'D:\\PUPILmesh\\Rail_matlab\\fan\\tet{}\\{}'.format(tmp['tet'][0], tmp['slice_file_name'][0])
    files[labels[i]] = path

ImportError: You must import Comet before these modules: sklearn, tensorflow, tensorboard, keras

please tell me how to remove error

**Comment by dsblank** [comment]
Move the line:

```python
from comet_ml import Experiment
```

to the top.

**Comment by Prateekkalkonda** [comment]
I tried that also but no change

**Comment by dsblank** [comment]
How are you running the code?

This works for me:

```python
# file issue.py
from comet_ml import Experiment

import IPython.display as ipd
import numpy as np
import pandas as pd
#import librosa
import matplotlib.pyplot as plt
from scipy.io import wavfile as wav
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import Adam
from keras.utils import to_categorical

experiment = Experiment()
```

Running the code:

```
python issue.py
```

Also, you should change your Comet API key after publicly posting it.

**Comment by Prateekkalkonda** [comment]
> How are you running the code?
> 
> This works for me:
> 
> ```python
> # file issue.py
> from comet_ml import Experiment
> 
> import IPython.display as ipd
> import numpy as np
> import pandas as pd
> #import librosa
> import matplotlib.pyplot as plt
> from scipy.io import wavfile as wav
> from sklearn import metrics
> from sklearn.preprocessing import LabelEncoder
> from sklearn.model_selection import train_test_split
> from keras.models import Sequential
> from keras.layers import Dense, Dropout, Activation
> from keras.optimizers import Adam
> from keras.utils import to_categorical
> 
> experiment = Experiment()
> ```
> 
> Running the code:
> 
> ```
> python issue.py
> ```
> 
> Also, you should change your Comet API key after publicly posting it.

from comet_ml import Experiment

import IPython.display as ipd
import numpy as np
import pandas as pd
import librosa
import matplotlib.pyplot as plt
from scipy.io import wavfile as wav
from sklearn import metrics 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split 
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import Adam
from keras.utils import to_categorical


experiment = Experiment(
    api_key="l8nz3MHq7zdRr696oWNf8u0hT",
    project_name="safe",
    workspace="prateekkalkonda",
)


df = pd.read_csv('D:\\PUPILmesh\\Rail_matlab\\fan\\tet\\book1.csv')# Create a list of the class labels
labels = list(df['class'].unique())
# Let's grab a single audio file from each class
files = dict()
for i in range(len(labels)):
    tmp = df[df['class'] == labels[i]][:1].reset_index()
    path = 'D:\\PUPILmesh\\Rail_matlab\\fan\\tet{}\\{}'.format(tmp['tet'][0], tmp['slice_file_name'][0])
    files[labels[i]] = path


This is how i was running

**Comment by Prateekkalkonda** [comment]
> > How are you running the code?
> > This works for me:
> > ```python
> > # file issue.py
> > from comet_ml import Experiment
> > 
> > import IPython.display as ipd
> > import numpy as np
> > import pandas as pd
> > #import librosa
> > import matplotlib.pyplot as plt
> > from scipy.io import wavfile as wav
> > from sklearn import metrics
> > from sklearn.preprocessing import LabelEncoder
> > from sklearn.model_selection import train_test_split
> > from keras.models import Sequential
> > from keras.layers import Dense, Dropout, Activation
> > from keras.optimizers import Adam
> > from keras.utils import to_categorical
> > 
> > experiment = Experiment()
> > ```
> > 
> > 
> > Running the code:
> > ```
> > python issue.py
> > ```
> > 
> > 
> > Also, you should change your Comet API key after publicly posting it.
> 
> from comet_ml import Experiment
> 
> import IPython.display as ipd
> import numpy as np
> import pandas as pd
> import librosa
> import matplotlib.pyplot as plt
> from scipy.io import wavfile as wav
> from sklearn import metrics
> from sklearn.preprocessing import LabelEncoder
> from sklearn.model_selection import train_test_split
> from keras.models import Sequential
> from keras.layers import Dense, Dropout, Activation
> from keras.optimizers import Adam
> from keras.utils import to_categorical
> 
> experiment = Experiment(
> api_key="l8nz3MHq7zdRr696oWNf8u0hT",
> project_name="safe",
> workspace="prateekkalkonda",
> )
> 
> df = pd.read_csv('D:\PUPILmesh\Rail_matlab\fan\tet\book1.csv')# Create a list of the class labels
> labels = list(df['class'].unique())
> 
> # Let's grab a single audio file from each class
> files = dict()
> for i in range(len(labels)):
> tmp = df[df['class'] == labels[i]][:1].reset_index()
> path = 'D:\PUPILmesh\Rail_matlab\fan\tet{}\{}'.format(tmp['tet'][0], tmp['slice_file_name'][0])
> files[labels[i]] = path
> 
> This is how i was running

I am trying in Jupyter

**Comment by dsblank** [comment]
Perhaps you didn't restart your kernel? Or perhaps you have Jupyter configured to import some libraries on startup? comet_ml works well in Jupyter, so it must be something with your local install or use.
