### ISSUE TITLE
[Feature Request] Adding metric sample selection (e.g. max, min, last, first) to web UI columns

### ISSUE THREAD

**Issue by DeepOzean** [comet-ml/issue-tracking#405]
It would be great, if you can select which sample point to show in the columns of the Web UI. During a run, metrics for each epoch are usually saved. Usually you want to see the best performance of a run (min or max depending on metric), not the last (currently shown in web UI). Then you can easily sort the runs based on that to see which hyperparameters works best.

**Comment by dsblank** [comment]
There is now a Custom Panel for displaying Optimizer runs, and you can pin an experiment (best so far) to show with other experiments. Does that help address your request?

**Comment by CharlesGaydon** [comment]
To me this is a similar feature request to https://github.com/comet-ml/issue-tracking/issues/218.
Has this really been implemented?
Right now we would need to hack into the logging in order to order experiments by max metric or min loss.
