### ISSUE TITLE
Opening an experiment row breaks the charts in other experiment

### ISSUE THREAD

**Issue by lemairecarl** [comet-ml/issue-tracking#406]
Steps:

1. Go to https://www.comet.ml/lemairecarl/radrec/view/new
2. Click to the down arrow next to the checkbox for the first experiment to open the details "in-place"
3. Do the same for the experiment below

Expected: The charts show correctly in both "open" experiments

Actual: The charts only show correctly in the last open experiment; for the other(s), it ends of saying "No data for this chart".

I use a saved view with combined line charts, seems like it was working before I used that.

**Comment by lemairecarl** [comment]
There seem to be weird stuff happening today. Like, I'm seeing new experiments running inside old projects (the running experiments are from another project, they shoudn't be there). And that seems to affect the panels. When first entering the old project, the panels say "no data for this chart", but when I reverse the sort order (hiding the weird running experiments), the panels show.

**Comment by dsblank** [comment]
Looking into this...

**Comment by dsblank** [comment]
@lemairecarl Can you hard-refresh your browser and see if the issue continues?

**Comment by dsblank** [comment]
If the issue continues, can you send a link to the "new experiments running inside old project" issue?

**Comment by lemairecarl** [comment]
I've disabled the cache, and now it seems that the charts still disappear, but they reappear after about 5 seconds.
Not sure if it's really different after disabling the cache...

**Comment by lemairecarl** [comment]
About the "new experiments running inside old project", it seems that changing the view has nudged the problem away.

Now, about the main issue, it seems related to the custom (saved) view I made in the single experiment page. It seems that this view causes problems in the "project dashboard" (where I can see charts from multiple experiment at once). When setting the default view of the experiment page to "auto generated", the disappearing charts problem doesn't happen.

**Comment by dsblank** [comment]
Ok, thanks for the additional info. We'll take a look at this.

**Comment by dsblank** [comment]
Are you still experiencing this issue?

**Comment by lemairecarl** [comment]
It seems to be fixed. Thanks.
