### ISSUE TITLE
Project view infinite loading screen

### ISSUE THREAD

**Issue by lemairecarl** [comet-ml/issue-tracking#407]
Both the Panels and Experiments sections are displaying "Loading..." for minutes, and seem like they will never actually load.

https://www.comet.ml/lemairecarl/pepseg-abysis-classif/view/qaYZuI5kzKec8q1UTM7xz6Cyk

**Comment by dsblank** [comment]
Thanks for reporting; we'll take a look.

**Comment by dsblank** [comment]
Do you still have this issue?

**Comment by lemairecarl** [comment]
Not sure what was happening on that day of April, but today there doesn't seem to be a problem.
