### ISSUE TITLE
Built-in line chart not working correctly on report

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#408]
Actually, just a copy of #399 since it stopped receiving attention. It happens when I create a set of panels, then duplicate them and just change the metric displayed in all plots. Watch the first plots, then go down the report and come back to the first plots. It will display the second set of plots in the first one. Example of bug [here](https://www.comet.ml/george-gca/super-resolution-experiments/reports/test-report).

**Comment by dsblank** [comment]
Closing this ticket to focus on #399
