### ISSUE TITLE
Link to Open in Embedding Projector not working

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#409]
When I open the `Assets` tab of an experiment, select the asset, click in `View` and then `Open in Embedding Projector`, it is incorrectly generating the url for the embedding, setting `experimentKey%3Dundefined`.

![image](https://user-images.githubusercontent.com/31376482/117370251-8128d480-ae9c-11eb-8caf-8a7f4afdebb6.png)
![image](https://user-images.githubusercontent.com/31376482/117370830-5ab76900-ae9d-11eb-9971-9bb9704ecf59.png)

It works correctly though if I click straight in the button to show in embedding projector next to `View` in the first image.

**Comment by dsblank** [comment]
Thanks for the note! Will fix.
