### ISSUE TITLE
Add option to not show hidden experiments in built-in charts

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#410]
When creating built-in charts, it would be really useful if we could choose to not show hidden experiments in the legends.

![image](https://user-images.githubusercontent.com/31376482/120120414-6bdd5800-c173-11eb-8f1b-ffd1fd8b8dae.png)

Since I have a lot of experiments and already filtered them, it is kinda annoying to see them here in some cases.

**Comment by dsblank** [comment]
Thanks for the feedback! We have a new UI on the horizon that should address this issue.
