### ISSUE TITLE
Fast Dev Run still triggers logging with comet.ml

### ISSUE THREAD

**Issue by half-potato** [comet-ml/issue-tracking#413]
The argument --fast_dev_run is meant to disable logging in pytorch lightning, but it doesn't.
Version:
pytorch_lightning: 1.3.2
comet_ml: 3.12.2

**Comment by dsblank** [comment]
Thanks for the report. Because that is a flag on another project, you should report that there. If you create an issue on pytorch-lightning, could you link it to this one so that we can track it too?
