### ISSUE TITLE
[Feature Request] UI: Delete Artifacts when deleting experiment

### ISSUE THREAD

**Issue by magehrig** [comet-ml/issue-tracking#415]
The deletion of an experiment in the online user interface does not delete the corresponding artifacts. This is really cumbersome because it requires the users to find the artifacts without experiments and delete them manually.

**Request**:
When deleting an experiment, provide the option (e.g. as tickbox) to also delete the corresponding artifacts.

**Comment by dsblank** [comment]
Thanks for the suggestion! This has been added to the list to be considered by the Product Design team [CM-744].

**Comment by dsblank** [comment]
@magehrig Thanks again for the feedback! This feature enhancement is not currently on our roadmap, but may be re-evaluated in the future.
