### ISSUE TITLE
Experiment.clean() not working

### ISSUE THREAD

**Issue by pvardanis** [comet-ml/issue-tracking#416]
Running in `Python 3.7.11` and `comet_ml==3.14.0`.

It seems the clean() method that's supposed to clean the Experiment's loggers doesn't seem to be working. After logging a test metric and running APIExperiment.get_metrics(), I got this output:

```
api_exp = APIExperiment(previous_experiment=experiment_id)
print(api_exp.get_metrics("test_metric"))  # get logged metrics
```

> [{'metricName': 'test_metric1', 'metricValue': '10.0', 'timestamp': 1628857383890, 'step': 1, 'epoch': None, 'runContext': None, 'offset': 12}, {'metricName': 'test_metric1', 'metricValue': '20.0', 'timestamp': 1628857383890, 'step': 2, 'epoch': None, 'runContext': None, 'offset': 15}, {'metricName': 'test_metric1', 'metricValue': '30.0', 'timestamp': 1628857383891, 'step': 3, 'epoch': None, 'runContext': None, 'offset': 18}, {'metricName': 'test_metric1', 'metricValue': '40.0', 'timestamp': 1628857383891, 'step': 4, 'epoch': None, 'runContext': None, 'offset': 21}, {'metricName': 'test_metric1', 'metricValue': '50.0', 'timestamp': 1628857383891, 'step': 5, 'epoch': None, 'runContext': None, 'offset': 24}]

However when I run Experiment.clean(), and repeat the above lines, I still get these values back. Isn't .clean() supposed to clean the loggers? If not, is there any other way to do it?

**Comment by dsblank** [comment]
Actually, `Experiment.clean()` just signals that the experiment has ended, but doesn't wait for all of the uploads to finish. If you want to finish off an experiment, use `Experiment.end()`.

I'm not sure what "clean the loggers" means. The lines you are reporting above are items previously logged and then collected from the Comet server. What are you attempting to do?

**Comment by pvardanis** [comment]
`Clean the experiment loggers, useful in case you want to debug your scripts with IPDB.` 

From that line in the docs I understand that the loggers are emptied (i.e. log metric named 'test_metric1' in my case) and the same variables (that correspond to the parameters seen in comet.ai metrics & graphs tabs) can be used all over again. That way the corresponding values on comet.ml will be reloaded, at least that was my impression. So in overall this would be equivalent to 'resetting' the experiment. 

If this is not the functionality of Experiment.clean(), is there any other way to achieve that? I want to be able to 'reset' somehow the same Experiment (pointing on the same experiment on comet.ml) anytime in my code.

**Comment by dsblank** [comment]
I don't think there is a way to "reset an experiment" in the manner you mean. The best way would simple be to create a new experiment. Would that work for you? There are a few different types of experiments that may be more appropriate:

https://www.comet.ml/docs/python-sdk/experiment-overview/

**Comment by pvardanis** [comment]
Not what I was looking for, but might work as an alternative. Thanks for the prompt reply!
