### ISSUE TITLE
Question - upload interactive image (with bokeh for eg)

### ISSUE THREAD

**Issue by eyalho** [comet-ml/issue-tracking#417]
The confusion matrix is awesome!
Im trying to plot also some interactive 2d visualization such as in 

https://umap-learn.readthedocs.io/en/latest/basic_usage.html

![Screenshot_20210823-003824_Chrome.jpg](https://user-images.githubusercontent.com/53655596/130370853-ffcbaf31-0afd-4dc0-ac31-dbc2f52f10f3.jpg)

Any suggestions how to do it?

**Comment by dsblank** [comment]
@eyalho You can do exactly what you like with Comet Custom Code Panels:

1. https://www.comet.ml/docs/user-interface/gallery/
2. https://www.comet.ml/docs/user-interface/panels/
3. https://www.comet.ml/docs/javascript-sdk/api/
