### ISSUE TITLE
[Feature Request] Option to select all experiments in archived experiments

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#419]
When selecting archived experiments, currently we can select at most the ones shown in the screen (max 25 since this is not customizable), but it would be useful to allow to select all of them (even the ones not currently shown). This is useful when, for example, deleting all archived experiments and you have more than 300 of them.

**Comment by dsblank** [comment]
Thanks! Adding that to our list. 

BTW, you can also delete archived experiments from the comet_ml Python SDK:
https://www.comet.ml/docs/python-sdk/API/#apidelete_experiments
