### ISSUE TITLE
Support for 1e-4 like expression

### ISSUE THREAD

**Issue by sotetsuk** [comet-ml/issue-tracking#42]
Hi, thank you for developing a nice product.

In comet.ml, it uses 0.0001 like expression in dashboard.
And if the number is too small, it is rounded in some precision.
However, we sometimes need the expression with any precision like 1e-4.
Could you consider adding this expression as an option?

Thanks.

**Comment by gidim** [comment]
Thanks for the feedback!
We're looking into this. In the meantime you can always report it as a string.
