### ISSUE TITLE
Error when deleting archived experiments from last page

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#420]
When in last page of archived experiments, deleting all experiments shown results in `This project has no archived experiments.` even though there are more archived experiments and the counter shows the remaining archived experiments.

![2021-08-27_20-17](https://user-images.githubusercontent.com/31376482/131197356-e8f9878e-b9f3-4786-8f2c-0dc4978df70e.png)

**Comment by dsblank** [comment]
Thank you for the report!

**Comment by lemairecarl** [comment]
This is annoying.
