### ISSUE TITLE
Experiment objects seem not to get garbage-collected

### ISSUE THREAD

**Issue by daniel-ziegler** [comet-ml/issue-tracking#423]
I'm calling `Experiment.end()` and don't keep a reference to the `Experiment`, yet it seems to persist.

Since `Experiment` keeps models in `self._storage["torch"]["model"]`, this can cause GPU memory leaks if a script uses multiple models in succession.

This happens with comet_ml==3.15.4

**Comment by dsblank** [comment]
Thanks for reporting this! If experiment.end() cleared _storage, do you think that would be enough to fix this problem for you?

**Comment by daniel-ziegler** [comment]
Yes, that would work!
