### ISSUE TITLE
images added by intercepting tf.summary image should have name

### ISSUE THREAD

**Issue by kretes** [comet-ml/issue-tracking#424]
Currently when we run a tensorflow job and a 
```
tf.summary.image("a_name", png_as_tensor, step=1)
tf.summary.image("a_name", png_as_tensor, step=2)
```
we get a proper grouping by name in tensorboard, but in comet the images are added as a `tmps0ty71mi`  or similar, which therefore makes grouping by name not possible.

We should have the same behaviour as when the images are added explicitly by experiment.log_image()

I found an old issue, where it was said that auto-adding of images is not supported- https://github.com/comet-ml/issue-tracking/issues/228 - however it works now, therefore we should make it work nice.

**Comment by dsblank** [comment]
@kretes Thanks for the report! Yes, "make it work nice" is indeed our goal :) Looking into this issue...

**Comment by dsblank** [comment]
Fixes for this are now under development.
