### ISSUE TITLE
Question - Confusion Matrix 

### ISSUE THREAD

**Issue by f3n1Xx** [comet-ml/issue-tracking#426]
How do you export confusion matrix as a JPEG or SVG?

**Comment by dsblank** [comment]
@f3n1Xx Exporting the confusion matrix is not currently possible. We will add that to our enhancement list! Thanks for the question.

**Comment by f3n1Xx** [comment]
another add-on would be to include a epoch slider to see how confusion matrix is evolving. In the meantime I'll look for alternatives

**Comment by dsblank** [comment]
@f3n1Xx We have a version of the "epoch-slider" in the form of a pull-down menu: if you log different confusion matrices with names like "epoch-100", "epoch-200", ...etc you can select them here:

![Screenshot from 2021-09-27 08-39-26](https://user-images.githubusercontent.com/168568/134940666-4d9f7024-cbf8-4f1d-a7fa-f0d84fa8f00e.png)
