### ISSUE TITLE
log_code=False disables log_git_metadata

### ISSUE THREAD

**Issue by rgaiacs** [comet-ml/issue-tracking#428]
I used

```
comet_ml.Experiment(
        project_name="foo",
        workspace="username",
        log_code=False,
        log_git_metadata=True,
        log_git_patch=True
)
```

and my experiment reports says "No commit available".

When I change it to

```
comet_ml.Experiment(
        project_name="foo",
        workspace="username",
        log_code=True,  # Changed to True
        log_git_metadata=True,
        log_git_patch=True
)
```

I have the Git commit information.

**Comment by robatscandit** [comment]
I propose that this is not only a documentation issue. We would like to log the git metadata (commit hash etc.) but we don't want to log our codebase to comet.

**Comment by robatscandit** [comment]
This has been fixed in the latest release and can be closed imo.
