### ISSUE TITLE
Debug mode for experiments

### ISSUE THREAD

**Issue by janmtl** [comet-ml/issue-tracking#43]
In my current workflow, I rerun my training script when I make changes to it. However, my code isn't perfect and things break during run-time (e.g.: I mistype the key of a pandas column). On these runs, comet still records an experiment and I have to go into the console and delete the incomplete run.

**Could a flag be added to the `Experiment` object to silence all logging to the comet.ml API?** This would make development of scripts much easier as the flag could be removed once the script is in good shape. I understand there's individual flags for some of the other logs, but prevent the creation of runs entirely would be the goal of this flag.

**Comment by Nimrod007** [comment]
taking a look how to implement this (probably adding a constructor param)

**Comment by Nimrod007** [comment]
usage example:
```python
experiment = Experiment(api_key="someKey", disabled=True)
```
available on `v1.0.14` https://pypi.org/project/comet-ml/1.0.14/

**Comment by janmtl** [comment]
This is great. Thanks!
