### ISSUE TITLE
Legend plots don't have line color in new view

### ISSUE THREAD

**Issue by bw4sz** [comet-ml/issue-tracking#437]
## Describe the Bug
When you click into a plot the color of the line is not reflected by the legend, making it harder to match.

## Expected behavior
The line color and legend should be the same color for each group.

## Where is the issue?
- [ ] Comet Python SDK
- [ X] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## Screenshots or GIFs
<img width="1696" alt="Screen Shot 2021-10-26 at 11 14 11 AM" src="https://user-images.githubusercontent.com/1208492/138937003-e9eec33c-79d8-4d68-b8bb-2713946888bb.png">

## Link to Comet Project/Experiment
If applicable, please provide a link to your Comet Project or Experiment. 

## Additional context
I also think the legend text should be bigger.

**Comment by lemairecarl** [comment]
Bug also present in Panels:

![Screenshot from 2021-11-10 17-33-29](https://user-images.githubusercontent.com/13444373/141204741-e45ecdfe-5505-455c-8639-99c246428fe4.png)

**Comment by CharlesGaydon** [comment]
Is there any news on this visualization bug? I have the same issue since the new view and expected it to be corrected by now :octopus:

**Comment by lemairecarl** [comment]
It's been a while. The legends are useless without colors (they just repeat the metric names that are already in the panel title), so you might as well remove them, as they take up space.
