### ISSUE TITLE
"Experiments" button inactive while on a specific experiment view

### ISSUE THREAD

**Issue by CharlesGaydon** [comet-ml/issue-tracking#438]
## Describe the Bug
Clicking on "Experiments" while on the panel for a specific experiment does not move the page to the full listing of experiments.

## Where is the issue?
- [ ] Comet Python SDK
- [X Comet UI (new one)
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
1. Go to UI -> Experiments tab
2. Click on a specific experiment
3. Click again on the Experiments tab
4. Nothing happens

## Screenshots or GIFs
![image](https://user-images.githubusercontent.com/11660435/139090298-2a5faf46-51e0-47b0-a8dc-fbf97a77ee1d.png)

**Comment by CharlesGaydon** [comment]
This is fixed now. Thanks, closing the issue :)

**Comment by austin-kodra** [comment]
Thanks @CharlesGaydon -- just found out this was fixed myself, but thank you for closing :)
