### ISSUE TITLE
Comet ML chart limits number of datapoints viewed

### ISSUE THREAD

**Issue by jarrelscy** [comet-ml/issue-tracking#44]
The chart function is very useful but sometimes limits the number of datapoints displayed. Sometimes it will not display the entire trend and will simply display the last 20 or so points. With long running experiments this is not ideal - is there a way to 'zoom out' or display the entire series? 

I have a currently running project at: 

https://www.comet.ml/jarrelscy/crop/753d855f88654ec3b4ccecfe0277fbbe

This has been running for a while now but only the last 16 or so datapoints are displayed.

**Comment by gidim** [comment]
Thanks @jarrelscy  Good catch on this bug!
We're looking into this and hopefully we can fix this soon.

**Comment by gidim** [comment]
@jarrelscy 
We upgraded our caching infrastructure while your model was training. This caused the charts to only show data points from ~10am EST. Once your experiment will finish the cache will be updated and all the data points will be shown on the UI.

New experiments should not show this behavior. Sorry for the inconvenience and thanks for reporting! Closing this for now.
