### ISSUE TITLE
Allow to configure time The Python SDK has before aborting

### ISSUE THREAD

**Issue by kretes** [comet-ml/issue-tracking#445]
## Is your feature request related to a problem? Please describe.
Using python lib for comet we want to configure the timeout of sending all dangling events.
Currently at the end we see `COMET INFO: The Python SDK has 3600 seconds to finish before aborting...`
Since in some cases - the process hangs and never finishes - we would like to be able to configure the 3600 seconds to a smaller value for better control of the environment.

## Describe the solution you'd like
Since I found from the code that this value should be taken from `comet_ml.config.DEFAULT_STREAMER_MSG_TIMEOUT` I tried altering it before running comet, but that didn't seem to work. Anyway this should be a parameter provided e.g. by an environmental variable.

## Additional context
comet-ml 3.18.1 py 3.9

**Comment by DN6** [comment]
Thank you for the suggestion @kretes. I will loop in the SDK team to consider this option and get back to you.

**Comment by DN6** [comment]
Hello @kretes. I believe that you can configure this timeout by setting the `COMET_TIMEOUT_CLEANING` environment variable. 

```
export COMET_TIMEOUT_CLEANING=<Your Timeout Value>
```

**Comment by kretes** [comment]
Thanks! that works (at least to the point that I see this value in logs).
I understand this should be specified in seconds?

The whole reason around this is that we observe hanging of our training process sometimes, and we would like to ensure comet will not wait long before exiting in any case

**Comment by DN6** [comment]
@kretes Yes the time specified is in seconds. I'm going to close this ticket, since the solution seems to be working for you 👍🏽
