### ISSUE TITLE
How to use Optimizer ID parallelly

### ISSUE THREAD

**Issue by arkhan19** [comet-ml/issue-tracking#447]
## Before Asking:   
- [ ] I have searched the Issue Tracker.   
- [+] I have searched the Documentation.    

## What is your question related to?
- [+] Comet Python SDK
- [ ] Comet UI
- [] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lightning etc.)  

## What is your question?
How to use Optimizer ID parallelly in several execution, so that i can finish all experiments quickly.

## Code
```
Please paste a code snippet if your question requires it!   
```

## What have you tried?
I have used optimizer ID to resume a crashed search.

**Comment by dsblank** [comment]
Note also the documentation: https://www.comet.ml/docs/command-line/#comet-optimize

**Comment by DN6** [comment]
Hello @f3n1Xx. Could you take a look at the docs page that @dsblank has shared here to see if it answers your question on parallelized execution of the Optimizer?
