### ISSUE TITLE
Hyperparmeters are not being logged at times when using with distributed pytorch

### ISSUE THREAD

**Issue by nsriniva03** [comet-ml/issue-tracking#450]
## Describe the Bug

Hello, I am using comet.ml with  distributed pytorch. When the program is executed the model is initialized on N GPUs and comet.ml starts the corresponding N experiments. However, comet.ml is logging the hyperparameters only on some of the GPUs/experiments and not on all. Why would this happen and what does it mean?

## Expected behavior
I would expect the hyperparameters to be logged in all the experiments. 

## Where is the issue?
- [ ] Comet Python SDK
- [ ] Comet UI

## Screenshots or GIFs

![Screen Shot 2021-12-03 at 4 09 40 PM](https://user-images.githubusercontent.com/83607477/144680934-134acc4b-0316-4c54-833d-2f0ea58e3d74.png)

For experiment  typical_root_7164, the hyperparameters are not logged. 

![Screen Shot 2021-12-03 at 4 27 41 PM](https://user-images.githubusercontent.com/83607477/144681262-ca78dc9d-f3ef-4cf7-83d1-dc31b21c4edb.png)

Whereas for experiment surviving_seasoining_1118, the hyperparameters are logged. 

![Screen Shot 2021-12-03 at 4 27 24 PM](https://user-images.githubusercontent.com/83607477/144681340-55851e0c-e183-4044-b0fe-034d7c6b42e1.png)

**Comment by dsblank** [comment]
Do they eventually show up after the experiment has finished running?

**Comment by nsriniva03** [comment]
Since I am not sure about it. I always kill the program and restart it. I do this till all the parameters are visible on all the experiments. But I could let it run and get back to you about it

**Comment by dsblank** [comment]
Some things don't log until the end, so it isn't a good idea to kill an experiment. If at all possible, the experiment should run until completion. If you want, you can call experiment.end() manually in your code.

**Comment by nsriniva03** [comment]
Hi Douglas, 

The parameters are not showing up after the experiment has finished running.

appalling_aracde has not logged any parameters.
![Screen Shot 2021-12-06 at 8 56 27 AM](https://user-images.githubusercontent.com/83607477/144868361-0765fd90-69df-4c36-88e6-5abbb0f6ed49.png)
![Screen Shot 2021-12-06 at 8 57 19 AM](https://user-images.githubusercontent.com/83607477/144868486-717ee4a7-2580-4829-b2e9-12e2200479e7.png)

**Comment by dsblank** [comment]
Some additional questions:

1. The hyperparameters never did show up (even after a browser refresh)? Sometimes the server takes a few minutes to process everything.
2. All of these really ran for 44 hours, 3 minutes, and 30-some seconds? I don't think I've ever seen such consistency across computers for that long. Are they reporting a lot of data over that time, or all at once? An experiment could get throttled on various limits. See: https://www.comet.ml/docs/python-sdk/warnings-errors/#rate-limits
3. Do you have the output captured for the experiment(s) that aren't showing the hyperparameters? I'm wondering if they had connection issues or crashed. Are these links you can share with me in DM? I'm doug@comet.ml
