### ISSUE TITLE
Chart tooltips in diff should show experiment names instead of id

### ISSUE THREAD

**Issue by lemairecarl** [comet-ml/issue-tracking#453]
## Describe the Bug
Since in the diff page (and pretty much everywhere in the new UI) we identify the experiments by their name, instead of ID, the chart tooltips in diff mode should be consistent with that.

What I see now:

```
y: Y_VALUE
x: X_VALUE
METRIC_NAME ( (EXPERIMENT_ID))
```

Also note that the parentheses are doubled, and asymmetric; which drives me crazy. ;)

## Expected behavior

The tooltips should look like this:

```
y: Y_VALUE
x: X_VALUE
METRIC_NAME (EXPERIMENT_NAME)
```

## Where is the issue?
- [ ] Comet Python SDK
- [x] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
1. Diff two experiments
2. Hover over a chart

## Link to Comet Project/Experiment
https://www.comet.ml/lemairecarl/microscopie/221a7f2c8fe04f2481c26515f28d6e88/80187ebafb1140aeadbb2ae38da2a451/compare?experiment-tab=chart&showOutliers=true&smoothing=0&transformY=smoothing&viewId=voqJTkeVr1y7vlJ5gE3jnqCdi&xAxis=epoch

**Comment by DN6** [comment]
Thanks for flagging this @lemairecarl. I've raised the issue with our engineering team. I will update you when a fix is pushed.
