### ISSUE TITLE
[Bug] Panels don't scale appropriately when resizing

### ISSUE THREAD

**Issue by florianblume** [comet-ml/issue-tracking#458]
## Describe the Bug
When adding a panel and then changing its size it doesn't always scale appropriately but for example covers only the leftmost part when scaling to the right, like this for example:

![Screenshot from 2022-02-01 11-26-32](https://user-images.githubusercontent.com/2170192/151952276-258d98a6-ca7c-420f-aba9-53ccc45efca7.png)

When clicking on edit and closing the edit view again, the panel is being reloaded and scales appropriately.

## Expected behavior
Maybe reload the panel directly when resizing, I'm not sure whether there is some technical reason why this isn't implemented.

## Where is the issue?
- [ ] Comet Python SDK
- [X] Comet Javascript SDK
- [X] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
1. Add my publicly available Group Bar Chart v3 (supports grouping by experiment Name)
2. Click on edit layout
3. Resize the panel in the horizontal axis
4. See how it doesn't scale
5. Click on edit of the panel
6. Click on Apply without making any changes
7. The panel should have scaled appropriately

**Comment by DN6** [comment]
Thanks for reporting this @florianblume. I was able to reproduce your issue. Indeed this looks like a big. I'll let the the team know about the behavior and post an update here when a fix has been pushed.

**Comment by DN6** [comment]
Hi @florianblume. We just pushed a fix for this issue. Plotly Panels should resize automatically now.

**Comment by florianblume** [comment]
Cool, will check it out!
