### ISSUE TITLE
[Bug] Panel saving takes longer with every save until nearly freezing

### ISSUE THREAD

**Issue by florianblume** [comet-ml/issue-tracking#459]
## Describe the Bug
Editing a panel and saving it increases the time to save it. At some point the editor becomes unusable. Maybe this has something to do with the history of the panel.

## Expected behavior
Saving should take a second at most.

## Where is the issue?
- [ ] Comet Python SDK
- [X] Comet Javascript SDK
- [X] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
1. Edit a panel
2. Save it multiple times
3. Saving time increases

Happens in Chrome and Firefox.

**Comment by florianblume** [comment]
Apparently reloading the browser helps temporarily until it becomes laggy again.

**Comment by florianblume** [comment]
So this workaround only works in some cases and often the panels cannot be added to the panels view and the browser just crashes.

**Comment by DN6** [comment]
Hello @florianblume. Taking a look into this now. I'll update you if I'm able to reproduce the issue.
