### ISSUE TITLE
OfflineExperiment does NOT record Git metadata

### ISSUE THREAD

**Issue by rgaiacs** [comet-ml/issue-tracking#462]
## Describe the Bug

When I use `OfflineExperiment` instead of `Experiment`, Comet does **not** record Git metadata.

## Expected behavior

`OfflineExperiment` record Git metadata like `Experiment`.

## Where is the issue?
- [X] Comet Python SDK
- [ ] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce

Use

```
    experiment = comet_ml.OfflineExperiment(
        project_name="project-name",
        workspace="workspace",
        log_code=True,
        log_git_metadata=True,
        log_git_patch=True,
        log_graph=False,
        auto_param_logging=False,
        auto_metric_logging=False,
        auto_output_logging=False,
        auto_log_co2=False,
        disabled=False,
        offline_directory="comet/",
    )
```

## Link to Comet Project/Experiment

https://www.comet.ml/raniere-silva/ai-for-radiograph-classification/3937d546c7ed42d0a42c615d8b333c80

**Comment by DN6** [comment]
Hello @rgaiacs. Thanks for flagging.  I Will try to reproduce this and update you here.

**Comment by DN6** [comment]
Hi @rgaiacs. I was unable to reproduce this issue. Would you be able to share a test code snippet to reproduce the issue? Additionally, when running the snippet, could you set Comet to debug mode? 

You will need to set the following environment variables before running your script. 

```
export COMET_LOGGING_FILE=./comet-debug.log
export COMET_LOGGING_FILE_LEVEL=debug
```

**Comment by rgaiacs** [comment]
Dear @DN6. Thanks for the help. I will work to get you with a debug log file in the coming days.
