### ISSUE TITLE
Can't change chart color in an experiment

### ISSUE THREAD

**Issue by phosseini** [comet-ml/issue-tracking#464]
## Describe the Bug
By default, there is a color chosen for charts in an experiment. I simply want to change the color of the charts but for some reason, the color does not change. For example, when I go to an experiment, I select `"Change colors,"` then I select the `"Single Color Per Experiment,"` then after choosing a new/different color I click `"Done"`. Even though the color in the "Select Colors" panel changes, color of non of the charts gets updated. First I thought maybe we cannot change the color of a running experiment. However, I tried this even for an experiment that is done and I still can't change the color. I even added a new chart to an experiment to see if the newly added chart will have the updated color, but the newly added charts also have the first color they had. I am trying to figure out why.

## Expected behavior
Simply changing the color of ALL charts in existing experiments (either running or done.)

## Where is the issue?
- [x] Comet UI

## Screens
As you see in the following, even though I've changed the color, charts' color is still the same (in the background)

![Screen Shot 2022-03-09 at 4 08 52 PM (2)](https://user-images.githubusercontent.com/25105263/157536601-0959b1f0-b3d2-4b34-85c3-bbbf85f55a9d.png)

**Comment by DN6** [comment]
Hello @phosseini. Thank you for flagging this. I was able to reproduce this issue and I've raised a ticket with our engineering team. I will update you here when this is resolved.
