### ISSUE TITLE
Cannot log hyperparameter if it looks like a number in scientific notation

### ISSUE THREAD

**Issue by mova** [comet-ml/issue-tracking#465]
## Where is the issue?
- [x] Comet Python SDK
- [x] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
1. `api_exp.log_parameters({'hash': '80e5005'})`
2. Experiments > 'hash' filled is blank for this experiment, other hashes work
3. If I get the experiment via `comet_ml.API(...).get(...)`, then the `exp.get_parameters_summary("hash")` is `[]`.

## Screenshots or GIFs
![Screenshot from 2022-03-21 18-42-57](https://user-images.githubusercontent.com/779688/159333621-b7549b85-2d68-49ff-936c-845ebc69663b.png)

## Link to Comet Project/Experiment

https://www.comet.ml/mscham/normal/view/aeJxyfMF2731Kme0gAn0i2oqb/experiments

## Additional context
I have reported the same bug before ( in the slack at the time ), but then full number strings `"123456"` were the problem.

**Comment by mova** [comment]
Oh, sorry, I accidentally archived it.
https://www.comet.ml/mscham/normal/932caccd927a4073b60a27aaa356b346 
or:
https://www.comet.ml/mscham/normal/10a59adb6b7a4fbdbdf4d0e9d9e1164f

**Comment by DN6** [comment]
Thank you @mova! I was able to reproduce the issue. Let me check with our team to see what might be happening. I will update you here when we have a resolution.

**Comment by DN6** [comment]
@mova Would it be possible to increase the character length of your hash strings so that they do not look like scientific notation?  This could be a quick way to unblock you with the issue

**Comment by mova** [comment]
Hey, 
if I'm understanding correctly that would  only make it less likely to happen, since `80098765347887667e5005786546` is still valid python. If possible, the datatype of parameters/metrics could be recorded to exclude such errors in the future.
For my personal project, i have changed the way the hash is calculated to avoid the issue for now.
