### ISSUE TITLE
Doc Improvement: log metadata

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#467]
## Is your feature request related to a problem? Please describe.
A lot of logging functions in comet also support logging metada information (e.g. [log_text](https://www.comet.ml/docs/python-sdk/Experiment/#experimentlog_text)).

## Describe the solution you'd like
It would be nice to address what can be done with this metadata, how it is displayed in the comet interface, what can be done with this information, and how can it be accessed. Adding some screenshots would be much appreciated.

## Additional context
For example, the metadata dictionary given to `log_text` is displayed as additional columns in the experiments' text part, but this information is not provided in the `log_text` documentation.

**Comment by DN6** [comment]
Duly noted @george-gca! Thank you for the suggestion. We will work towards adding more context to these methods in our docs

**Comment by dsblank** [comment]
This issue is now tracked internally as CM-8716
