### ISSUE TITLE
Adding second metric to line chart with aggregation crashes dashboard

### ISSUE THREAD

**Issue by kirillv-cim** [comet-ml/issue-tracking#469]
## Describe the Bug
In Comet UI, when using a line chart to plot a single metric with grouping enabled (mean aggregation, Std Dev range; see photo 1), adding a second metric in the y-axis immediately crashes the dashboard (see photo 2).

## Expected behavior
No crash

## Where is the issue?
- [ ] Comet Python SDK
- [X] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
Steps to reproduce the behavior (Comet UI):
1. Create a panel with a line chart for a single metric in the y-axis
2. Enable grouping and select "Mean" for "Aggregation" and "Std Dev" for "Range"
3. Click Done to finish editing the panel
4. Edit the same panel again, select a second metric to add to y-axis (photo 1). As soon as the metric is selected, observe a dashboard crash (photo 2)

## Stack Trace
N/A

## Comet Debug Log
N/A

## Screenshots or GIFs
Photo 1:
![p1](https://user-images.githubusercontent.com/77167055/161896338-c790d7c0-6b34-412f-aa33-029eba40f1b6.png)
Photo 2:
![comet](https://user-images.githubusercontent.com/77167055/161896457-e8634adc-1e68-4682-b486-b9e5bf56adf6.PNG)

## Link to Comet Project/Experiment
Can provide if helps later on

## Additional context
N/A

**Comment by kirillv-cim** [comment]
Tried first adding multiple metrics, then enabling grouping. Mean aggregation worked fine, but enabling Std Dev range caused the crash.

**Comment by DN6** [comment]
Hi @kirillv-cim I was able to reproduce this issue. I've raised a ticket with our engineering team to look into this. I will update you when we have a fix ready.

**Comment by kirillv-cim** [comment]
Hi @DN6 , many thanks for the update!
