### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by bw4sz** [comet-ml/issue-tracking#47]
Hello, first of a couple issues i'll post after working with comet for a few days. I'm definitely really happy with the tool.

It would be very useful to export the data back out of the project page. For example, if i wanted to know how my average accuracy was changing across experiments. Or compare the effect of a given hyperparameters on performance, I'd want to select multiple experiments and dump the data to file/json. Then I could go and plot those data in Python/R. It would be extra nice to make this a method in the comet_ml API, since it already has our key authentication. The "compare experiments" idea is getting there, but exporting the data would allow a user to balance a quick visual check of a run versus more in-depth graphing that would be too cumbersome to customize in the browser.  

Let me know if this kind of feedback is better in-channel.

**Comment by ceceshao1** [comment]
@bw4sz - our REST API is coming out soon and we can notify you and other folks on the slack channel when it's on beta (~next week). Would that fulfill your need for data export? The data would be  in `json` format. Can provide more details re: API🥇 

On a slightly different note, it seems like there are some things about the `compare experiment` capability that are missing for you right now - would love to get your feedback on what we can improve (options = submit another GH issue or we can chat on slack about it)

**Comment by bw4sz** [comment]
A rest API sounds great. I think a wrapper for the comet_ml pypi module would be useful, but all in time.

**Comment by ceceshao1** [comment]
@bw4sz / @neighthan - **I'm going to close this GH issue since we've released the REST API** (see the documentation [here](https://www.comet.ml/docs/rest-api/endpoints/)). 

Don't hesitate to provide feedback/report issues (as always)! 

P.S. One of our developers @bnbarak is in the process of creating a **Node.js wrapper for the API** as well. It'll take 1 or 2 more days! Stay tuned 🚀
