### ISSUE TITLE
`log_image` uploading images with the same name

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#471]
## Describe the Bug
I am uploading multiple images from my code during the eval phase, but sometimes it handles the same image in another iteration. Since it is the same image, and I set the parameter `overwrite` on [log_image](https://www.comet.ml/docs/python-sdk/Experiment/#experimentlog_image) to `False` and I am not associating any `step` to it, I figured that it wouldn't upload the same image again. But it is.

## Expected behavior
Avoid uploading the same image again since it has the same name and no step.

## Where is the issue?
- [X] Comet Python SDK
- [ ] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## Screenshots or GIFs
![image](https://user-images.githubusercontent.com/31376482/162820858-8680c35c-af1a-4161-be49-2e6856fac03f.png)

## Additional context
I realized that probably it is doing that because the `Context` metadata of the images are different. But how do I avoid this?

![image](https://user-images.githubusercontent.com/31376482/162821804-6481dbf5-3f85-4aec-a3c8-1bc957a27803.png)

![image](https://user-images.githubusercontent.com/31376482/162821954-ce6d2c18-b318-4b82-8987-03c683bb4156.png)

**Comment by DN6** [comment]
Hi @george-gca. Would you be able to tell me what you mean by handling the same image in another iteration? Is there a specific reason you have set `overwrite=False`

**Comment by george-gca** [comment]
@DN6 sure. Currently I am working with [visual question answering](https://visualqa.org/), so basically there is an image, and a text question associated with it. I'd like to log to comet the image, question, and resulting answer.

The problem is, sometimes I can have multiple questions associated with the same image, so I end up uploading the same image over and over. I thought that the `overwrite=False` parameter would avoid uploading the same image again, since it would figure that the image is already in the server because it has the same name and step associated with it (which is None).

**Comment by atharvas** [comment]
Also facing this issue while logging images! Happy to provide any logs/code/etc. if needed.
