### ISSUE TITLE
Duplicate section in report don't keep panel layout

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#476]
## Describe the Bug
When duplicating a section in report, it doesn't keep panel layout the same (keeps the panels, but not its width/height.

## Expected behavior
When duplicating a section, generate a perfect copy of it.

## Where is the issue?
- [ ] Comet Python SDK
- [X] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
1. Create a report
2. Create a section with a few panels, change their size/position
3. Duplicate it

## Screenshots or GIFs
![image](https://user-images.githubusercontent.com/31376482/172706605-90eb450e-62da-4e84-8ca1-291550fb425b.png)

![image](https://user-images.githubusercontent.com/31376482/172706764-401e16b7-1419-4c3d-aeeb-76c135128b87.png)

**Comment by DN6** [comment]
Hello @george-gca. Indeed this looks like a bug. I'll raise a ticket with the engineering team and update you here when it is resolved 👍🏽
