### ISSUE TITLE
Table of Contents (ToC) in Report

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#477]
## Is your feature request related to a problem? Please describe.
When a report is big enough, navigating between sections becomes a bit slowly.

## Describe the solution you'd like
It would be nice to see a table of contents somewhere on the report.

## Describe alternatives you've considered
One option would be a Table of Contents in the beginning of the report, maybe like the one in [Gitlab wikis](https://docs.gitlab.com/ee/user/markdown.html#table-of-contents). A nicer option would be in a sidebar, like the ones that appear in a well formated pdf, or even Google docs.

**Comment by DN6** [comment]
Noted @george-gca. I will bring this up with our Product team.
