### ISSUE TITLE
Can you drop dependency on `nvidia-ml-py3`?

### ISSUE THREAD

**Issue by xwjiang2010** [comet-ml/issue-tracking#481]
## Describe the Bug

Both `nvidia-ml-py3` and `nvidia-ml` are installing the same  `pynvml.py` module, causing issues with the newest `gpustat` release. Error msg:
```
ImportError: pynvml is missing or an outdated version is installed.
```

## Where is the issue?
- [ ] Comet Python SDK
- [ ] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## Stack Trace
If possible please include the full stack trace of your issue here

```
# Paste stack trace here
```

## Comet Debug Log
If possible, please follow the instructions [here](https://www.comet.ml/docs/python-sdk/advanced/#troubleshooting) to run Comet in debug mode and attach the resulting log file.  

## Screenshots or GIFs
If applicable, add screenshots/gifs to help explain your problem.

## Link to Comet Project/Experiment
If applicable, please provide a link to your Comet Project or Experiment.

**Comment by pcmoritz** [comment]
What is the stance of the comet maintainers on this issue? This is a blocker for adopting comet for anybody who wants to use a recent version of gpustat.

**Comment by pcmoritz** [comment]
I also linked the related gpustat issue

**Comment by mattip** [comment]
Any news here?

**Comment by mattip** [comment]
Hi. Is there an update to this issue?

**Comment by DN6** [comment]
Hi all. The dev team has identified the issue and found a viable workaround that will maintain current Comet functionality while fixing this issue. The fix will be released within the next two weeks.

**Comment by jacques-comet** [comment]
Hi @mattip @xwjiang2010 
The latest version of the Comet SDK (version 3.31.9) has dropped the `nvidia-ml-py3` dependency, let me know if you are still running into any issues on the latest version of the SDK

**Comment by jacques-comet** [comment]
From version 3.31.9 onwards `nvidia-ml-py3` is no longer a dependency of the SDK. Closing this issue as resolved

**Comment by mattip** [comment]
Thanks!
