### ISSUE TITLE
Legend shows experiment id instead of name when exporting

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#482]
## Describe the Bug
When I create a bar chart with builtin panel, set legend to display name, and export it (as png or svg), it is showing experiment id in legend instead of name.

## Expected behavior
Legend of the exported images should display experiment name.

## Where is the issue?
- [ ] Comet Python SDK
- [X] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
Create a bar chart, set `Legend keys` as Name, export the plot.

## Screenshots or GIFs

`Legend keys` as Name
![image](https://user-images.githubusercontent.com/31376482/182047213-1b1412a2-3663-4702-ad02-7447abc7a708.png)

Showing the real experiment Name that should be displayed in the exported version
![image](https://user-images.githubusercontent.com/31376482/182047286-d9968a3b-dfd2-41da-a604-b7dc09e3ab81.png)

Exported image
![image](https://user-images.githubusercontent.com/31376482/182047234-6bfcdf29-32a5-4574-b0f3-61b3fa136b0e.png)

**Comment by DN6** [comment]
Hi @george-gca. I was able to reproduce this. I've raised the issue with our engineering team and it has been prioritized.

**Comment by dsblank** [comment]
I believe that this has been fixed. Please re-open if further issues. Thanks for reporting!
