### ISSUE TITLE
[Feature request] Customize Plotly Mode Bar Icons

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#483]
## Is your feature request related to a problem? Please describe.
I was trying to work around #482 then I found out that I can customize the way I can export the plot in Plotly. More specifically, I can [customize the format that the download button will output](https://plotly.com/python/configuration-options/#customizing-modebar-download-plot-button). So I tried to do that.

## Describe the solution you'd like
I would like to be able to do exactly that. I found out that there is a [kwargs parameter](https://www.comet.com/docs/v2/api-and-sdk/python-sdk/reference/ui/#uidisplay) handling when calling `ui.display` in the python panel sdk, but I could not make it work with the Plotly figure. I tried `ui.display(go.Figure(figure), config=cfg)`, and also `ui.display(go.Figure(figure), kwargs={"config": cfg})`, but to no avail. I even tried to add the configure keys to the figure dictionary, when creating the figure dictionary as [here](https://www.comet.com/docs/v2/guides/comet-dashboard/code-panels/python-panels-examples/#using-plotly).

## Describe alternatives you've considered
#482

**Comment by dsblank** [comment]
We are working on a more flexible interface for Python Panels. Thanks for the report!
