### ISSUE TITLE
Metric selection dropdown filter randomly resets

### ISSUE THREAD

**Issue by lemairecarl** [comet-ml/issue-tracking#484]
## Describe the Bug
In the "Add scatter chart to project" window, when typing to filter through metrics and parameters, I type characters and the dropdown updates. However, after I stop typing, after a few seconds the dropdown resets to showing all items, even as I have something in the filter text box. Thus, to be able to use the filtering, I have to react quickly and click right when I see the item I want. If I wait just 3-4 seconds, there is a risk that the dropdown resets to showing all items.

## Expected behavior
The dropdown should only update in reaction to key presses.

## Where is the issue?
- [ ] Comet Python SDK
- [x] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
1. Go to Panels
2. Click on Add
3. Add a scatter chart
4. Start filtering the Y-axis field by typing characters
5. In some cases, just waiting 2 seconds will make the bug happen. Also, scrolling the dropdown to the top can trigger the bug.

## Screenshots or GIFs

As you can see, the dropdown contains items unrelated to "accu", in fact it shows all items.

![Screenshot from 2022-08-27 13-10-01](https://user-images.githubusercontent.com/13444373/187040746-27330ce3-f058-43cc-8a92-7a0ebb2800f6.png)

## Link to Comet Project/Experiment
https://www.comet.com/lemairecarl/harmon-moyer/view/dfWVmkI8grlv7lAEONOW6N0Ql/panels

**Comment by dsblank** [comment]
This is probably caused by the page being updated to refresh for any experiment changes. I believe that this has been fixed. Please re-open if you have any questions or comments. Thanks for reporting!
