### ISSUE TITLE
ui.display not working with plotly express object

### ISSUE THREAD

**Issue by ankit51** [comet-ml/issue-tracking#485]
## Describe the Bug
Logging a plotly express object using ui.display throws an error

## Expected behavior
It should log the plot to the Panels in my experiment

## Where is the issue?
- [ x] Comet Python SDK
- [ ] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
![Screenshot 2022-08-29 at 5 42 11 AM](https://user-images.githubusercontent.com/7209695/187100797-bae06d9b-8c28-44c5-84b5-082a326a16dc.png)

```
fig = px.histogram(train, x="SalePrice", marginal="rug",
                   hover_data=train.columns)
ui.display(fig)
```

## Stack Trace
If possible please include the full stack trace of your issue here

```
# Paste stack trace here
```

## Comet Debug Log
If possible, please follow the instructions [here](https://www.comet.ml/docs/python-sdk/advanced/#troubleshooting) to run Comet in debug mode and attach the resulting log file.  

## Screenshots or GIFs
If applicable, add screenshots/gifs to help explain your problem.

## Link to Comet Project/Experiment
If applicable, please provide a link to your Comet Project or Experiment. 
https://www.comet.com/ankit51/px/80d13e6671ef4c1f84c70358af0a7762?experiment-tab=chart&showOutliers=true&smoothing=0&transformY=smoothing&xAxis=step

**Comment by DN6** [comment]
Hi @ankit51 Are you running `ui.display` in Python Panels Code Editor in the UI?  Or a notebook?

**Comment by ankit51** [comment]
Hi @DN6 

I am running it in a notebook.

**Comment by DN6** [comment]
Hi @ankit51. `ui.display` is meant to to be used with the Python Panels code editor from the UI

**Comment by ankit51** [comment]
OK, understood
