### ISSUE TITLE
Add tags column to the panel view

### ISSUE THREAD

**Issue by kirillv-cim** [comet-ml/issue-tracking#487]
## Is your feature request related to a problem? Please describe.
When comparing multiple selected experiments in Panel view, it's often hard to remember what each experiment is (e.g. during hyper-parameter tuning or architecture search), especially if experiment name is not explicitly set and is randomly generated (either way, not the most appropriate way to discern experiments for multiple attributes). Tags help to sort experiment by desired attributes, but are not visible in the Panel tab, only in Experiment tab.

## Describe the solution you'd like
Adding a Tags column after the Name column in the Panel tab; see screenshot in the Additional Context section.

## Describe alternatives you've considered
Currently having to switch between Panel and Experiment tabs to peek at the tags.

## Additional context
See the photo bellow as to where the tags can be included (where the red arrow is pointing)
![image](https://user-images.githubusercontent.com/77167055/196293469-1a4f3758-bc13-4092-919a-a9521c4b0511.png)

**Comment by dsblank** [comment]
You can now click on "Experiments" in that view to alternate between seeing the Panels, and seeing the experiment grid. Otherwise, there just wasn't enough room. Let us know if this solution works for you.
