### ISSUE TITLE
Laggy Scrolling

### ISSUE THREAD

**Issue by neighthan** [comet-ml/issue-tracking#49]
I don't know if this is just for me, but whenever I have the Code, Graph Definition, or Installed Packages tabs open, scrolling lags quite a bit - not only scrolling the code itself, but also scrolling the entire web page if the code box is visible. This stops being a problem as soon as the code box is out of view. No bug here, obviously, but it would be a nice enhancement if this part of the interface were more fluid. Right now I just click on View Raw when looking at code/graph defs; since this workaround already exists, this isn't high priority for me, but I thought I'd raise the issue (and at least see if others have this as well).

**Comment by Nimrod007** [comment]
Hi @neighthan , we pushed some changes regarding the laggy scrolling. can you check on your end and see if it solves the issue ?

**Comment by neighthan** [comment]
@Nimrod007, everything scrolls *much* better now. Thank you!
