### ISSUE TITLE
Experiment Summary Report has everything but experiment name

### ISSUE THREAD

**Issue by davidgilbertson** [comet-ml/issue-tracking#491]
## Describe the solution you'd like
In the console, Comet prints out some details of my experiment:
![image](https://user-images.githubusercontent.com/4443482/209740456-98442bda-73d2-49ca-918a-6d3eee9f9fea.png)

It seems odd that this doesn't contain the actual name of the experiment. My workaround is to just manually print out the `experiment.name`.

(I do this because the web UI is quite slow to update, I want to know the name so I can be confident I'm seeing my new data - would be great if this was faster! It shouldn't really take more than a few hundred milliseconds)

**Comment by dsblank** [comment]
Good point! This is being tracked internally as issue EXT-1339.

**Comment by dsblank** [comment]
Experiment name was added to the Summary in comet_ml version 3.40.0 which was released today. Thank you for the request!

**Comment by dsblank** [comment]
Please let us know if you have any other requests or questions!
