### ISSUE TITLE
metadata argument of Artifact.add is ignored

### ISSUE THREAD

**Issue by lemairecarl** [comet-ml/issue-tracking#500]
## Describe the Bug
`metadata` argument of `Artifact.add` is ignored

Also, [the docs says about this argument](https://www.comet.com/docs/v2/api-and-sdk/python-sdk/reference/Artifact/#artifactadd) : "additional data to attach to the the audio asset". Why specifically audio?

## Expected behavior
I expected to find the dict values somewhere in the UI, e.g. in the metadata tab of the artifact, but there is nothing there.

## Where is the issue?
- [X] Comet Python SDK
- [ ] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

**Comment by dsblank** [comment]
Thanks for pointing out this issue! This is being internally tracked as issue EXT-1335.

**Comment by dsblank** [comment]
Update:
1. Typo in docs fixed; will be released soon
2. The metadata is for the file, and the Product team is trying to figure out what to do. Would it be possible for you to add the metadata to the artifact, rather than the file?
