### ISSUE TITLE
Metrics are not persisted to file with OfflineExperiment

### ISSUE THREAD

**Issue by mikolajkania** [comet-ml/issue-tracking#501]
## Describe the Bug
Offline experiment is not saving metrics.

## Expected behavior
I would like to work with Comet localy. I want to save metrics in its zip dump. It is not working.

## Where is the issue?
- [x] Comet Python SDK

## To Reproduce
1. Run:
```
from comet_ml import OfflineExperiment
exp = OfflineExperiment()
exp.log_metrics({'accuracy': 0.5, 'loss': 0.001})
exp.end()
```

2. Read summary in console:

> COMET INFO:   Metrics:
> COMET INFO:     accuracy : 0.5
> COMET INFO:     loss     : 0.001

3. Go into created zip, i.e. 8991baeaaa3642579e7f90ca84e0895b.zip. In any file there is metion of accurracy or loss.

4. Load experiment with ExistingOfflineExperiment. Also no trace of a metric.

## Stack Trace
If possible please include the full stack trace of your issue here

```
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml OfflineExperiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     url                   : [OfflineExperiment will get URL after upload]
COMET INFO:   Metrics:
COMET INFO:     accuracy : 0.5
COMET INFO:     loss     : 0.001
COMET INFO:   Others:
COMET INFO:     offline_experiment : True
COMET INFO:   Uploads:
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (3.45 MB)
COMET INFO:     installed packages       : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1 (2.38 KB)
COMET INFO: 
COMET WARNING: Experiment Name is generated at upload time for Offline Experiments unless set explicitly with Experiment.set_name
COMET INFO: Still saving offline stats to messages file before program termination (may take up to 120 seconds)
COMET INFO: Starting saving the offline archive
COMET INFO: To upload this offline experiment, run:
    comet upload (...)/.cometml-runs/8991baeaaa3642579e7f90ca84e0895b.zip
```

Here is a resulting file:
[8991baeaaa3642579e7f90ca84e0895b.zip](https://github.com/comet-ml/issue-tracking/files/10778398/8991baeaaa3642579e7f90ca84e0895b.zip)

Code is working when switched to online mode again:
![obraz](https://user-images.githubusercontent.com/14984193/219985635-f0db76d1-accf-431d-9477-ade8318573eb.png)

Please fix it, as it is pretty annoying.

**Comment by jacques-comet** [comment]
Hi @mikolajkania ,

I've tried to reproduce the issue and haven't been able to. Looking at the zip file you provided, I can see the `accuracy` and `loss` metrics in the `messages.json` file:
```
{"payload":{"local_timestamp":1676852440067,"metric":{"epoch":null,"metricName":"accuracy","metricValue":0.5,"step":null}},"type":"metric_msg"}
```
I've also run the code you provided locally and when I upload the offline experiment to Comet, the accuracy and loss metrics are displayed in the UI.

I think the issue might be more in the workflow you are trying to implement. The ExistingOfflineExperiment object is just used to send data to an experiment that already exists, it is not mean to be used to load in local offlineExperiment and query its data.
Instead you can create local offline experiments, upload them to Comet using `comet upload /.../.cometml-runs/<...>.zip` and then query the data using the [Comet API class](https://www.comet.com/docs/v2/api-and-sdk/python-sdk/reference/API/)

**Comment by mikolajkania** [comment]
Hi @jacques-comet, thank you for an insight!

The thing I want to implement is to avoid clutter in Comet. I will be running a lot of failed/ not final trainings and I would like to decide which of them should go to the main dashboard. So I can imagine, let's say, 25 offline runs against 1 online run. And I would like to iterate over the most recent offline runs to learn from them.

This is why I tried to use ExistingOfflineExperiment but here is my full log:

`/home/mikolajkania/miniconda3/envs/newstitenv/bin/python /mnt/c/Users/mikol/Documents/Projects/newsletter/newsletter-titles/src/newsletter_titles/main.py 
COMET INFO: Using '/mnt/c/Users/mikol/Documents/Projects/newsletter/newsletter-titles/src/newsletter_titles/.cometml-runs' path as offline directory. Pass 'offline_directory' parameter into constructor or set the 'COMET_OFFLINE_DIRECTORY' environment variable to manually choose where to store offline experiment archives.
COMET INFO: COMET_API_KEY was set, but is ignored in OfflineExperiment(); remember to set when you upload
COMET WARNING: Unknown error exporting current conda environment
COMET WARNING: Unknown error retrieving Conda package as an explicit file
COMET WARNING: Unknown error retrieving Conda information
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml OfflineExperiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     url                   : [OfflineExperiment will get URL after upload]
COMET INFO:   Metrics:
COMET INFO:     accuracy : 0.5
COMET INFO:     loss     : 0.001
COMET INFO:   Others:
COMET INFO:     offline_experiment : True
COMET INFO:   Uploads:
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (3.45 MB)
COMET INFO:     installed packages       : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1 (2.36 KB)
COMET INFO: 
COMET WARNING: Experiment Name is generated at upload time for Offline Experiments unless set explicitly with Experiment.set_name
COMET INFO: Still saving offline stats to messages file before program termination (may take up to 120 seconds)
COMET INFO: Starting saving the offline archive
COMET INFO: To upload this offline experiment, run:
    comet upload /mnt/c/Users/mikol/Documents/Projects/newsletter/newsletter-titles/src/newsletter_titles/.cometml-runs/bdc4f93753ed43aa864753d54cf15269.zip
Printing experiments
COMET WARNING: Config key 'comet.auto_log.weights' is deprecated, please use 'comet.auto_log.histogram_weights' instead
{'sys.gpu.0.total_memory': 6442450944}

COMET WARNING: Unknown error exporting current conda environment
COMET WARNING: Unknown error retrieving Conda package as an explicit file
COMET WARNING: Unknown error retrieving Conda information
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml ExistingOfflineExperiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     url                   : [OfflineExperiment will get URL after upload]
COMET INFO:   Others:
COMET INFO:     offline_experiment : True
COMET INFO:   Uploads:
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (3.45 MB)
COMET INFO:     installed packages       : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1 (2.36 KB)
COMET INFO: 
COMET WARNING: Experiment Name is generated at upload time for Offline Experiments unless set explicitly with Experiment.set_name
COMET INFO: Starting saving the offline archive
COMET INFO: To upload this offline experiment, run:
    comet upload /mnt/c/Users/mikol/Documents/Projects/newsletter/newsletter-titles/src/newsletter_titles/.cometml-runs/bdc4f93753ed43aa864753d54cf15269-rVAIme.zip

Process finished with exit code 0
`

You can see that in first offline run metrics are seen, and in the second one - not. And now I see from your response that it is not the best usage of this class. I thought it should just read existing experiment with all the changes applied to it.

What would be the best case then for me? Track local runs without Comet? It would be a bit of disappoitment as I saw offline development mode as one of its features.

**Comment by jacques-comet** [comment]
@mikolajkania The `ExistingOfflineExperiment` class isn't actually reading from a particular file, even though you are passing in the offline directory the experiment object isn't instantiated with the data from the existing experiment. As a result, when you print `ex.metrics` you only get the metrics that were logged to the experiment object that was created just before. Given no new metrics were logged, there are no metrics to print.

I've done some digging and there is a workaround though. There are two options I think:
1. Set `disabled=True` during experiment creation when debugging a script to stop any data being logged to Comet
2. Log all the experiments to Comet and then archive them through the UI. Using filters based on a `hasCrashed` or another field will allow to quickly archive all the experiments that you don't wish to keep.
3. Use a workaround that allows you to export all the data contained in an OfflineExperiment `.zip` file to csv and read the data you need from there.

I think the third option is closest to what you are looking for, here is a working code snippet:
```
from comet_ml.scripts.comet_offline import ArchivedExperiment, get_parser_arguments
import argparse

parser = argparse.ArgumentParser(
    description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
)
get_parser_arguments(parser)
parsed_args = parser.parse_args([
    "--csv",
    "--level", "detail",
    "--section", "metric",
    "--output", "test.csv",
    "./.cometml-runs/0b5d7d7c4cbf4606bcb93b48cdae4b03-Eosojf.zip"])


ArchivedExperiment(
    './.cometml-runs/0b5d7d7c4cbf4606bcb93b48cdae4b03-Eosojf.zip',
    parsed_args)
```
The code shared here is taken from the Comet CLI and the command called [comet offline](https://www.comet.com/docs/v2/api-and-sdk/python-sdk/command-line-utilities/#comet-offline). This command allows you to process offline experiments and write the metrics to a csv file.

Do you think this could work ?

**Comment by mikolajkania** [comment]
hi, @jacques-comet, thank you for a hint.

I tried it and it is interesting option. Where I would find those metrics, though? This is what I see in the results of run:

![obraz](https://user-images.githubusercontent.com/14984193/221377262-e1cb22b8-cbb0-4210-9aa4-1ce2a61f1d74.png)

It looks like accuracy and loss are not present and they are the things I am looking for.

I think there is basic gap in tracking, those metrics:

![obraz](https://user-images.githubusercontent.com/14984193/221377668-123ef01b-4c83-4e5d-8424-1a18a592634e.png)

are present only in a payload in messages.json of the particular run. They are not saved as metrics, which is a pitty. Do you think is there a possibility that I could write my own subclass of OfflineExperiment to get them? If not, probably this ticket can be closed.
