### ISSUE TITLE
Offline experiments upload failed for ValueError? Anyone can help me?

### ISSUE THREAD

**Issue by hongge831** [comet-ml/issue-tracking#503]
COMET ERROR: File upload failed: ValueError("Uploading file failed with max retries: 4 on url 'https://www.comet.com/clientlib/asset/upload'"), file: /var/folders/p3/gmy1j6gn02ncvqd5dpn_wpw80000gn/T/tmpkini6y0p/tmpald55tsq

**Comment by dsblank** [comment]
Probably was just a temporary connection issue. If you have additional information, please re-open. Thanks for reporting!
