### ISSUE TITLE
Completely disable creation of temp file with creating Artifact

### ISSUE THREAD

**Issue by lemairecarl** [comet-ml/issue-tracking#504]
## Is your feature request related to a problem? Please describe.
When create an artifact, and add a file to it, Comet copies the file to `/tmp` in the process. In my case, I don't see any advantage of doing so, as the file is quite large, and the original file will always remain available. Also, the files created in `/tmp` are not always cleaned (maybe because of a crash), so there is an accumulation and risk of running out of space.

## Describe the solution you'd like
The `copy_to_tmp` argument of `Artifact.add` should allow to disable copying to a temp dir, **in all cases**, i.e., even if I am supplying a filename. According to the docs, the arg only applies to when one supplies a file-like object.

## Describe alternatives you've considered

* I could create a file object and give it to `add()`, however it still doesn't work, and now Comet creates not one, but TWO copies of the data. See #505 .
* I can set the `TMPDIR` env variable to point to a location with more space, but that only delays the problem, and using a directory that is not automatically cleaned by the system could worsen the situation.

## Additional context
I didn't understand right away the nuance in the docs about filename vs. file-like object, and I thought this would apply to filenames. It very much seemed like a bug.

I've been surprised to find that, whether `copy_to_tmp` was true or false, there seems to be a creation of temp file involved.

In `experiment.py:_log_preprocessed_asset`, there is a branching:

```
if preprocessed_asset.copy_to_tmp is True:
```

but both branches call functions that seem to create a temp file (`handle_in_memory_file_upload` and `write_file_like_to_tmp_file` respectively).

Also, in `comet.py:_process_upload_message`, there is a creation of a tmpfile in all cases, there doesn't seem to be a way to prevent this.

**Comment by dsblank** [comment]
I believe there were some issues when copy_to_tmp was False, and so that has been removed for now.
