### ISSUE TITLE
Artifact.add copy_to_tmp argument is ignored

### ISSUE THREAD

**Issue by lemairecarl** [comet-ml/issue-tracking#505]
## Describe the Bug
[According to the docs](https://www.comet.com/docs/v2/api-and-sdk/python-sdk/reference/Artifact/#artifactadd), `copy_to_tmp` disables copying the data to the temp folder. Even when setting it to False, Comet copies the data to the temp dir.

## Expected behavior
When setting `copy_to_tmp=False`, the artifact data should NOT be copied to the temp dir.

## Where is the issue?
- [X] Comet Python SDK
- [ ] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce

Take note of the size of the file (in my case, around 1GB).

Make sure there are no files in `/tmp` of this size.

Use this code:

```
file_obj = open(file_path, 'rb')
artifact.add(file_obj, logical_path=file_name, copy_to_tmp=False)
comet_exp.log_artifact(artifact)
```

Observe that there is now a file of that size in `/tmp`. (Actually, there are two copies!)

**Comment by dsblank** [comment]
This has been addressed in that copy_to_tmp has been deprecated. If this causes any issues, please reopen. Thanks for reporting!
