### ISSUE TITLE
[Bug] Comet ML HTML rendering does not use the full space available. HTML graphs are cut at 10% of the space

### ISSUE THREAD

**Issue by MatthieuToulemont** [comet-ml/issue-tracking#507]
## Describe the Bug
The HTML Page does not use the full window to render. 
This makes reading the HTML graphs we upload harder. 

## Where is the issue?
- [x] Comet UI
![Screenshot 2023-03-09 at 10 49 02](https://user-images.githubusercontent.com/75613333/223984386-81df8625-b6db-4843-a2f3-3a0c323277b1.png)

**Comment by MatthieuTPHR** [comment]
This can be fixed by setting the style of `class="ExperimentDetailsWrapper-module__experimentDetailWrapper--Oq5eV full-height"` to height: 100%

**Comment by MatthieuTPHR** [comment]
It seems to be happening on Chrome

**Comment by ferc** [comment]
@MatthieuTPHR we deployed a new version yesterday to it should be fixed :)
