### ISSUE TITLE
Add date and time to optimizer name

### ISSUE THREAD

**Issue by plutonium-239** [comet-ml/issue-tracking#511]
Since optimizers are the way to go and we run a lot of them, manually finding the id of the last run optimizer in the experiments table seems.... unnecessary. (I use the grouping feature a lot but I need to open the terminal and scroll to see what was the optimizer id)

A very simple way to improve this and QOL is to use the optimizer.name field, just append the datetime string to it.

An alternative would be to add a optimizer.datetime field, but that requires a change in the api probably?

**Comment by dsblank** [comment]
Tracking as internal issue EXT-1331.

**Comment by dsblank** [comment]
Workaround: you can now do this from `cometx`:

```
cometx log WORKSPACE/PROJECT --debug --query 'Other("optimizer_id") == "OLD-OPTIMIZER-ID"' --type other --set "optimizer_id:NEW-OPTIMIZER-ID"
```

See: https://github.com/comet-ml/comet-sdk-extensions

**Comment by dsblank** [comment]
You can now set the name of the optimizer in the Optimizer config:

```
config = {
   "algorithm": "random",
   "name": "random-sweep-mar-24-2024",
   ...
}
optimizer = comet_ml.Optimizer(config)
...
```
Does that solve your issue?

**Comment by plutonium-239** [comment]
Yes, I think a fully customisable name solves this and is even better!
Thank you, I'll close this issue now.
