### ISSUE TITLE
How to view all panels

### ISSUE THREAD

**Issue by lukasugar** [comet-ml/issue-tracking#517]
## Before Asking:   
- [x ] I have searched the Issue Tracker.   
- [ x] I have searched the Documentation.    

## What is your question related to?
- [x ] Comet UI

## What is your question?
I have multiple experiments. When I click on each of them, I can see many different panels. But in the main panel screen, I'm seeing just 4 of them. How to see all of them together?

When clicking on a single image:
<img width="1718" alt="image" src="https://github.com/comet-ml/issue-tracking/assets/22435018/298218c7-7b50-45b1-a4fe-754dcbe57a53">

When viewing all experiments, why are only 4 panels shown?
<img width="1714" alt="image" src="https://github.com/comet-ml/issue-tracking/assets/22435018/fb7289b6-1dec-42ad-a799-fde182c7b3f8">

## Code
```
Please paste a code snippet if your question requires it!   
```

## What have you tried?
I've figured out that I can go to + Add -> New Panel, but I'd like to show that all and not add one by one

**Comment by dsblank** [comment]
I suspect that that may be by design, but I am asking the engineering team.

**Comment by lukasugar** [comment]
@dsblank thanks for picking this up. If it's by design, I'd advocate for enabling the view of all/many panels, I feel it'd be very useful :)

**Comment by dsblank** [comment]
@lukasugar agreed :) I've confirmed that the current value is set to 4 by design. Are you using the comet.com cloud, or are you using an onprem comet installation?

**Comment by lukasugar** [comment]
I’m using comet.com cloud

**Comment by dsblank** [comment]
Ok, this is now being tracked internally as EXT-1330. Thanks for bring this to our attention!

**Comment by dsblank** [comment]
This is now in development.
