### ISSUE TITLE
How to fetch an image logged to an experiment on Comet ML?

### ISSUE THREAD

**Issue by kirilllzaitsev** [comet-ml/issue-tracking#518]
## Before Asking:   
- [+] I have searched the Issue Tracker.   
- [+] I have searched the Documentation.    

## What is your question related to?
- [+ ] Comet Python SDK
- [ ] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lightning etc.)  

## What is your question?

I want to fetch an image once logged to an experiment on Comet ML for displaying it with matplotlib. How can I do that?

## Code
```
Please paste a code snippet if your question requires it!   
```

**Comment by dsblank** [comment]
You can fetch all of the assets in the Comet Python SDK with a two-step process:

First, get the asset list:

https://www.comet.com/docs/v2/api-and-sdk/python-sdk/reference/APIExperiment/#apiexperimentget_asset_list

```python
>>> from comet_ml.api import API
>>> api = API()
>>> x = api.get("myworkspace/project1/experiment_key")
>>> assets = x.get_asset_list()
```

Then you can get the asset by its asset ID:

https://www.comet.com/docs/v2/api-and-sdk/python-sdk/reference/APIExperiment/#apiexperimentget_asset

```python
>>> api_experiment.get_asset("298378237283728", return_type="binary")
```

Does that help? You can do this in a Python program, or in a Comet Python Panel.

**Comment by kirilllzaitsev** [comment]
Yes, thank you, it works.
