### ISSUE TITLE
Name of an experiment

### ISSUE THREAD

**Issue by kazitasnif** [comet-ml/issue-tracking#52]
Currently, experiments do not have any 'name' property. So, it's harder to keep track of which experiment is which. A name property would allow naming with the associated hyperparameters.

**Comment by ceceshao1** [comment]
@kazitasnif and @noahyonack - we've pushed the ability for you to set a name for your experiment. Here are some direct links to the docs:

- For a new experiment: https://www.comet.ml/docs/python-sdk/Experiment/#experimentset_name
- For an existing experiment: https://www.comet.ml/docs/python-sdk/ExistingExperiment/#existingexperimentset_name

Closing this feature request as it has been resolved.

**Comment by noahyonack** [comment]
@ceceshao1 Thanks!

Is it possible to have the name show up as a column in the experiment table (next to the experiment key?) so that it's easy to know which experiment is which?

**Comment by gidim** [comment]
Sure!
Just click the "Customize Columns" on the top right and select "Name".
