### ISSUE TITLE
In custom panel: How to get the currently highlighted experiment?

### ISSUE THREAD

**Issue by florianblume** [comet-ml/issue-tracking#520]
## Before Asking:   
- [x] I have searched the Issue Tracker.   
- [x] I have searched the Documentation.    

## What is your question related to?
- [ ] Comet Python SDK
- [x] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lightning etc.)  

## What is your question?

In a custom panel, I would like to also mark the currently highlighted experiment in the experiments overview. E.g., I have a panel showing some parameter tried out in a hyperparameter search. Now, I would like to also highlight the respective paramter when I'm hovering over one of the curves.

Is it possible to get the currently highlighted experiment from the JavaScript SDK?

**Comment by dsblank** [comment]
Can you provide a screen capture indicating where you would like to see the highlighted parameter when hovering?
