### ISSUE TITLE
Need a solution for updating or removing string metrics in existing Experiments.

### ISSUE THREAD

**Issue by DiegoFernandezC** [comet-ml/issue-tracking#521]
## Before Asking:   
- [x] I have searched the Issue Tracker.   
- [x] I have searched the Documentation.    

## What is your question related to?
- [x] Comet Python SDK
- [x] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lightning etc.)  

## What is your question?

Hello, I am encountering an issue with corrupted metrics in the Model Registry. Suppose that I have a metric called `metric1`. This metric was logged as a dictionary value and, for this reason, has been parsed into a string. This is causing problems with a library I am using to evaluate new models against existing ones, as it expects the metrics to be in float format.

The issue arises when the library attempts to parse the string-like metric value into a float, which fails due to the incorrect data type. I am seeking a solution to either remove this metric or update it with a float value in the existing experiments without re-registering all my models and creating new experiments again.

## What have you tried?

I attempted to load the experiment and update the current value using `log_metric()`. However, I can only see the updated value in the UI when it's a string (e.g., `"abc"`). If I input a float number or a string representation of a float number (e.g., `"0.3"`), it doesn't work, and the new value is not visible in the UI.

When I retrieve the historical data of this metric using `exp.get_metrics("metric1")`, I can see my float values with different timestamps. However, these values are not reflected in the UI.

**Comment by dsblank** [comment]
> If I input a float number or a string representation of a float number (e.g., "0.3"), it doesn't work, and the new value is not visible in the UI.

Can you provide a snippet of code to give an example?

If you have a link to an experiment, can you share here if it is public, or send it to me doug@comet.com?
