### ISSUE TITLE
Failed (Crashed) Experiment status doesn't reset when restarted from last checkpoint

### ISSUE THREAD

**Issue by Ritesh313** [comet-ml/issue-tracking#528]
## Describe the Bug
When the experiment crashes because of an error, comet shows a red cross in front of it. If you restart the experiment from last saved checkpoint, the logging starts as normal, but the sign doesn't go away.

## Expected behavior
If a failed (crashed) experiment is restarted using `ExistingExperiment` function, it's state should be reset to running again. Basically the red cross sign should be replaced by the experiment running sign.

## Where is the issue?
- [ ] Comet Python SDK
- [x] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
1. Run a comet experiment with an error in code after it saves a checkpoint. You'll see the crashed sign next to the experiment on comet.
2. Fix the error and restart the experiment using `ExistingExperiment`. The comet experiment will start logging, but still show crashed sign.

## Screenshots or GIFs
The crashed experiment sign
<img width="567" alt="image" src="https://github.com/comet-ml/issue-tracking/assets/36135489/27c5d090-3d55-4b5a-9867-00684ac81914">

Running experiment sign
<img width="438" alt="image" src="https://github.com/comet-ml/issue-tracking/assets/36135489/a2942b92-3d94-4734-ab7a-61e32e331d55">

**Comment by dsblank** [comment]
@Ritesh313 thank you for reporting. Can you run the following code snippet and report results for an experiment that was continued with `ExistingExperiment`?

```python
from comet_ml import API
api = API()
experiment = api.get("WORKSPACE/PROJECT/EXPERIMENT-NAME")
print(experiment.get_metadata())
```
I'm going to guess that "error" is still True.

**Comment by dsblank** [comment]
Internal ticker number is `EXT-1444`

**Comment by Ritesh313** [comment]
`{'experimentKey': '84e2d2f0c62e4d038aef0679dc79867f', 'experimentName': 'creative_barbel_8378', 'optimizationId': None, 'userName': 'ritesh313', 'projectId': 'bf0890c2bcd74382b335f5092e8535bf', 'projectName': 'scale-ai', 'workspaceName': 'ritesh313', 'filePath': '/blue/azare/riteshchowdhry/Personal/scale_ai/star_find/train_experiment.py', 'fileName': 'train_experiment.py', 'throttle': False, 'throttleMessage': '', 'throttlingReasons': [], 'durationMillis': 33809340, 'startTimeMillis': 1700685741418, 'endTimeMillis': 1700719550758, 'running': False, 'error': 'Unexpected error detected in the user script: TypeError("\'int\' object is not iterable")', 'archived': False}`

**Comment by Ritesh313** [comment]
My apologies, I closed it by mistake. Let me know if that's the output you needed.

**Comment by dsblank** [comment]
Thanks! A fix is being developed.

**Comment by dsblank** [comment]
This issue was labeled "CM-8690" and has now available at comet.com. Let us know if you have an questions, comments, or issues. 

Thanks for reporting!
