### ISSUE TITLE
Fix typos on the FAQ page 

### ISSUE THREAD

**Issue by ceceshao1** [comet-ml/issue-tracking#53]
First reported via Intercom for the FAQ page (https://www.comet.ml/faq)

1. "Does ~it~ work with library (including it)
2. I found a bug ~I~'d like to report". (capitalizing the i)

See the screenshot:
![image](https://user-images.githubusercontent.com/24228106/40810580-35a05264-64fc-11e8-99ae-2de6fab511a6.png)

**Comment by ceceshao1** [comment]
Link to PR: https://github.com/comet-ml/comet-react/pull/1260

**Comment by ceceshao1** [comment]
Closing as resolved!

**Comment by blatr** [comment]
Small typo at https://www.comet.ml/docs/python-sdk/errors-warnings/
![image](https://user-images.githubusercontent.com/16680949/42819110-3b52f76c-89db-11e8-98f0-854587b1b4a0.png)

**Comment by ceceshao1** [comment]
Thanks for catching this @blatr - just pushed a fix so it'll be up soon!
