### ISSUE TITLE
Allegedly Invalid API Key

### ISSUE THREAD

**Issue by MAGomes95** [comet-ml/issue-tracking#532]
## Describe the Bug
I am building an application that ultimately predicts the likelihood of a given person to develop lung cancer given a set of features. In order to deploy my application as a API, I am using Cerebrium.

In the moment of deploying the endpoint, more precisely, in the building phase, the process is interrupted with the following log:

I have changed the API Key in comet-ml several times as well update its value in the secrets section of Cerebrium, so I know this is not the issue.

## Expected behavior
I expected this error wouldn't be thrown, since the API key is correct

## Where is the issue?
- Comet Python SDK

## Stack Trace

Jan 04 08:34:46 PM cerebrium.secrets:get_secret:31 - Fetching secret for key: COMET_ML_WORKSPACE
Jan 04 08:34:46 PM Fetching secret for key: COMET_ML_WORKSPACE
Jan 04 08:34:46 PM cerebrium.secrets:get_secret:31 - Fetching secret for key: COMET_ML_API_KEY
Jan 04 08:34:46 PM Fetching secret for key: COMET_ML_API_KEY
Jan 04 08:34:46 PM cerebrium.secrets:get_secret:31 - Fetching secret for key: COMET_ML_MODEL_NAME
Jan 04 08:34:46 PM Fetching secret for key: COMET_ML_MODEL_NAME
Jan 04 08:34:46 PM Traceback (most recent call last):
Jan 04 08:34:46 PM File "/persistent-storage/.venv/miniconda/envs/lungcancer-svm/lib/python3.10/site-packages/comet_ml/connection.py", line 1985, in get
Jan 04 08:34:46 PM raise InvalidRestAPIKey(self.api_key)  # probably
Jan 04 08:34:46 PM comet_ml.exceptions.InvalidRestAPIKey: "xxxxxxxxxxxxxxxxxxxxxxx"

**Comment by dsblank** [comment]
Not sure if those names are supposed to match Comet's environmental variables, but Comet's are:

```
COMET_API_KEY
COMET_WORKSPACE
```

**Comment by dsblank** [comment]
A full list of Comet environment variables is listed here:

https://www.comet.com/docs/v2/api-and-sdk/python-sdk/advanced/configuration/#configuration-parameters

**Comment by MAGomes95** [comment]
Hello! 

Thank you for your response in such a short notice but I tried to change the name of the environmental variables to the names that you pointed, am I keep having the same issue, which is shown bellow.

--------------------------------------

Initializing app lungcancer-svm...

--------------------------------------

2024-01-06 12:56:22.775 | INFO     | cerebrium.secrets:populate_secrets:14 - Fetching secrets from Cerebrium Secrets for V3

Fetching secrets from Cerebrium Secrets for V3

2024-01-06 12:56:23.174 | INFO     | cerebrium.secrets:populate_secrets:24 - Secrets loaded successfully

Secrets loaded successfully

Initializing main.py ...

2024-01-06 12:56:26.077 | INFO     | cerebrium.secrets:get_secret:31 - Fetching secret for key: COMET_WORKSPACE

Fetching secret for key: COMET_WORKSPACE

2024-01-06 12:56:26.077 | INFO     | cerebrium.secrets:get_secret:31 - Fetching secret for key: COMET_API_KEY

Fetching secret for key: COMET_API_KEY

2024-01-06 12:56:26.077 | INFO     | cerebrium.secrets:get_secret:31 - Fetching secret for key: COMET_MODEL

Fetching secret for key: COMET_MODEL

Traceback (most recent call last):

File "/persistent-storage/.venv/miniconda/envs/lungcancer-svm/lib/python3.10/site-packages/comet_ml/connection.py", line 1985, in get

raise InvalidRestAPIKey(self.api_key)  # probably

comet_ml.exceptions.InvalidRestAPIKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

Failed to initialize main.py!

ERROR: |   Failed to build lungcancer-svm

**Comment by dsblank** [comment]
Where might comet_ml be getting a different api key? Maybe you have quotes (or spaces) around your secret values, or somehow they are wrong?
