### ISSUE TITLE
UI panel does not plot after logging metrics with `ExistingExperiment.log_metric()`

### ISSUE THREAD

**Issue by riyadhrazzaq** [comet-ml/issue-tracking#533]
## Describe the Bug
After continuing an experiment through the an `ExistingExperiment` object, the metrics are shown in the Metrics tab properly, however, the panel does not plot the metric values that are logged after continuing the experiment. This occurs sometimes. I have unable to find any pattern when it works or not.

## Expected behavior
The plots in Panel page should show new values when new metrics values are logged after logging them through `ExistingExperiment.log_metric` function.

## Where is the issue?
- [ ] Comet Python SDK
- [ x] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
1. Log some metric using `Experiment.log_metric()`
2. end the experiment with `Experiment.end()`
3. Open the experiment with `ExistingExperiment()`
4.  Log more values to metrics with `ExistingExperiment.log_metric()`
5. Look at the panel in UI, the plots should also contain new values.

**Comment by dsblank** [comment]
Make sure that when you log more metrics, that you pass in a step value that continues the sequence from the first experiment. That is, the default would increment step from 0, but when continuing make sure that step doesn't again start from 0.

**Comment by dsblank** [comment]
Please re-open ticket if you have additional information. Thanks!
