### ISSUE TITLE
Logging a metric for multiple classes to a single plot

### ISSUE THREAD

**Issue by Ritesh313** [comet-ml/issue-tracking#534]
## Is your feature request related to a problem? Please describe.
I am working on a multi-class classification problem where I compute and log the F1 score for each class at each epoch. I use a dictionary to store the F1 score for each class at each step, with the class name as the key and the F1 score as the value. I then log these metrics using the log_metrics method in PyTorch Lightning's CometLogger.
Here is a simplified version of my code:
```
scores = {k:v for k,v in zip(class_list, f1_vals)}
comet_logger.experiment.log_metrics(scores, prefix='test_f1', step=0)
```
Current Behavior:
Currently, Comet creates a separate plot for each class. This makes it difficult to compare the F1 scores for different classes, as I have to switch between different plots.

## Describe the solution you'd like
I would like to have the ability to log multiple metrics in a single plot at logging time. Ideally, the log_metrics method would accept a dictionary of metrics and log them in a single plot, with each key-value pair represented as a separate line in the plot. This would allow me to easily compare the F1 scores for different classes in a single view.

## Describe alternatives you've considered
Workaround:
Currently, I am manually adding the metrics for each class to a single plot and deleting the individual plots. However, this is a time-consuming process and it would be much more efficient if this could be done automatically at logging time.
I believe this feature would be beneficial for many users who are working on multi-class classification problems or any other tasks where they need to compare multiple metrics over time. 

## Additional context
Screenshot of plots for 2 classes (this is how they get logged and I have to delete them one by one, there isn't a select option for panels(?) which I could use to delete all at once):
![image](https://github.com/comet-ml/issue-tracking/assets/36135489/e34ffca3-967b-4f73-ad8f-5e296d67d67e)
Manually created panel with all plots in one
![image](https://github.com/comet-ml/issue-tracking/assets/36135489/352f819b-7d81-4465-a42c-6af50b74f55b)

**Comment by dsblank** [comment]
I provided some solutions in slack, including:

1. You could create a view that contains your workaround, and will always show these metrics
2. You could create a custom Panel to show the metrics you are interested in
3. You could use the `Experiment.log_curve()` method, and create a custom Panel
4. You could also create a plot and log with `Experiment.log_figure()`, but that is much less flexible in the long run.

But perhaps what is the best solution is to use a custom panel (either JavaScript or Python) and put a filter on it. The filter can match any criteria.

![Screenshot from 2024-01-28 09-45-05](https://github.com/comet-ml/issue-tracking/assets/168568/cb1cfdeb-a83d-4201-9da0-456d57de1f52)

**Comment by Ritesh313** [comment]
Thanks @dsblank! I have started using the custom view feature. I'll look into the custom panel too as that useful good for my use case.

**Comment by Ritesh313** [comment]
Hi Doug, I posted this on slack too, but might be useful to have an option to share views across projects (if it's not possible already).
