### ISSUE TITLE
Experiment created when downloading artifact

### ISSUE THREAD

**Issue by AlexandreBrown** [comet-ml/issue-tracking#540]
## Describe the Bug
When instantiating an `Experiment` class to download an artifact, the experiment gets created on cometml.com even tho I did not log anything.

## Expected behavior
A dummy experiment should not be created every time we donwload an artifact.  
No experiment should be created, we should be able to just download the artifact we want.

## Where is the issue?
- [x] Comet Python SDK
- [ ] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
```python
experiment = Experiment(api_key=api_key, project_name=project_name, workspace=workspace)
artifact = experiment.get_artifact(artifact_name)
artifact.download(output_dir)
```

## Comet Debug Log
[comet.log](https://github.com/comet-ml/issue-tracking/files/14624646/comet.log)

## Screenshots or GIFs
![image](https://github.com/comet-ml/issue-tracking/assets/26939775/65290e9c-eb86-47ef-8e84-4917888a3056)

## Additional context
Using `comet-ml` version `3.38.1`  
  
## Workaround  
- Delete the experiment after the download  
```python
from pathlib import Path
from comet_ml import Experiment
from comet_ml import API  

def download_artifact(api_key: str, project_name: str, workspace: str, artifact_name: str, output_dir: Path) -> Path:
    experiment = Experiment(api_key=api_key, project_name=project_name, workspace=workspace)
    artifact = experiment.get_artifact(artifact_name)
    artifact_path = Path(artifact.assets[0].logical_path)
    artifact.download(output_dir)
    
    # Workaround for deleting the dummy experiment created during the download
    api = API(api_key=api_key)
    api.delete_experiment(experiment_key=experiment.get_key())
    
    return output_dir / artifact_path
```

**Comment by dsblank** [comment]
@AlexandreBrown , indeed you are creating the experiment when you execute `Experiment()`.

You can use the `ExistingExperiment()` or the `APIExperiment()` class interfaces. See https://www.comet.com/docs/v2/api-and-sdk/python-sdk/experiment-overview/

One way: https://www.comet.com/docs/v2/api-and-sdk/python-sdk/reference/ExistingExperiment/#existingexperimentget_artifact

```
from comet_ml import ExistingExperiment

experiment = ExistingExperiment(previous_experiment=KEY)
experiment.get_artifact(...)
```

Another way: https://www.comet.com/docs/v2/api-and-sdk/python-sdk/reference/API/#apiget_artifact_files

```
from comet_ml import API

api = API()
api.get_artifact_files("demo", artifact_name="demo-artifact", version="2.0.0")
```
