### ISSUE TITLE
'Return to experiments' vs 'Return to project'

### ISSUE THREAD

**Issue by kirilllzaitsev** [comet-ml/issue-tracking#549]
## Describe the Bug
I open experiments from the 'Experiments' tab. However, the button on screenshots changes non-deterministically from 'Return to Project' to 'Return to experiments'. Ideally, the button returns to the page from which the experiment page was opened. Always 'Return to experiments' would be also great.

## Expected behavior
The button follows some fixed rule.

## Where is the issue?
- [ ] Comet Python SDK
- [+] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
1. Go to 'Experiments'
2. Open an experiment
3. Observe the button 'Return to Project'
4. Repeat 1-2 (some number of times)
5. Observe the same button becoming 'Return to experiments'

## Screenshots or GIFs

![image](https://github.com/comet-ml/issue-tracking/assets/44346535/18a0eb2c-19b2-4f82-981b-053075f482de)
![image](https://github.com/comet-ml/issue-tracking/assets/44346535/0483313f-d834-4aa9-b4a7-833301e0406b)

**Comment by kirilllzaitsev** [comment]
And a feature request: could you add the button to copy experiment's name just like its ID? Right now copying the name requires some effort..
![image](https://github.com/comet-ml/issue-tracking/assets/44346535/f2ed4761-bcf8-4655-bb39-bad499acd4e3)

**Comment by jverre** [comment]
Hi @kirilllzaitsev 
Thanks for the feedback !

1. `Return to experiments` issue: Indeed, the button should always return you to the page you came from. I tried to reproduce the issue but couldn't, I'll investigate this further
2. Thanks for the letting us know, I'll raise it internally and we will fix it for the next release
3. I'll pass this on to the team

**Comment by jverre** [comment]
@kirilllzaitsev I think I was able to reproduce the first issue:
1. Go to project Experiments tab
2. Go to an experiment by clicking on the name (same tab / page)
3. Click on experiment name (to try and copy it for example)
4. -> Button changes from `Return to experiments` to `Return to Project`

or
1. Go to project Experiments tab
2. Open an experiment in a new tab
-> Button is `Return to Project` instead of `Return to experiment`

Is the flow you described above one of these two ?

**Comment by kirilllzaitsev** [comment]
@jverre , the first one I guess. In my case, the button changes to 'Return to Project' not necessarily from the first time an experiment is opened
