### ISSUE TITLE
Wrong start/endTimeMillis?

### ISSUE THREAD

**Issue by piratinskii** [comet-ml/issue-tracking#550]
## Describe the Bug
Duration of the experiment doesn't match in the website and in the API. I got 00:08:13 in the website, but only 4 milliseconds on the API. 

## Expected behavior
endTimeMillis - startTimeMillis = Duration in milliseconds

## Where is the issue?
- [ ] Comet Python SDK
- [ ] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
1. Check the duration in the website
2. Check endTimeMillis - startTimeMillis in the API for the same experiment
## Stack Trace
If possible please include the full stack trace of your issue here

```
# Paste stack trace here
```

## Comet Debug Log
If possible, please follow the instructions [here](https://www.comet.ml/docs/python-sdk/advanced/#troubleshooting) to run Comet in debug mode and attach the resulting log file.  

## Screenshots or GIFs
![image](https://github.com/comet-ml/issue-tracking/assets/111863964/a4d2202f-dc8b-4ec2-b7d6-125cc9bb4588)
![image](https://github.com/comet-ml/issue-tracking/assets/111863964/f7754204-b3ff-4d68-924d-1c5d2dbf827f)

## Link to Comet Project/Experiment
[If applicable, please provide a link to your Comet Project or Experiment. ](https://www.comet.com/piratinskii/comparison-yolov10/807b0f20ab534d2bb4c57d0aa9929cf7?compareXAxis=step&experiment-tab=panels&showOutliers=true&smoothing=0&xAxis=step)

**Comment by dsblank** [comment]
Perhaps the experiment was in the middle of still logging its data? I looked at the metadata for the experiment, and it looks correct now:

```json
{
  "experimentKey": "807b0f20ab534d2bb4c57d0aa9929cf7",
  "experimentName": "entitled_parapet_204",
  "optimizationId": null,
  "userName": "piratinskii",
  "projectId": "c6964e6e81af4e03bf211172e4c4f8b1",
  "projectName": "comparison-yolov10",
  "workspaceName": "piratinskii",
  "filePath": "/home/sceuser/AthenaSky/yolo_train.py",
  "fileName": "yolo_train.py",
  "throttle": false,
  "throttleMessage": "",
  "throttlingReasons": [],
  "durationMillis": 493974,
  "startTimeMillis": 1718543791405,
  "endTimeMillis": 1718544285379,
  "running": false,
  "error": "Unexpected error detected in the user script: KeyboardInterrupt()",
  "hasCrashed": true,
  "archived": false,
  "tags": [],
}
```
And the times checkout:

```
>>> ((endTimeMillis - startTimeMillis) / 1000) / 60
8.232899999999999
```

**Comment by dsblank** [comment]
Thanks for the additional information. I'll check that endpoint and will report any issues to the engineering team.

**Comment by dsblank** [comment]
I was able to replicate. Reported as CM-10771. Thanks again for reporting!

**Comment by dsblank** [comment]
The fix for this is scheduled to be made soon.

**Comment by dsblank** [comment]
Now being tested...

**Comment by dsblank** [comment]
This fix is now available on comet.com and will be available in on-prem installations in the next release.

Thanks for reporting!
