### ISSUE TITLE
Cannot display points logged with log_points_3d

### ISSUE THREAD

**Issue by kirilllzaitsev** [comet-ml/issue-tracking#551]
## Where is the issue?
- [ ] Comet Python SDK
- [+] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce

```
pcl = np.random.rand(1000, 3)
exp.log_points_3d(scene_name="random_points", points=pcl)
```

Go to Assets and confirm it was logged:
![image](https://github.com/comet-ml/issue-tracking/assets/44346535/1c87754d-5e00-406e-81f0-62b63c67e700)

Go to Panels and try to add a 3D panel:
![image](https://github.com/comet-ml/issue-tracking/assets/44346535/c67439d3-ed27-4fd3-b828-579e7591e31a)

There are no suggestions and typing 'random..' doesn't help, making it a problem to visualize the logged asset.

**Comment by dsblank** [comment]
I suspect that if you look in the comet.log file, you'll see a warning about the points are not a list or tuple. Try:

```python
pcl = np.random.rand(1000, 3)
exp.log_points_3d(scene_name="random_points", points=pcl.tolist())
```

**Comment by kirilllzaitsev** [comment]
@dsblank I tried `pcl.tolist()` and it didn't have any effect. The original problem remains
