### ISSUE TITLE
🐛 in Y-axis of Loss Graph 

### ISSUE THREAD

**Issue by LuluW8071** [comet-ml/issue-tracking#555]
## Describe the Bug
The same line of code logs correct loss values for train_loss graph that is logged for 50steps and another loss graph logs different value.

## Expected behavior
Y-axis of both graphs need to be on same range

## Where is the issue?
- [ ] Comet Python SDK
- [x] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## Stack Trace
If possible please include the full stack trace of your issue here

```py
self.log('train_loss', loss, on_step=True, on_epoch=False, prog_bar=True, logger=True, sync_dist=self.sync_dist)
```

## Screenshots or GIFs
![image](https://github.com/user-attachments/assets/486a6547-b0a5-4ede-bf0a-be49ec419af0)

## Link to Comet Project/Experiment

[link to project](https://www.comet.com/luluw8071/speechrecognition-2/ec83107bb4584a6cb5fc44a916e17565)

**Comment by dsblank** [comment]
Hello @LuluW8071! What is the "self" in the above code? I don't of a `log()` method in any Comet SDK.

**Comment by LuluW8071** [comment]
> What is the "self" in the above code? I don't know of a `log()` method in any Comet SDK.

Thanks for responding @dsblank. The `self.log` logs the metrics on progress bar which also logs in comet_ml. 

The full trainer code can be found [here](https://www.comet.com/luluw8071/speechrecognition-2/ec83107bb4584a6cb5fc44a916e17565?experiment-tab=code&file=3c3041bbc1944bcabcca0f7e7acbe2d1)
