### ISSUE TITLE
OSError: [Errno 28] No space left on device 

### ISSUE THREAD

**Issue by kargarisaac** [comet-ml/issue-tracking#556]
## Describe the Bug
I started to use comet recently and when I do the logging, I get an error which seems to be the size of the `tmp` dir.

## Expected behavior
I should log normally without an error.

## Where is the issue?
- [x] Comet Python SDK
- [ ] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## Stack Trace
If possible please include the full stack trace of your issue here

```
OSError: [Errno 28] No space left on device 
```

## Comet Debug Log
If possible, please follow the instructions [here](https://www.comet.ml/docs/python-sdk/advanced/#troubleshooting) to run Comet in debug mode and attach the resulting log file.  

## Screenshots or GIFs
If applicable, add screenshots/gifs to help explain your problem.

## Link to Comet Project/Experiment
If applicable, please provide a link to your Comet Project or Experiment.

**Comment by dsblank** [comment]
@kargarisaac, you can control the comet_ml logging (and even disable it). Details: https://staging.dev.comet.com/docs/v2/guides/experiment-management/configure-sdk/#explore-comet-configuration-options

Check out the `[comet_logging]` section.
