### ISSUE TITLE
Allow users working offline to save run data in experiment object 

### ISSUE THREAD

**Issue by ceceshao1** [comet-ml/issue-tracking#56]
**First requested by Adhish Thite**

"Sometimes, people have to run their jobs on a cluster, which does not necessarily allow socket connections. So the use of Comet is impossible in such environments.

If the data of the run is stored in the Experiment object, we can load that object from memory and then upload it after the running has been completed.

**Comment by adhishthite** [comment]
Hey guys, can you kindly work on this? This will really be helpful!

**Comment by gidim** [comment]
Hi @adhishthite 
We're starting to work on this now. We'll keep you updated!

**Comment by adhishthite** [comment]
Thanks! Looking forward to getting this feature soon. All the best. :)

**Comment by a2dsouza** [comment]
Just wanted to say that I'd really love to see this feature as well. Looking forward to it.

**Comment by neighthan** [comment]
This would also be very helpful for things like the Comet website outage today; I removed all of my local logging because logging to Comet was nicer (and I just pull the data through the REST API when I need to do custom charts and such), but now I'm waiting to run some experiments until the site is back up. I came here just to check how this issue was doing; hope to see this before too long!

**Comment by pierthodo** [comment]
Any timeline on this feature ? I would love to start using comet.ml but can not until this feature is available.

**Comment by ceceshao1** [comment]
**Comet Offline Experiment Support** is officially out of beta!

The `OfflineExperiment()` interface allows you to store your experiment data on your local disk until you are ready to upload it to Comet.ml — very useful for scenarios where you may not have an internet connection in the training machine.

**Get started with Offline Experiments here:** https://www.comet.ml/docs/python-sdk/offline-experiment/
