### ISSUE TITLE
Comet-ML chart showing more epochs than the number of epochs in the code

### ISSUE THREAD

**Issue by preetskhalsa97** [comet-ml/issue-tracking#57]
![comet](https://user-images.githubusercontent.com/5739418/41144411-7b9a5e94-6b1a-11e8-920e-95c1474e28ec.png)

It shows epoch#63 while the code runs for only 50 epochs. How to interpret this?

**Comment by gidim** [comment]
Hi @preetskhalsa97 
Thanks for the feedback. We're looking into this. This might be an issue with Keras reporting twice with `ImageDataGenerator()`
