### ISSUE TITLE
Improve documentation around Comet.ml errors for debugging 

### ISSUE THREAD

**Issue by ceceshao1** [comet-ml/issue-tracking#58]
Provide more information around potential causes + fixes for the following errors:
- COMET WARNING: Failed to parse argv values. Falling back to naive parsing.
- COMET ERROR: Run will not be logged
- COMET ERROR: Streaming error

> Internal: Story #874

**Comment by ceceshao1** [comment]
Update on this issue: we've released a new section in our documentation around sdk errors + warnings. Here's the link to this section: https://www.comet.ml/docs/python-sdk/errors-warnings/

We'll continue updating this section if folks have more questions (reach out through our [slack group](https://join.slack.com/t/cometml/shared_invite/enQtMzM0OTMwNTQ0Mjc5LTM4ZDViODkyYTlmMTVlNWY0NzFjNGQ5Y2Q1Y2EwMjQ5MzQ4YmI2YjhmZTY3YmYxYTYxYTNkYzM4NjgxZmJjMDI)

**Comment by sotte** [comment]
The link https://www.comet.ml/docs/python-sdk/errors-warnings/ is a 404. More information regarding the errors would be great.

I also get the `COMET ERROR: Failed to setup the std logger` error sometimes.

**Comment by ceceshao1** [comment]
@sotte - you're on fire today! Thanks for reporting. We're looking at this right now.

**Comment by sotte** [comment]
@ceceshao1 you're welcome :)

I would also appreciate some information regarding `COMET ERROR: Failed to setup the std logger`.

**Comment by dsblank** [comment]
We have added a new config flag, COMET_LOGGING_CONSOLE. Set that to "info" and not only will you see the standard logging, but you will also see tracebacks in the console for better and easier diagnosing of such issues as you identify above.

To send that information to a file, see: https://www.comet.ml/docs/python-sdk/advanced/#trouble-shooting

If you have further questions or comments, please re-open. Thanks for reporting!
