### ISSUE TITLE
logged data doesn't show up in web

### ISSUE THREAD

**Issue by amn41** [comet-ml/issue-tracking#60]
running in anaconda python 3.5.4 

comet_ml '1.0.16' (from pypi today)

run the following script:

```python
from comet_ml import Experiment
experiment = Experiment(api_key=[redacted], auto_param_logging=False)

batch_size = 128
num_classes = 10
epochs = 20

params={
    "batch_size":batch_size,
    "epochs":epochs,
    "num_classes":num_classes}

experiment.log_metric("loss", 1000., step=0)
experiment.log_metric("loss", 999, step=1)
experiment.log_metric("loss", 998, step=2)
experiment.log_multiple_params(params)
```

result:
```
$ python try_comet.py
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/[redacted]

COMET INFO: Uploading stats to Comet before program termination (may take several seconds)
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/[redacted]
```

expected result:
- see some metrics at the logged url
observed result:
- always `No plotable data points were found`

**Comment by ceceshao1** [comment]
@amn41 - Hi Alan - thanks for reporting! Our team is investigating right now and will respond soon once there's a resolution (suspect it's a data processing bug). Important to note: there will be no data loss.

**Comment by ceceshao1** [comment]
@amn41 - another update: the issue has now been resolved so you should see your metrics data successfully showing.

Please verify and close the issue if the fix worked for you!

**Comment by amn41** [comment]
awesome, thank you!

**Comment by naefl** [comment]
Doesn't work for me still, exact same issue - I confirmed the right key with

`exp.get_key` & `exp.log_metrics`doesn't throw an error.

**Comment by dsblank** [comment]
@naefl Can you either email me specifics (doug@comet.ml) or send the details to support@comet.ml. That will allows us to see what is happening. Also, you may be interested in this section of the docs on downsampling: https://www.comet.ml/docs/python-sdk/warnings-errors/#rate-limits
