### ISSUE TITLE
Support option to overwrite a figure

### ISSUE THREAD

**Issue by noahyonack** [comet-ml/issue-tracking#61]
When I run a script that hooks into an existing experiment (and which logs a figure with a name that has already been used), the figure is appended to the graphics tab with the same name as opposed to overwriting the first figure.

It'd be nice to have the option of overwriting figures if there's a name clash. e.g.

`experiment.log_figure(figure_name="name", figure=fig, overwrite=True)`

**Comment by ceceshao1** [comment]
Hello (again) @noahyonack! This request makes a lot of sense - thanks for suggesting! We'll add it to our roadmap and update you when there's progress!

**Comment by gidim** [comment]
Hi @noahyonack 
We recently released a feature that allows you to filter images by name. While we don't overwrite images you can easily filter by name and look at the last one. Does that solve your issue? 
If not we'll add the overwrite flag.

**Comment by noahyonack** [comment]
Hi @gidim 

Thanks! I'll try it out — I think the motivation for the overwrite flag is to eliminate confusion about which image I should be looking at. Sounds like filtering might solve for that. I'll keep you posted.

**Comment by tom-roddick** [comment]
Hi! Just +1ing this issue: the option to overwrite figures would be extremely useful as the graphics tab quickly becomes very cluttered and unresponsive if large numbers of figures are generated. This is especially problematic for visualising outputs during training which I think is quite a common use case.

**Comment by gidim** [comment]
Hi @tom-roddick 
Thanks - we'll add this!

**Comment by gidim** [comment]
@tom-roddick @noahyonack 
Version 1.0.33 now supports overwriting figures. The API might look familiar to you (:
experiment.log_figure(figure_name="name", figure=fig, overwrite=True)

The key used to overwrite is the figure name.
