### ISSUE TITLE
Results from REST API are limited to 40 experiments 

### ISSUE THREAD

**Issue by ceceshao1** [comet-ml/issue-tracking#62]
First reported by Sebastian B. via Intercom:
> "Hello Cecelia, I am using your rest api and noticed that I cannot get a request response which contains more than 40 elements (e.g. list of experiments in a project in which I have > 40 experiments). Could you tell me if you use some response length limits or request rate restriction? Is there a way to get the rest of the results which did not fit in the first request (e.g. get list of experiments from given project starting from exp. number 40)? Thank you in advance"

**Comment by Nimrod007** [comment]
fixed.
