### ISSUE TITLE
Allow manual upload of images and deletion of images 

### ISSUE THREAD

**Issue by ceceshao1** [comet-ml/issue-tracking#69]
### Proposed state:
- allow user to drag images to the notes & resize
- allow user to upload images from filesystem
- allow user to delete images once it's uploaded 

### Current state:
For project and experiment notes, images can currently be uploaded via a link. Once an image is uploaded, it cannot be deleted 
![image](https://user-images.githubusercontent.com/24228106/42515877-cab454d4-842a-11e8-938e-86d2d538fad8.png)

**Comment by ceceshao1** [comment]
Update on this issue: our experiment + project Notes support markdown now (see more details in our latest [Release Notes](https://www.notion.so/cometml/Comet-ml-Release-Notes-93d864bcac584360943a73ae9507bcaa) for July 23, 2018).

These updated Notes allow for you to manually upload images.

We are still working on the feature to allow users to delete images once they've been uploaded to the `Graphics` tab

**Comment by florianblume** [comment]
Any news on the possibility to manually delete images from the experiment on the website? Or deleting them through Python?

**Comment by Jupestrone** [comment]
Any news on the possibility to manually delete images from the experiment on the website? Or deleting them through Python?
