### ISSUE TITLE
Name does not appear in Experiments view

### ISSUE THREAD

**Issue by dharness** [comet-ml/issue-tracking#71]
The experiments list for a project shows the name field but no values:

<img width="1272" alt="screen shot 2018-07-10 at 3 58 56 pm" src="https://user-images.githubusercontent.com/8755912/42542124-367ee70e-845a-11e8-9e60-265d11a83955.png">

Despite the value being shown under the other tab:

<img width="1246" alt="screen shot 2018-07-10 at 3 59 45 pm" src="https://user-images.githubusercontent.com/8755912/42542139-49efddf2-845a-11e8-9c4f-11bd1c63ff43.png">

This makes it impossible to filter by that attribute

**Comment by gidim** [comment]
Thanks for the feedback!
This should be resolved in the next release on Thursday 7/11.

**Comment by gidim** [comment]
Issue resolved.
