### ISSUE TITLE
Experiment comparison graphs are mislabeled!

### ISSUE THREAD

**Issue by bw4sz** [comet-ml/issue-tracking#74]
I think the chart labels are flipped in the experiment comparison tool.

see:

https://www.comet.ml/bw4sz/deepforest-retinanet/4db40013d57948cbacf2bf5e224815d2/1a7ac253fbe942158d2060528ba4553e/compare?experiment-tab=chart

In the bottom figure, the line labeled "loss_2" comes from experiment 1, and the line labeled "loss 1" comes from experiment 2.

<img width="1206" alt="screen shot 2018-07-12 at 10 46 44 am" src="https://user-images.githubusercontent.com/1208492/42650447-429fa70e-85c1-11e8-99a8-0ae2559aef81.png">

This confused me for a bit. The two experiments differ in batch size (experiment 2 is batch = 5), and I only noticed because its impossible for larger batch run to finish after a smaller batch run.

**Comment by ceceshao1** [comment]
@bnbarak - heads up on this compare charts bug

**Comment by ceceshao1** [comment]
We've pushed a fix for this bug! Please confirm that you don't see this anymore @bw4sz! Thanks again for reporting.
