### ISSUE TITLE
Order of metrics on chart

### ISSUE THREAD

**Issue by sbysiak** [comet-ml/issue-tracking#76]
I noticed that while adding a new metrics chart, there is no way to control order in which metrics appear on the chart.
It can be misleading in case of same/similar variables are shown on various charts with different color, 
e.g. on picture below I would like to have same colors for validation/train metrics on each chart.
![image](https://user-images.githubusercontent.com/15728684/42842353-46fb54d8-8a0d-11e8-979c-b4686a26c6e1.png)

I'm not sure if it's a bug or rather a feature request, but it would be expected by me that metrics appear on chart in  the order of clicking on / choosing them.

Adding #63 would also solve the issue.

**Comment by gidim** [comment]
Thanks for the feedback @sbysiak 
We're looking into a way to give you a more consistent experience.

**Comment by gidim** [comment]
@sbysiak We release a fix for this. 
From now the colors would be selected based on the order of the metrics chosen.
