### ISSUE TITLE
Awkward rounding for very small metric decimals 

### ISSUE THREAD

**Issue by bw4sz** [comet-ml/issue-tracking#80]
I monitor mean average precision for my experiments. This value can range between 0 and 1. I made some poor parameter choices and got a very poorly performing model. Comet saw the very small value 0.0001 and tried to transform it into different units. 

![image](https://user-images.githubusercontent.com/1208492/43216093-d545297c-8ff2-11e8-884c-1a2f6fefc77d.png)

Which is fine (if a bit awkward) in graph. But the kicker is that in the experiment table it is shown as 1.66, which is a) impossible, and b) would falsely confuse someone looking at the table that this run was actually really good, because its a large number, when its actually really bad, and should be a small number.

I suggest that small values should be rounded and truncated, not transformed.

**Comment by ceceshao1** [comment]
Related to parsing issue (see https://github.com/comet-ml/issue-tracking/issues/83 as well)

**Comment by ceceshao1** [comment]
@bw4sz - this issue is fixed now. Please try expanding the width of your mAP column to see the full value.
