### ISSUE TITLE
Allow ability to cycle account API key 

### ISSUE THREAD

**Issue by ceceshao1** [comet-ml/issue-tracking#82]
> First reported via Twitter by Serpent.AI team 

https://twitter.com/Serpent_AI/status/1024029321508384770

`Love the platform so far! My only audible qualm has been the lack of an ability to cycle the account API key. I do live work on Twitch and didn't worry about it expecting to be able to cycle it for production but it's not possible so I had to make another account.`

**Comment by Nimrod007** [comment]
can be done in the setting page in the UI
