### ISSUE TITLE
Column sort is off (scientific notation)

### ISSUE THREAD

**Issue by ceceshao1** [comet-ml/issue-tracking#83]
> First reported via email by Omri M. 

`When sorting a column, I get the wrong sort. The first value in the list is the smallest (it's in scientific notation, look at the E)`

Screenshot:
![column sort bug](https://user-images.githubusercontent.com/24228106/43470063-a85fcb0c-94b5-11e8-8151-ecc65251561d.png)

**Comment by Nimrod007** [comment]
@rememberlenny - can you verify its resolved and close ?

**Comment by rememberlenny** [comment]
Issue resolved!
