### ISSUE TITLE
Allow manual editing of metrics/hyperparameter names 

### ISSUE THREAD

**Issue by ceceshao1** [comet-ml/issue-tracking#86]
> First suggested by Dany R. via email

`Think one thing that could be useful would be manual editing of metrics/hyperparameters names. Sometimes early during the ideation process of a project, I am still undecided about the better way to test and compare models, the best metrics, etc etc and I end up with models where the same metric may be under different names/prefixes (or sometimes I just mistype the name or forget to add the .test() context).`

`Now that I think of it, I realize there may be some problems regarding transparency (for instance, improving apparent performance by changing the name of the main metric to a secondary, better one), so maybe there should be an edit log somewhere. Just some food for thought, not sure if it's a use case common enough or if there's any way to do it without cluttering the interface too much.`

**Comment by sbysiak** [comment]
+1

**Comment by jacenkow** [comment]
+1

**Comment by Nimrod007** [comment]
we added an option to do this from the UI
