### ISSUE TITLE
Cloud Optimizer runs out of suggestions after 1 epoch

### ISSUE THREAD

**Issue by dolhasz** [comet-ml/issue-tracking#88]
As in title - optimizer responds with `no more suggestions available`

Here's  my code snippet - I am replacing the built-in model parameters with the suggestions from the Optimizer:

```
from comet_ml import Optimizer
from NeuralNetwork import NeuralNetwork

optimizer = Optimizer("N8uYmDHt4WtKR7HeldmX8sx3Q")
# Declare your hyper-parameters:
params = """
        lr real [0.000001, 0.0001] [0.00001]
        fb real [1.0, 3.6] [2.0]
        decay real [0.0000001, 0.1] [0.0001]
        """
optimizer.set_params(params)

while True:
    # Get a suggestion
    suggestion = optimizer.get_suggestion()

    nn = NeuralNetwork('./Configs/xval/RESNET_1_BCE.json')
    nn.build_model()

    nn.config.lr = suggestion["lr"]
    nn.config.f_beta = suggestion["fb"]
    nn.config.decay = suggestion["decay"]

    nn.compile_model()
    history = nn.gen_train()

    # Report the score back
    suggestion.report_score("accuracy", history.history['val_IoU'])
    del nn

**Comment by ceceshao1** [comment]
Our team has logged an internal issue for this - will update once we issue a fix!

**Comment by Lothiraldan** [comment]
@dolhasz Hello, I'm looking at your issue.

The `suggestion.report_score` is expecting a float, could you confirm that `history.history['val_IoU']` is a float? If not could you cast it with `float(history.history['val_IoU'])`.

If the score you send is a float, it would be helpful to get the suggestion values that you get and the score that you returns in order to pinpoint the exact problem.

**Comment by dolhasz** [comment]
Thanks for suggestions - the issue is solved, but not completely sure how. I rebuilt a simple experiment and it seemed to work. So obviously I was doing something stupid before - @Lothiraldan may have been correct regarding casting. Either way this can be closed now. Apologies for hassle.

**Comment by ceceshao1** [comment]
Thanks for the update @dolhasz. Feel free to comment if the issue arises again (I'll close for now).
