### ISSUE TITLE
Line Not Being Colored Correctly

### ISSUE THREAD

**Issue by ryanhausen** [comet-ml/issue-tracking#89]
In a plot I have a line that is supposed to be colored red-orange, but is getting plotted as black.

You can find the plot here: https://www.comet.ml/ryanhausen/reduced-dataset-cifar10/c6aef602c6274da182a4dd21b60608ea/d6fa55a545ab485a858628375f31ba1b/compare

The line is 'train_data_ratio'

**Comment by Nimrod007** [comment]
fixed.

**Comment by dsblank** [comment]
Looks like this is now fixed. We just released some very nice colorization enhancements. See: https://www.comet.ml/docs/user-interface/#experiment-table under Color.

Please let us know if you have any questions or issues.
