### ISSUE TITLE
Comet 1.0.23 update breaks Optimizer on Windows 10

### ISSUE THREAD

**Issue by dolhasz** [comet-ml/issue-tracking#90]
Spotted a bug with the latest version of the Python package (1.0.23)

When importing Optimizer on Windows this error is thrown: 

`No module named 'fcntl'`

Haven't got as far as looking for a fix yet, but I'll update if I find anything.

**Comment by ceceshao1** [comment]
Thanks for reporting this @dolhasz.

We're currently working on a fix for this bug. In the meantime, please downgrade comet to version 1.0.22 (see command below)

```
pip install -I comet_ml=1.0.22
```

**Comment by gidim** [comment]
Thanks @omri374! Closing this one.
