### ISSUE TITLE
No data is appearing in the web interface

### ISSUE THREAD

**Issue by ZeonTrevor** [comet-ml/issue-tracking#94]
Since a few minutes ago, no data from my experiments are getting logged in the web interface. Even though in the terminal I get the info that the experiment is live. The only thing that gets logged properly is the time spent. I have updated to the latest version of comet.ml 1.0.26. Also, updated the Experiment object initialisation from using "team_name" to "workspace".

<img width="500" alt="screen shot 2018-08-16 at 22 53 27" src="https://user-images.githubusercontent.com/4203328/44234591-4429ca80-a1a7-11e8-8b9a-8f1c15e625c4.png">

**Comment by Nimrod007** [comment]
Hi @ZeonTrevor - we have a data delay due to peak traffic. all data is saved and will show up soon on the site.

**Comment by ZeonTrevor** [comment]
@Nimrod007 Thanks for the update.
