### ISSUE TITLE
Serious Slow Down when using CometML

### ISSUE THREAD

**Issue by benjamink85** [comet-ml/issue-tracking#95]
I'm running an experiment using pytorch and comet-ml.
After a few iterations (~3500), it gets very slow (to the point where I can't run the experiment anymore). Upon removing comet-ml from the code, it returns to perform normally.

**Comment by Nimrod007** [comment]
Hi @benjamink85 - can you share experiment link ? (or code snippet) so we can re-create.

**Comment by benjamink85** [comment]
Hey. I'm still debugging to see if it's slow even without comet. Will
update.

**Comment by benjamink85** [comment]
Not a bug.
Closing.

**Comment by Fan-Luo** [comment]
I have the same issue when running jobs on HPC with GPU. My jobs usually run 8 epochs and finish within wall time, but only runs 2 epochs after add experiment. @benjamink85 Could you please share what happened to you and how was that solved? Thank you!
