### ISSUE TITLE
Give/edit model names for comparison charts from website

### ISSUE THREAD

**Issue by neighthan** [comet-ml/issue-tracking#97]
The new model comparison charts are very nice. The main drawback for me is that each line in the chart is referenced by the experiment key, which means nothing to me; I have to look up each experiment by key in my table every time I want to compare them. I'd like a way to **give experiments names in the web frontend and have those used as labels in the comparison charts** instead of the experiment keys. I know that you can already name an experiment using `Experiment.set_name` - will this be used instead of the key in the comparison charts, if it's given? This is similar to issue #86 which asks for editing of hyperparameter/metric names from the web GUI, though I also want to be able to give a name to an experiment that has none, not just edit existing names.

Here's what things look like now:

<img src="https://user-images.githubusercontent.com/12573501/44591823-bfcddd80-a78c-11e8-9d25-892eb0a77e88.png" height="300px">

I just want, instead of labels like "5ba68" to have names I set.

**Comment by ceceshao1** [comment]
This suggestion makes a lot of sense @neighthan! Will circle back to the team and see if we can enable an option to/update the name to reflect a set experiment name (as opposed to the key).

**Comment by slachapelle** [comment]
I'd like to add something to this enhancement:
Would be nice to be able to set those legend labels to anything logged in that experiment: hyperparameter, other, experiment name, ... etc. It would then be natural to add a "Custom" option that allows to directly enter the names by hand.
