### ISSUE TITLE
Group experiments in comparison charts

### ISSUE THREAD

**Issue by neighthan** [comet-ml/issue-tracking#98]
I often run a few repeats of an experiment to see how metrics vary across random initializations. I tend to make one of two types of charts in Python to look at this: either I take the mean and standard deviation of the metric at each step, for each set of repeats, and plot a curve with a shaded region for +/- 1 std or, if I want to see the differences directly, I plot each curve but I color the repeats the same color. I'd be glad to be able to make either or both of these charts in Comet ML. I'd imagine the comparison chart editor window having an additional option to select the name of a parameter of the models that you could group by (and if you support multiple types of grouped charts, a dropdown to select which kind, e.g. just color by group or only plot mean +/- std per group).

Here's an example of the sort of chart I'd like to make:

![image](https://user-images.githubusercontent.com/12573501/44592978-1ee12180-a790-11e8-8a95-8ed790687ca5.png)

And the second one mentioned, though it can get too messy:

![image](https://user-images.githubusercontent.com/12573501/44593438-543a3f00-a791-11e8-81bc-61667dad381b.png)

Here ABCDE are the values of the parameter by which I'm grouping the experiments.

If there's not enough support for this use case to be worth complicating the API, I can stick with making my own charts in Python =)

**Comment by ceceshao1** [comment]
Thanks for suggesting this interesting feature request @neighthan! We've placed it in our backlog and will reach out with updates/questions 👍

**Comment by neighthan** [comment]
You might even consider letting any parameter of an experiment be set as the "color by" variable (which is currently experiment key). Above, I've considered this only for categorical parameters, but, as long as the color palette is adapted, this could also be useful for continuous parameters.

Handling the legend gets a little tricky here, though; I think you'd want more than what my examples had. It might make sense, to have a colorbar somewhere (which shows what my legend above does; a colorbar is especially good when coloring by a continuous variable, though) in addition to the existing legend (showing experiment keys right now but maybe names in the future). Then the user could still toggle the visibility of different experiments, even though they'll need to hover over the lines to see which line corresponds to which experiment (since multiple will have the same color). If plotting mean + error region, being able to toggle visibility could still be nice, and it would keep things consistent, but I wouldn't expect hovering over the chart to show any specific experiment keys/names.

**Comment by fabawi** [comment]
This feature would be a great addition. The charts are not very useful if they cannot be grouped, especially if multiple runs represent a similar experiment. Maybe add a drop down for choosing how to combine the runs which were grouped together (e.g.: mean, median, max, min) and a margin appearing with a lower alpha (e.g.: min/max, mean+std/mean-std)

**Comment by backpropper** [comment]
This is a very useful tool for grouping multiple runs! You should make it a high priority.

**Comment by lucianoviola** [comment]
Yes, please prioritize this! I'm having to circumvent this by uploading custom matplotlib figures.

**Comment by dsblank** [comment]
You can now create exactly the type of plot described. Please see: https://www.comet.ml/docs/javascript-sdk/getting-started/
